import { getAscensionModifiers, getAscensionTier } from './endless/ascension.js';
import type { AscensionTierPressureIdentityId } from './ascension-tier-pressure-identity-assets.js';

export interface AscensionTierPressureEffect{id:Exclude<AscensionTierPressureIdentityId,'mutator-threshold'>;label:string;before:number;after:number;delta:number;kind:'pressure'|'reward';}
export interface AscensionTierOutcomeProjection{fromTier:number;toTier:number;mutatorThreshold:boolean;effects:AscensionTierPressureEffect[];primaryPressureIds:AscensionTierPressureIdentityId[];}
export interface AscensionTierForecastProjection extends AscensionTierOutcomeProjection{currentTier:number;nextTier:number|null;secondsToNext:number;visible:boolean;}
const MUTATOR_TIERS=new Set([3,6,9]);
const IDS=['enemy-health','enemy-damage','spawn-pressure','elite-pressure','gold','mastery'] as const;
function round2(v:number):number{return Math.round((v+Number.EPSILON)*100)/100;}
function valueFor(id:typeof IDS[number],mods:ReturnType<typeof getAscensionModifiers>):number{return id==='enemy-health'?mods.enemyHealthMultiplier:id==='enemy-damage'?mods.enemyDamageMultiplier:id==='spawn-pressure'?mods.spawnBudgetMultiplier:id==='elite-pressure'?mods.eliteBudgetMultiplier:id==='gold'?mods.goldMultiplier:mods.masteryXpMultiplier;}
function label(id:typeof IDS[number]):string{return id==='enemy-health'?'적 체력':id==='enemy-damage'?'적 피해':id==='spawn-pressure'?'스폰 압박':id==='elite-pressure'?'정예 압박':id==='gold'?'골드 보상':'숙련 보상';}
function compact(id:typeof IDS[number]):string{return id==='enemy-health'?'HP':id==='enemy-damage'?'피해':id==='spawn-pressure'?'스폰':id==='elite-pressure'?'정예':id==='gold'?'골드':'숙련';}
export function projectAscensionTierOutcome(tierInput:number):AscensionTierOutcomeProjection{const toTier=Math.max(1,Math.min(10,Math.floor(Number.isFinite(tierInput)?tierInput:1))),fromTier=Math.max(0,toTier-1),before=getAscensionModifiers(fromTier),after=getAscensionModifiers(toTier),effects=IDS.map(id=>({id,label:label(id),before:round2(valueFor(id,before)),after:round2(valueFor(id,after)),delta:round2(valueFor(id,after)-valueFor(id,before)),kind:(id==='gold'||id==='mastery'?'reward':'pressure') as 'pressure'|'reward'}));return{fromTier,toTier,mutatorThreshold:MUTATOR_TIERS.has(toTier),effects,primaryPressureIds:['enemy-health','enemy-damage']};}
export function projectAscensionTierForecast(elapsedMsInput:number):AscensionTierForecastProjection{const elapsedMs=Math.max(0,Number.isFinite(elapsedMsInput)?elapsedMsInput:0),currentTier=getAscensionTier(elapsedMs);if(currentTier>=10)return{...projectAscensionTierOutcome(10),currentTier:10,nextTier:null,secondsToNext:0,visible:false,effects:[],primaryPressureIds:[]};const nextTier=currentTier+1,nextAtMs=currentTier===0?30*60_000:(30+currentTier*10)*60_000,secondsToNext=Math.max(0,Math.ceil((nextAtMs-elapsedMs)/1000)),outcome=projectAscensionTierOutcome(nextTier);return{...outcome,currentTier,nextTier,secondsToNext,visible:secondsToNext>0&&secondsToNext<=90};}
export function ascensionTierPressureHint(projection:Pick<AscensionTierOutcomeProjection,'effects'|'mutatorThreshold'>,maxEffects=2):string{const pressure=projection.effects.filter(effect=>effect.kind==='pressure').slice(0,Math.max(0,maxEffects)).map(effect=>`${compact(effect.id)}+${effect.delta.toFixed(2)}×`);if(projection.mutatorThreshold)pressure.push('변이');return pressure.join(' · ');}
export function ascensionTierForecastLabel(projection:AscensionTierForecastProjection):string{return projection.nextTier===null?'A10 MAX':`A${projection.nextTier} ${projection.secondsToNext}s`;}
