export const HERO_ASCENSION_BUILD_DIRECTION_IDS=['expand','hybrid','focus'] as const;
export type HeroAscensionBuildDirectionId=typeof HERO_ASCENSION_BUILD_DIRECTION_IDS[number];
const CELL:Readonly<Record<HeroAscensionBuildDirectionId,number>>={expand:0,hybrid:1,focus:2};
const META:Readonly<Record<HeroAscensionBuildDirectionId,{label:string;accent:string}>>={expand:{label:'확장',accent:'#6ff0b2'},hybrid:{label:'혼합',accent:'#8bc8ff'},focus:{label:'집중',accent:'#ffd36f'}};
export interface HeroAscensionBuildDirectionIdentityIcon{id:HeroAscensionBuildDirectionId;label:string;accent:string;sx:number;sy:0;sw:96;sh:96;animated:false;motionAmplitude:0;textFallbackPreserved:true;loadFailureBlocksGameplay:false;}
export const HERO_ASCENSION_BUILD_DIRECTION_ATLAS={src:'./assets/ui/hero-ascension-build-direction-icons.png',columns:3,rows:1,cellSize:96,width:288,height:96} as const;
export function heroAscensionBuildDirectionIdentityIcon(id:HeroAscensionBuildDirectionId):HeroAscensionBuildDirectionIdentityIcon{const meta=META[id];return{id,label:meta.label,accent:meta.accent,sx:CELL[id]*96,sy:0,sw:96,sh:96,animated:false,motionAmplitude:0,textFallbackPreserved:true,loadFailureBlocksGameplay:false};}
export function heroAscensionBuildDirectionIdentityStyle(id:HeroAscensionBuildDirectionId):string{const cell=CELL[id];return`--secondary-icon-image:url('${HERO_ASCENSION_BUILD_DIRECTION_ATLAS.src}');--secondary-icon-bg-size:300% 100%;--secondary-icon-bg-position:${(cell/2)*100}% 0%`;}
export function auditHeroAscensionBuildDirectionIdentityAtlas(){const icons=HERO_ASCENSION_BUILD_DIRECTION_IDS.map(heroAscensionBuildDirectionIdentityIcon),outOfBounds=icons.filter(icon=>icon.sx<0||icon.sx+icon.sw>HERO_ASCENSION_BUILD_DIRECTION_ATLAS.width||icon.sy+icon.sh>HERO_ASCENSION_BUILD_DIRECTION_ATLAS.height).map(icon=>icon.id),uniqueCellCount=new Set(icons.map(icon=>`${icon.sx}:${icon.sy}`)).size,coverage=icons.length/3;return{coverage,uniqueCellCount,outOfBounds,passed:coverage===1&&uniqueCellCount===3&&outOfBounds.length===0};}
