import type { EquipmentState, EquippedItem } from '../domain/types.js';
import type { HeroId } from './hero-profiles.js';
import type { BuildArchetype } from './endless/build-overdrive.js';
import type { ShopDisplayOffer } from './shop-data.js';
import { quickShopRecommendation, shopGuidanceForOffers } from './shop-guidance.js';
export interface QuickBuyDwellSample{heroId:HeroId;archetype:BuildArchetype;stateKind:string;quickEligible:boolean;protectedSwap:boolean;unaffordable:boolean;legacyDwellMs:number;quickDwellMs:number;}
export interface QuickBuyDwellAudit{passed:boolean;heroCount:number;archetypeCount:number;samples:QuickBuyDwellSample[];quickEligibleCount:number;legacyTapCount:2;quickTapCount:1;tapReduction:number;estimatedDwellReduction:number;protectedSwapExposureCount:number;unaffordableExposureCount:number;issues:string[];}
const HEROES:HeroId[]=['arkan','seria','kain','edric'],ARCHETYPES:BuildArchetype[]=['burst','cycle','domain','fortress'];
const OFFERS:ShopDisplayOffer[]=[{id:'arcane-staff',kind:'weapon',name:'마력 지팡이',price:220,power:.15,description:'',accent:'#fff'},{id:'rapid-wand',kind:'weapon',name:'속사 완드',price:240,power:.07,description:'',accent:'#fff'},{id:'iron-robe',kind:'armor',name:'철갑 로브',price:200,power:.08,description:'',accent:'#fff'},{id:'guardian-plate',kind:'armor',name:'수호 갑주',price:230,power:.07,description:'',accent:'#fff'},{id:'healing-potion',kind:'potion',name:'체력 물약',price:70,power:.35,description:'',accent:'#fff'},{id:'healing-potion',kind:'potion',name:'체력 물약',price:80,power:.35,description:'',accent:'#fff'}];
function item(id:string,kind:'weapon'|'armor',rank:number,legendary=false):EquippedItem{const o=OFFERS.find((x)=>x.id===id)!;return{id,kind,name:o.name,rank,power:o.power,legendary};}
function protectedSwap(offer:ShopDisplayOffer,state:EquipmentState):boolean{if(offer.kind==='potion')return false;const current=offer.kind==='weapon'?state.weapon:state.armor;return Boolean(current&&current.id!==offer.id&&(current.rank>=3||current.legendary));}
export function auditQuickBuyDwell():QuickBuyDwellAudit{
 const states:readonly [string,(a:BuildArchetype)=>EquipmentState][]=[['empty',()=>({coins:1000,weapon:null,armor:null,healingPotions:1})],['upgrade',(a)=>({coins:1000,weapon:item(a==='cycle'?'rapid-wand':'arcane-staff','weapon',2),armor:null,healingPotions:1})],['protected',()=>({coins:1000,weapon:item('rapid-wand','weapon',3),armor:item('iron-robe','armor',3),healingPotions:2})],['legendary',()=>({coins:1000,weapon:item('rapid-wand','weapon',5,true),armor:item('iron-robe','armor',5,true),healingPotions:2})]];
 const samples:QuickBuyDwellSample[]=[];let quickEligibleCount=0,protectedSwapExposureCount=0,unaffordableExposureCount=0,legacyTotal=0,quickTotal=0;
 for(const heroId of HEROES)for(const archetype of ARCHETYPES)for(const [stateKind,make] of states){const state=make(archetype),guidance=shopGuidanceForOffers(OFFERS,{heroId,archetype,state}),offer=quickShopRecommendation(OFFERS,guidance,state),eligible=Boolean(offer),protectedSwapValue=offer?protectedSwap(offer,state):false,unaffordable=offer?offer.price>state.coins:false;const legacyDwellMs=guidance.length*120+2*330,quickDwellMs=eligible?120+330:legacyDwellMs;if(eligible){quickEligibleCount++;legacyTotal+=legacyDwellMs;quickTotal+=quickDwellMs;}if(protectedSwapValue)protectedSwapExposureCount++;if(unaffordable)unaffordableExposureCount++;samples.push({heroId,archetype,stateKind,quickEligible:eligible,protectedSwap:protectedSwapValue,unaffordable,legacyDwellMs,quickDwellMs});}
 const tapReduction=.5,estimatedDwellReduction=legacyTotal>0?1-quickTotal/legacyTotal:0,issues:string[]=[];if(quickEligibleCount<16)issues.push('quick-eligibility');if(tapReduction<.5)issues.push('tap-reduction');if(estimatedDwellReduction<.45)issues.push('dwell-reduction');if(protectedSwapExposureCount)issues.push('protected-swap-exposure');if(unaffordableExposureCount)issues.push('unaffordable-exposure');
 return{passed:issues.length===0,heroCount:HEROES.length,archetypeCount:ARCHETYPES.length,samples,quickEligibleCount,legacyTapCount:2,quickTapCount:1,tapReduction,estimatedDwellReduction,protectedSwapExposureCount,unaffordableExposureCount,issues};
}
