const clamp01=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
const smooth01=(value:number)=>{const x=clamp01(value);return x*x*(3-2*x);};
const slot4=(value:number)=>((Math.floor(Number.isFinite(value)?value:0)%4)+4)%4;
function recover(release:number,stress:number,critical:boolean,slot:number,normalMin:number,criticalMin:number,reducedMotion=false,reducedFlash=false){const s=slot4(slot),load=clamp01(stress),delay=Math.min(.38,s*.08+load*.04),normalized=clamp01((clamp01(release)-delay)/Math.max(.001,1-delay)),recovery=smooth01(normalized),minimum=critical?criticalMin:normalMin,motion=reducedMotion?.86:1,flash=reducedFlash?.96:1,secondaryScale=clamp01(Math.max(minimum,minimum+(1-minimum)*recovery*motion-load*(critical?.025:.06))*flash);return{slot:s,delay,recovery,primaryScale:1,secondaryScale,presentationOnly:true as const};}
export function projectileThreatRhythmRecoveryPresentation(input:{release:number;stress:number;critical:boolean;slot:number},reducedMotion=false,reducedFlash=false){return recover(input.release,input.stress,input.critical,input.slot,.42,.6,reducedMotion,reducedFlash);}
export function impactThreatRhythmRecoveryPresentation(input:{release:number;stress:number;critical:boolean;slot:number},reducedMotion=false,reducedFlash=false){return recover(input.release,input.stress,input.critical,input.slot,.38,.56,reducedMotion,reducedFlash);}
export function hazardThreatRhythmRecoveryPresentation(input:{release:number;stress:number;critical:boolean;slot:number},reducedMotion=false,reducedFlash=false){return recover(input.release,input.stress,input.critical,input.slot,.4,.58,reducedMotion,reducedFlash);}
export function safeLaneThreatRhythmRecoveryPresentation(input:{release:number;stress:number;critical:boolean;slot:number},reducedMotion=false,reducedFlash=false){return{...recover(input.release,input.stress,input.critical,input.slot,.48,.66,reducedMotion,reducedFlash),safeLaneScale:1,presentationOnly:true as const};}
export function specialistThreatRhythmRecoveryPresentation(input:{release:number;stress:number;critical:boolean;slot:number},reducedMotion=false,reducedFlash=false){return recover(input.release,input.stress,input.critical,input.slot,.4,.6,reducedMotion,reducedFlash);}
export function threatRhythmRecoveryBudgetPresentation(input:{activeCount:number;criticalCount:number;stress:number;release:number;safeLaneVisible:boolean},reducedMotion=false,reducedFlash=false){const active=Math.max(0,Math.floor(input.activeCount)),load=clamp01(input.stress),release=clamp01(input.release),critical=clamp01(Math.max(0,input.criticalCount)/3),maxConcurrentRecoveries=active>=10?1:active>=5?2:3,secondaryScale=Math.max(.5,.58+release*.34-load*.18-critical*.03)*(reducedMotion?.97:1)*(reducedFlash?.96:1);return{maxConcurrentRecoveries,primaryScale:1,secondaryScale:clamp01(secondaryScale),safeLaneScale:1,presentationOnly:true as const};}
