import{contourReleasePresentation}from'./threat-impact-contour-release-rendering.js';
const clamp01=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
const smooth01=(value:number)=>{const x=clamp01(value);return x*x*(3-2*x);};
function settle(primaryFloor:number,reacquire:number,stress:number,critical:boolean,normalFloor:number,criticalFloor:number,normalSecondary:number,criticalSecondary:number,reducedMotion=false,reducedFlash=false){const settled=smooth01(reacquire),load=clamp01(stress),unsettled=clamp01((1-settled)*.68+load*.32),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1,contour=contourReleasePresentation({reacquire,stress:load,critical},reducedMotion,reducedFlash);return{settle:settled,primaryFloor:clamp01(Math.max(primaryFloor,(critical?criticalFloor:normalFloor)+unsettled*.035)*flash),secondaryScale:Math.max(critical?criticalSecondary:normalSecondary,1-unsettled*(critical?.26:.42))*motion*flash*contour.secondaryContourScale,presentationOnly:true as const};}
export function projectileFinalReadabilitySettlePresentation(input:{primaryFloor:number;reacquire:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return settle(input.primaryFloor,input.reacquire,input.stress,input.critical,.42,.6,.5,.68,reducedMotion,reducedFlash);}
export function impactFinalReadabilitySettlePresentation(input:{primaryFloor:number;reacquire:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return settle(input.primaryFloor,input.reacquire,input.stress,input.critical,.34,.48,.42,.64,reducedMotion,reducedFlash);}
export function hazardFinalReadabilitySettlePresentation(input:{primaryFloor:number;reacquire:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return settle(input.primaryFloor,input.reacquire,input.stress,input.critical,.36,.5,.4,.62,reducedMotion,reducedFlash);}
export function safeLaneFinalReadabilitySettlePresentation(input:{primaryFloor:number;reacquire:number;stress:number;critical:boolean;confidence:number},reducedMotion=false,reducedFlash=false){const confidence=clamp01(input.confidence),p=settle(input.primaryFloor,input.reacquire,input.stress,input.critical,.6+confidence*.12,.68+confidence*.06,.5,.66,reducedMotion,reducedFlash);return{...p,primaryFloor:clamp01(Math.max(p.primaryFloor,.6+confidence*.14)),presentationOnly:true as const};}
export function specialistFinalReadabilitySettlePresentation(input:{primaryFloor:number;reacquire:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return settle(input.primaryFloor,input.reacquire,input.stress,input.critical,.4,.5,.46,.64,reducedMotion,reducedFlash);}
export function finalReadabilitySettleBudgetPresentation(input:{criticalCount:number;stress:number;bossActive:boolean;safeLaneVisible:boolean},reducedMotion=false,reducedFlash=false){const critical=clamp01(Math.max(0,input.criticalCount)/3),stress=clamp01(input.stress),load=clamp01(stress*.82+critical*.18+(input.bossActive?.04:0));return{stress:load,primaryScale:1,secondaryScale:Math.max(.5,1-load*.34)*(reducedMotion?.97:1)*(reducedFlash?.97:1),safeLaneScale:input.safeLaneVisible?1+load*.025*(reducedFlash?.9:1):1,presentationOnly:true as const};}
