const clamp01=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
const smooth01=(value:number)=>{const x=clamp01(value);return x*x*(3-2*x);};
function gate(release:number,stress:number,critical:boolean,normalMin:number,criticalMin:number,reducedMotion=false,reducedFlash=false){const recovery=smooth01(release),load=clamp01(stress),floor=critical?criticalMin:normalMin,open=clamp01(floor+(1-floor)*recovery-load*(1-recovery)*.12),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{release:recovery,secondaryScale:Math.max(floor*.94,open)*motion*flash,canonicalScale:1,presentationOnly:true as const};}
export function projectileSecondaryRecoveryGatePresentation(input:{release:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return gate(input.release,input.stress,input.critical,.5,.68,reducedMotion,reducedFlash);}
export function impactSecondaryRecoveryGatePresentation(input:{release:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return gate(input.release,input.stress,input.critical,.42,.62,reducedMotion,reducedFlash);}
export function hazardSecondaryRecoveryGatePresentation(input:{release:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return gate(input.release,input.stress,input.critical,.4,.6,reducedMotion,reducedFlash);}
export function safeLaneSecondaryRecoveryGatePresentation(input:{release:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return gate(input.release,input.stress,input.critical,.5,.66,reducedMotion,reducedFlash);}
export function specialistSecondaryRecoveryGatePresentation(input:{release:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){return gate(input.release,input.stress,input.critical,.46,.64,reducedMotion,reducedFlash);}
export function secondaryRecoveryGateBudgetPresentation(input:{criticalCount:number;stress:number;release:number},reducedMotion=false,reducedFlash=false){const critical=clamp01(Math.max(0,input.criticalCount)/3),stress=clamp01(input.stress),release=smooth01(input.release),hold=clamp01((1-release)*.72+stress*.2+critical*.08);return{hold,canonicalScale:1,secondaryScale:Math.max(.48,1-hold*.42)*(reducedMotion?.97:1)*(reducedFlash?.97:1),presentationOnly:true as const};}
