const clamp01=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));
const smooth01=(value:number)=>{const x=clamp01(value);return x*x*(3-2*x);};

export function projectileImpactPeakSeparationPresentation(input:{trailPeak:number;impactPeak:number;proximity:number;critical:boolean},reducedMotion=false,reducedFlash=false){const overlap=clamp01(Math.min(clamp01(input.trailPeak),clamp01(input.impactPeak))*smooth01(input.proximity)),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{peakOverlap:overlap,canonicalScale:1,trailScale:Math.max(input.critical?.56:.48,1-overlap*(input.critical?.3:.36))*motion*flash,impactInteriorScale:Math.max(input.critical?.5:.42,1-overlap*(input.critical?.38:.45))*motion*flash,presentationOnly:true as const};}

export function bossHazardPeakSeparationPresentation(input:{bossPeak:number;hazardPeak:number;overlap:number;critical:boolean},reducedMotion=false,reducedFlash=false){const peak=clamp01(Math.min(clamp01(input.bossPeak),clamp01(input.hazardPeak))*smooth01(input.overlap)),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{peakOverlap:peak,bossEdgeScale:1,hazardInteriorScale:Math.max(input.critical?.4:.34,1-peak*(input.critical?.48:.56))*motion*flash,bossInteriorScale:Math.max(.5,1-peak*.3)*motion*flash,presentationOnly:true as const};}

export function safeLaneBossPeakPriorityPresentation(input:{laneConfidence:number;bossPeak:number;crossing:number;critical:boolean},reducedMotion=false,reducedFlash=false){const lane=clamp01(input.laneConfidence),crossing=clamp01(input.crossing),pressure=clamp01(lane*crossing*clamp01(input.bossPeak)),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{pressure,safeLaneScale:(1+pressure*.06)*flash,bossEdgeScale:Math.max(input.critical?.86:.8,1-pressure*.1)*flash,bossInteriorScale:Math.max(.42,1-pressure*.46)*motion*flash,canonicalScale:1,presentationOnly:true as const};}

export function specialistRecoveryTrailPeakPresentation(input:{facingPeak:number;recoveryPeak:number;stress:number;critical:boolean},reducedMotion=false,reducedFlash=false){const overlap=clamp01(Math.min(clamp01(input.facingPeak),clamp01(input.recoveryPeak))*(.72+.28*clamp01(input.stress))),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{peakOverlap:overlap,specialistDirectionScale:1,recoveryTrailScale:Math.max(input.critical?.48:.4,1-overlap*(input.critical?.46:.52))*motion*flash,canonicalScale:1,presentationOnly:true as const};}

export function criticalCorridorTemporalReservePresentation(input:{corridorPressure:number;secondaryPeak:number;criticalCount:number;heroProximity:number},reducedMotion=false,reducedFlash=false){const critical=clamp01(Math.max(0,input.criticalCount)/3),reserve=clamp01(clamp01(input.corridorPressure)*.55+clamp01(input.secondaryPeak)*.2+critical*.15+clamp01(input.heroProximity)*.1),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{reserve,corridorScale:1,canonicalScale:1,secondaryScale:Math.max(.44,1-reserve*.52)*motion*flash,presentationOnly:true as const};}

export function crossFamilyPeakBudgetPresentation(input:{activePeakFamilies:number;crowd:number;criticalCount:number;safeLaneVisible:boolean;bossActive:boolean},reducedMotion=false,reducedFlash=false){const families=clamp01(Math.max(0,input.activePeakFamilies)/5),crowd=clamp01(input.crowd),critical=clamp01(Math.max(0,input.criticalCount)/3),load=clamp01(families*.52+crowd*.24+critical*.14+(input.safeLaneVisible?.05:0)+(input.bossActive?.05:0)),motion=reducedMotion?.97:1,flash=reducedFlash?.97:1;return{load,canonicalScale:1,secondaryScale:Math.max(.5,1-load*.46)*motion*flash,safeLaneScale:(input.safeLaneVisible?1+load*.045:1)*flash,bossEdgeScale:(input.bossActive?Math.max(.86,1-load*.08):1)*flash,presentationOnly:true as const};}
