const clamp01=(value:number)=>Math.max(0,Math.min(1,Number.isFinite(value)?value:0));

export function criticalTemporalPriorityPresentation(input:{criticalCount:number;pressure:number;secondaryPeak:number;heroProximity:number},reducedMotion=false,reducedFlash=false){const critical=clamp01(Math.max(0,input.criticalCount)/3),reserve=clamp01(clamp01(input.pressure)*.5+clamp01(input.secondaryPeak)*.2+critical*.2+clamp01(input.heroProximity)*.1),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{reserve,criticalScale:1,canonicalScale:1,secondaryScale:Math.max(.44,1-reserve*.56)*motion*flash,presentationOnly:true as const};}

export function safeLaneTemporalPriorityPresentation(input:{confidence:number;crossing:number;bossPressure:number;secondaryPeak:number;critical:boolean},reducedMotion=false,reducedFlash=false){const pressure=clamp01(clamp01(input.confidence)*.35+clamp01(input.crossing)*.25+clamp01(input.bossPressure)*.22+clamp01(input.secondaryPeak)*.18),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{pressure,safeLaneScale:(1+clamp01(input.confidence)*.05)*flash,bossEdgeScale:Math.max(input.critical?.86:.84,1-pressure*.12)*flash,canonicalScale:1,secondaryScale:Math.max(.42,1-pressure*.55)*motion*flash,presentationOnly:true as const};}

export function bossTelegraphTemporalPriorityPresentation(input:{charge:number;hazardPressure:number;secondaryPeak:number;critical:boolean},reducedMotion=false,reducedFlash=false){const pressure=clamp01(clamp01(input.charge)*.45+clamp01(input.hazardPressure)*.32+clamp01(input.secondaryPeak)*.23),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1,bossInteriorScale=Math.max(input.critical?.48:.44,1-pressure*.48)*motion*flash;return{pressure,bossEdgeScale:1,bossInteriorScale,secondaryScale:Math.max(.38,bossInteriorScale*(.78+.08*(1-pressure)))*motion*flash,canonicalScale:1,presentationOnly:true as const};}

export function canonicalBodyTemporalProtectionPresentation(input:{crowd:number;secondaryPeak:number;critical:boolean;bossActive:boolean},reducedMotion=false,reducedFlash=false){const pressure=clamp01(clamp01(input.crowd)*.48+clamp01(input.secondaryPeak)*.34+(input.critical?.1:0)+(input.bossActive?.08:0)),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{pressure,bodyScale:1,canonicalScale:1,trailScale:Math.max(input.critical?.46:.42,1-pressure*.52)*motion*flash,presentationOnly:true as const};}

export function secondaryRhythmTemporalRetirementPresentation(input:{life:number;churn:number;pressure:number;critical:boolean},reducedMotion=false,reducedFlash=false){const life=clamp01(input.life),churn=clamp01(input.churn),pressure=clamp01(input.pressure),retention=clamp01(life*(1-churn*.5)*(1-pressure*.35)),floor=input.critical?.4:.34,motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{retention,canonicalScale:1,secondaryScale:Math.max(floor,floor+(.96-floor)*retention)*motion*flash,presentationOnly:true as const};}

export function unifiedTemporalArbitrationPresentation(input:{criticalCount:number;safeLaneVisible:boolean;laneConfidence:number;bossActive:boolean;bossCharge:number;projectilePressure:number;impactPressure:number;hazardPressure:number;secondaryFamilies:number;heroProximity:number},reducedMotion=false,reducedFlash=false){const critical=clamp01(Math.max(0,input.criticalCount)/3),families=clamp01(Math.max(0,input.secondaryFamilies)/6),load=clamp01(critical*.2+clamp01(input.projectilePressure)*.14+clamp01(input.impactPressure)*.14+clamp01(input.hazardPressure)*.14+families*.18+clamp01(input.heroProximity)*.1+(input.safeLaneVisible?.05:0)+(input.bossActive?.05:0)),motion=reducedMotion?.98:1,flash=reducedFlash?.97:1;return{load,criticalScale:1,safeLaneScale:(input.safeLaneVisible?1+clamp01(input.laneConfidence)*.05:1)*flash,bossEdgeScale:(input.bossActive?Math.max(.86,1-clamp01(input.bossCharge)*load*.1):1)*flash,canonicalScale:1,secondaryScale:Math.max(.42,1-load*.52)*motion*flash,presentationOnly:true as const};}
