export const SAFE_ZONE_TRANSITION_DIRECTION_IDS=['N','NE','E','SE','S','SW','W','NW'] as const;
export type SafeZoneTransitionDirectionId=typeof SAFE_ZONE_TRANSITION_DIRECTION_IDS[number];
const CELL:Readonly<Record<SafeZoneTransitionDirectionId,readonly[number,number]>>={N:[0,0],NE:[1,0],E:[2,0],SE:[3,0],S:[0,1],SW:[1,1],W:[2,1],NW:[3,1]};
const ACCENT:Readonly<Record<SafeZoneTransitionDirectionId,string>>={N:'#a8f8ff',NE:'#89eeff',E:'#71e0ff',SE:'#7fd9ff',S:'#9ed4ff',SW:'#b7d0ff',W:'#c6d8ff',NW:'#b6eaff'};
export interface SafeZoneTransitionDirectionIcon{direction:SafeZoneTransitionDirectionId;accent:string;sx:number;sy:number;sw:96;sh:96;forecastUrgencyThreshold:.65;autoMove:false;animated:false;motionAmplitude:0;textFallbackPreserved:true;loadFailureBlocksGameplay:false;}
export const SAFE_ZONE_TRANSITION_DIRECTION_ATLAS={src:'./assets/bosses/safe-zone-transition-direction-icons.png',columns:4,rows:2,cellSize:96,width:384,height:192} as const;
export function safeZoneTransitionDirectionFromVector(dx:number,dy:number):SafeZoneTransitionDirectionId{const x=Number.isFinite(dx)?dx:0,y=Number.isFinite(dy)?dy:0;if(Math.abs(x)<1e-9&&Math.abs(y)<1e-9)return'N';const oct=Math.round(Math.atan2(y,x)/(Math.PI/4));const normalized=(oct+8)%8;return(['E','SE','S','SW','W','NW','N','NE'] as const)[normalized]!;}
export function safeZoneTransitionDirectionIcon(direction:SafeZoneTransitionDirectionId):SafeZoneTransitionDirectionIcon{const[c,r]=CELL[direction];return{direction,accent:ACCENT[direction],sx:c*96,sy:r*96,sw:96,sh:96,forecastUrgencyThreshold:.65,autoMove:false,animated:false,motionAmplitude:0,textFallbackPreserved:true,loadFailureBlocksGameplay:false};}
export function auditSafeZoneTransitionDirectionAtlas(){const icons=SAFE_ZONE_TRANSITION_DIRECTION_IDS.map(safeZoneTransitionDirectionIcon);const outOfBounds=icons.filter(i=>i.sx<0||i.sy<0||i.sx+i.sw>SAFE_ZONE_TRANSITION_DIRECTION_ATLAS.width||i.sy+i.sh>SAFE_ZONE_TRANSITION_DIRECTION_ATLAS.height).map(i=>i.direction);const uniqueCellCount=new Set(icons.map(i=>`${i.sx}:${i.sy}`)).size;const coverage=icons.length/8;return{coverage,uniqueCellCount,outOfBounds,passed:coverage===1&&uniqueCellCount===8&&outOfBounds.length===0};}
