import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/specialist-attack-silhouette-emphasis-rendering.js');}
const input=(over={})=>({type:'assassin',pullback:.7,lunge:0,resolve:0,hit:0,rangedAim:false,facingX:1,facingY:0,...over});
test('phase 3513 specialist windup keeps a compact readable pre-strike silhouette',async()=>{const m=await load();const p=m.specialistAttackSilhouetteEmphasisPresentation(input(),false);assert.equal(p.phase,'windup');assert.ok(p.alphaScale<1);assert.ok(p.trailDistanceScale<1);});
test('phase 3514 assassin strike elongates silhouette along its committed attack direction',async()=>{const m=await load();const p=m.specialistAttackSilhouetteEmphasisPresentation(input({pullback:0,lunge:.9}),false);assert.equal(p.phase,'strike');assert.ok(p.widthScale>1);assert.ok(p.heightScale<1);});
test('phase 3515 shieldbearer windup stays taller and more planted than assassin windup',async()=>{const m=await load();const a=m.specialistAttackSilhouetteEmphasisPresentation(input(),false),b=m.specialistAttackSilhouetteEmphasisPresentation(input({type:'shieldbearer'}),false);assert.ok(b.heightScale>a.heightScale);assert.ok(Math.abs(b.lateralOffset)<=Math.abs(a.lateralOffset));});
test('phase 3516 resolve trail fades instead of competing with the next locomotion frame',async()=>{const m=await load();const p=m.specialistAttackSilhouetteEmphasisPresentation(input({pullback:0,resolve:.8}),false);assert.equal(p.phase,'resolve');assert.ok(p.alphaScale<=.65);});
test('phase 3517 strong hit ownership suppresses attack silhouette exaggeration',async()=>{const m=await load();const clean=m.specialistAttackSilhouetteEmphasisPresentation(input({pullback:0,lunge:.9}),false),hit=m.specialistAttackSilhouetteEmphasisPresentation(input({pullback:0,lunge:.9,hit:.9}),false);assert.ok(hit.alphaScale<clean.alphaScale);assert.ok(Math.abs(hit.widthScale-1)<Math.abs(clean.widthScale-1));});
test('phase 3518 live specialist silhouette consumes phase-specific shape and offset without gameplay mutation',async()=>{const s=source();assert.match(s,/specialistAttackSilhouetteEmphasisPresentation/);assert.match(s,/specialistSilhouetteEmphasis\.widthScale/);assert.match(s,/specialistSilhouetteEmphasis\.lateralOffset/);const a=await import('../dist/game/specialist-attack-silhouette-emphasis-audit.js');const r=a.runSpecialistAttackSilhouetteEmphasisAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
