import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/specialist-locomotion-signature-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/specialist-locomotion-signature-rendering.js');}

test('phase 2937 specialist locomotion signature module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceSpecialistLocomotionSignatureState,'function');assert.equal(typeof mod.specialistLocomotionSignaturePresentation,'function');});
test('phase 2938 assassin blink creates short arrival compression and directional catch-up',async()=>{const mod=await loadModule();const s=mod.advanceSpecialistLocomotionSignatureState(undefined,'assassin','blink',0.016);const p=mod.specialistLocomotionSignaturePresentation('assassin',s,0.8,0.2,1,0,false);assert.ok(p.arrival>0.8);assert.ok(p.offsetX<0);assert.ok(p.scaleX<1);assert.ok(p.scaleY>1);});
test('phase 2939 shieldbearer brace widens stance with bounded displacement',async()=>{const mod=await loadModule();const s=mod.advanceSpecialistLocomotionSignatureState(undefined,'shieldbearer','brace',0.016);const p=mod.specialistLocomotionSignaturePresentation('shieldbearer',s,0.2,0.7,1,0,false);assert.ok(p.brace>0.8);assert.ok(p.scaleX>p.scaleY);assert.ok(Math.abs(p.offsetX)<=3);assert.ok(p.groundPulseAlpha<=0.2);});
test('phase 2940 siege golem plant adds heavy settle and ground pulse only during plant',async()=>{const mod=await loadModule();const s=mod.advanceSpecialistLocomotionSignatureState(undefined,'siegeGolem','plant',0.016);const p=mod.specialistLocomotionSignaturePresentation('siegeGolem',s,0.1,0.9,0,1,false);const idle=mod.specialistLocomotionSignaturePresentation('siegeGolem',{arrival:0,brace:0,plant:0},0.1,0.9,0,1,false);assert.ok(p.plant>0.8);assert.ok(p.offsetY>1);assert.ok(p.groundPulseAlpha>0.08);assert.ok(p.groundPulseRadius>=38);assert.equal(idle.groundPulseAlpha,0);});
test('phase 2941 reduced motion compresses specialist displacement but preserves signature state',async()=>{const mod=await loadModule();const s=mod.advanceSpecialistLocomotionSignatureState(undefined,'assassin','blink',0.016);const full=mod.specialistLocomotionSignaturePresentation('assassin',s,0.8,0.2,1,0,false);const reduced=mod.specialistLocomotionSignaturePresentation('assassin',s,0.8,0.2,1,0,true);assert.equal(reduced.kind,full.kind);assert.equal(reduced.arrival,full.arrival);assert.ok(Math.abs(reduced.offsetX)<Math.abs(full.offsetX));});
test('phase 2942 enemy lifecycle triggers signatures on real specialist events and audit stays presentation-only',async()=>{assert.match(enemySource,/specialistLocomotionSignature/);assert.match(enemySource,/advanceSpecialistLocomotionSignatureState/);assert.match(enemySource,/specialistLocomotionSignaturePresentation/);assert.match(enemySource,/'blink'/);assert.match(enemySource,/'brace'/);assert.match(enemySource,/'plant'/);assert.equal(fs.existsSync(new URL('../src/game/specialist-locomotion-signature-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-locomotion-signature-audit.js');const audit=mod.runSpecialistLocomotionSignatureAudit();assert.equal(audit.samples.length,60);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
