import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/boss-special-cue-budget-rendering.js');}
const input=(over={})=>({phase:2,charge:.8,recovery:0,stagger:0,phaseOverlay:true,...over});
test('phase 3555 active boss special promotes primary ring and reduces ordinary boss outline competition',async()=>{const m=await load();const p=m.bossSpecialCueBudgetPresentation(input(),false,false);assert.ok(p.primaryRingScale>.8);assert.ok(p.baseOutlineScale<.75);});
test('phase 3556 phase three keeps phase identity but never lets overlay and special ring both peak fully',async()=>{const m=await load();const p=m.bossSpecialCueBudgetPresentation(input({phase:3,charge:.95}),false,false);assert.ok(p.phaseOverlayScale<1);assert.ok(p.primaryRingScale<=1);assert.ok(p.phaseOverlayScale+p.primaryRingScale<1.75);});
test('phase 3557 boss recovery retires special rings before restoring ordinary outline',async()=>{const m=await load();const p=m.bossSpecialCueBudgetPresentation(input({charge:.08,recovery:.8}),false,false);assert.ok(p.primaryRingScale<.45);assert.ok(p.baseOutlineScale>.55);});
test('phase 3558 stagger owns body readability and suppresses secondary warning ring first',async()=>{const m=await load();const p=m.bossSpecialCueBudgetPresentation(input({stagger:.9}),false,false);assert.ok(p.secondaryRingScale<.2);assert.ok(p.primaryRingScale<.5);});
test('phase 3559 reduced flash lowers alpha budget without changing cue ownership ratios',async()=>{const m=await load();const a=m.bossSpecialCueBudgetPresentation(input(),false,false),b=m.bossSpecialCueBudgetPresentation(input(),false,true);assert.equal(a.primaryRingScale,b.primaryRingScale);assert.equal(a.baseOutlineScale,b.baseOutlineScale);assert.ok(b.alphaScale<a.alphaScale);});
test('phase 3560 live boss outline special rings and phase overlay consume one cue budget',async()=>{const s=source();assert.match(s,/bossSpecialCueBudgetPresentation/);assert.match(s,/bossSpecialCueBudget\.baseOutlineScale/);assert.match(s,/bossSpecialCueBudget\.phaseOverlayScale/);const a=await import('../dist/game/boss-special-cue-budget-audit.js');const r=a.runBossSpecialCueBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
