import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-depth-plane-reentry-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4125 projectile reentry restores depth only as overlap clears',async()=>{const {projectileDepthReentryPresentation}=await load();const blocked=projectileDepthReentryPresentation({release:.2,pressure:1,critical:false},false),clear=projectileDepthReentryPresentation({release:1,pressure:.1,critical:false},false);assert.equal(clear.bodyScale,1);assert.ok(clear.trailScale>blocked.trailScale);});
test('Phase 4126 impact reentry restores edge before fill',async()=>{const {impactDepthReentryPresentation}=await load();const p=impactDepthReentryPresentation({release:.7,pressure:.5,critical:false},false);assert.ok(p.edgeScale>=p.fillScale);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);});
test('Phase 4127 hazard reentry avoids fill rebound while edge stays authoritative',async()=>{const {hazardDepthReentryPresentation}=await load();const p=hazardDepthReentryPresentation({release:.65,pressure:.6,telegraph:true},false);assert.ok(p.edgeAlphaScale>=.92);assert.ok(p.fillScale<=p.edgeScale);});
test('Phase 4128 safe lane contour releases toward neutral without undershoot',async()=>{const {safeLaneContourReentryPresentation}=await load();const p=safeLaneContourReentryPresentation({release:1,pressure:0,visible:true},false);assert.equal(p.contourAlphaScale,1);assert.equal(p.contourWidthScale,1);});
test('Phase 4129 specialist rim reentry keeps body canonical',async()=>{const {specialistRimReentryPresentation}=await load();const p=specialistRimReentryPresentation({release:.8,pressure:.3,owner:'recovery'},false);assert.equal(p.bodyScale,1);assert.ok(p.rimAlphaScale>=.68);});
test('Phase 4130 reentry budget prevents all secondary layers peaking together',async()=>{const {depthReentryBudgetPresentation}=await load();const p=depthReentryBudgetPresentation({reenteringCount:9,pressure:.8,criticalCount:1},false,false);assert.equal(p.canonicalScale,1);assert.ok(p.secondaryReentryScale<1);});
test('Phase 4125-4130 live renderers consume depth reentry helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileDepthReentryPresentation/);assert.match(e,/specialistRimReentryPresentation/);assert.match(s,/impactDepthReentryPresentation/);assert.match(g,/hazardDepthReentryPresentation/);assert.match(g,/safeLaneContourReentryPresentation/);});
