import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-dense-arbitration-rendering.js',import.meta.url);async function load(){return import(moduleUrl.href);}
test('Phase 4113 dense projectile arbitration keeps body canonical',async()=>{const {denseProjectileArbitrationPresentation}=await load();const p=denseProjectileArbitrationPresentation({projectileCount:18,indexFromNewest:12,critical:false,laneProximity:.8},false,false);assert.equal(p.bodyAlphaScale,1);assert.ok(p.trailAlphaScale<1);});
test('Phase 4114 dense impact arbitration retires fill before edge',async()=>{const {denseImpactArbitrationPresentation}=await load();const p=denseImpactArbitrationPresentation({impactCount:14,indexFromNewest:9,heroProximity:.8,critical:false},false);assert.equal(p.canonicalAlphaScale,1);assert.ok(p.fillAlphaScale<p.edgeAlphaScale);});
test('Phase 4115 dense hazard arbitration preserves telegraph boundary',async()=>{const {denseHazardArbitrationPresentation}=await load();const p=denseHazardArbitrationPresentation({hazardCount:9,indexFromNewest:6,telegraph:true,critical:true,laneProximity:.8},false);assert.ok(p.edgeAlphaScale>=.92);assert.ok(p.fillAlphaScale<=1);});
test('Phase 4116 dense safe lane arbitration keeps path floor',async()=>{const {denseSafeLaneArbitrationPresentation}=await load();const p=denseSafeLaneArbitrationPresentation({hazardCount:8,projectileCount:18,confidence:.9,critical:true},false);assert.ok(p.pathAlphaFloor>=.94);assert.ok(p.safeLaneAlphaScale>=1);});
test('Phase 4117 dense specialist arbitration keeps directional body readable',async()=>{const {denseSilhouetteArbitrationPresentation}=await load();const p=denseSilhouetteArbitrationPresentation({silhouetteCount:8,indexFromNewest:6,owner:'attack',critical:false},false);assert.equal(p.bodyAlphaScale,1);assert.ok(p.directionAlphaScale>=.66);assert.ok(p.secondaryAlphaScale<1);});
test('Phase 4118 unified dense battlefield arbitration protects critical lane and canonical body',async()=>{const {denseBattlefieldArbitrationPresentation}=await load();const p=denseBattlefieldArbitrationPresentation({criticalCount:2,hazardCount:9,projectileCount:18,impactCount:14,silhouetteCount:8,safeLaneVisible:true},false,false);assert.equal(p.criticalAlphaScale,1);assert.equal(p.canonicalBodyAlphaScale,1);assert.ok(p.safeLaneAlphaScale>=1);assert.ok(p.secondaryAlphaScale<1);});
test('Phase 4113-4118 live renderers consume dense arbitration helpers',async()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/denseProjectileArbitrationPresentation/);assert.match(e,/denseSilhouetteArbitrationPresentation/);assert.match(s,/denseImpactArbitrationPresentation/);assert.match(g,/denseHazardArbitrationPresentation/);assert.match(g,/denseSafeLaneArbitrationPresentation/);});
