import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/boss-special-body-language-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-special-body-language-rendering.js');}

test('phase 2943 boss special body language module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.bossSpecialBodyLanguagePresentation,'function');});
test('phase 2944 inferno pre-special expands forward while juggernaut compresses into charge stance',async()=>{const mod=await loadModule();const fire=mod.bossSpecialBodyLanguagePresentation('inferno',2,0.25,1,0,false);const jug=mod.bossSpecialBodyLanguagePresentation('juggernaut',2,0.25,1,0,false);assert.ok(fire.charge>0.7);assert.ok(fire.scaleX>1);assert.ok(jug.scaleY<1);assert.ok(jug.offsetX<0);});
test('phase 2945 summoner and abyss witch visibly lift before special without large lateral drift',async()=>{const mod=await loadModule();for(const kind of ['summoner','abyssWitch']){const p=mod.bossSpecialBodyLanguagePresentation(kind,3,0.2,0,1,false);assert.ok(p.offsetY<0);assert.ok(Math.abs(p.offsetX)<3);assert.ok(p.auraAlpha>0.15);}});
test('phase 2946 twin maw yaws while time eater tightens with distinct stance identities',async()=>{const mod=await loadModule();const twin=mod.bossSpecialBodyLanguagePresentation('twinMaw',2,0.15,1,0,false);const time=mod.bossSpecialBodyLanguagePresentation('timeEater',2,0.15,1,0,false);assert.ok(Math.abs(twin.rotation)>Math.abs(time.rotation));assert.notEqual(twin.stance,time.stance);assert.ok(time.scaleX<1.01);});
test('phase 2947 reduced motion preserves charge/stance but compresses body transform',async()=>{const mod=await loadModule();const full=mod.bossSpecialBodyLanguagePresentation('juggernaut',3,0.12,1,0,false);const reduced=mod.bossSpecialBodyLanguagePresentation('juggernaut',3,0.12,1,0,true);assert.equal(reduced.stance,full.stance);assert.equal(reduced.charge,full.charge);assert.ok(Math.abs(reduced.offsetX)<Math.abs(full.offsetX));assert.ok(Math.abs(reduced.rotation)<=Math.abs(full.rotation));});
test('phase 2948 boss render consumes archetype body language before sprite draw and audit stays presentation-only',async()=>{assert.match(enemySource,/bossSpecialBodyLanguagePresentation/);assert.match(enemySource,/bossSpecialBodyLanguage/);assert.match(enemySource,/specialTimer/);assert.equal(fs.existsSync(new URL('../src/game/boss-special-body-language-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-special-body-language-audit.js');const audit=mod.runBossSpecialBodyLanguageAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
