import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-effective-alpha-floor-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4155 compounded projectile alpha keeps a readable canonical body floor',async()=>{const {projectileEffectiveAlphaFloorPresentation}=await load();const p=projectileEffectiveAlphaFloorPresentation({critical:false,bossVisual:false,laneProximity:.8,reacquire:.15,crowd:1},false);assert.ok(p.bodyAlphaFloor>=.38);assert.ok(p.bodyAlphaFloor<=1);});
test('Phase 4156 impact edge floor survives compounded secondary suppression',async()=>{const {impactEffectiveAlphaFloorPresentation}=await load();const p=impactEffectiveAlphaFloorPresentation({critical:true,bossProximity:1,reacquire:.2,crowd:1},false);assert.ok(p.edgeAlphaFloor>=.45);assert.ok(p.directionAlphaFloor<=p.edgeAlphaFloor);});
test('Phase 4157 active hazard boundary keeps an effective alpha floor',async()=>{const {hazardEffectiveAlphaFloorPresentation}=await load();const p=hazardEffectiveAlphaFloorPresentation({telegraph:true,critical:true,laneProximity:.8,reacquire:.2},false);assert.ok(p.edgeAlphaFloor>=.5);assert.ok(p.edgeAlphaFloor<=1);});
test('Phase 4158 safe lane effective path remains readable under boss pressure',async()=>{const {safeLaneEffectiveAlphaFloorPresentation}=await load();const p=safeLaneEffectiveAlphaFloorPresentation({visible:true,confidence:.9,bossPressure:1,critical:true,reacquire:.2},false);assert.ok(p.pathAlphaFloor>=.72);assert.ok(p.pathAlphaFloor<=1);});
test('Phase 4159 specialist silhouette cannot collapse under stacked presentation multipliers',async()=>{const {specialistEffectiveAlphaFloorPresentation}=await load();const p=specialistEffectiveAlphaFloorPresentation({owner:'special',bossProximity:1,reacquire:.2,critical:true},false);assert.ok(p.silhouetteAlphaFloor>=.52);assert.ok(p.directionAlphaFloor>=.48);});
test('Phase 4160 effective floor budget never lifts decoration with the canonical floor',async()=>{const {effectiveAlphaFloorBudgetPresentation}=await load();const p=effectiveAlphaFloorBudgetPresentation({criticalCount:2,crowd:1,safeLaneVisible:true,bossActive:true},false);assert.equal(p.decorationLift,0);assert.ok(p.canonicalFloorScale>=1);assert.ok(p.safeLaneFloorScale>=1);});
test('Phase 4155-4160 live renderers apply final effective alpha floors',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileEffectiveAlphaFloorPresentation/);assert.match(e,/specialistEffectiveAlphaFloorPresentation/);assert.match(s,/impactEffectiveAlphaFloorPresentation/);assert.match(g,/hazardEffectiveAlphaFloorPresentation/);assert.match(g,/safeLaneEffectiveAlphaFloorPresentation/);assert.match(e,/Math\.max\(projectileEffectiveFloor\.bodyAlphaFloor/);});
