import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-direction-reacquisition-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4143 projectile direction reacquires before stale direction tail',async()=>{const {projectileDirectionReacquisitionPresentation}=await load();const p=projectileDirectionReacquisitionPresentation({reacquire:.2,pressure:1,critical:false},false);assert.ok(p.primaryDirectionScale>=.74);assert.ok(p.staleDirectionScale<p.primaryDirectionScale);});
test('Phase 4144 impact response direction remains legible during reacquisition',async()=>{const {impactDirectionReacquisitionPresentation}=await load();const p=impactDirectionReacquisitionPresentation({reacquire:.2,responseStrength:.9,pressure:1,critical:true},false);assert.ok(p.directionAlphaScale>=.82);assert.ok(p.responseScale>=p.staleDirectionScale);});
test('Phase 4145 hazard boundary direction outranks stale interior direction',async()=>{const {hazardBoundaryDirectionReacquisitionPresentation}=await load();const p=hazardBoundaryDirectionReacquisitionPresentation({reacquire:.2,telegraph:true,laneProximity:.8,pressure:1},false);assert.ok(p.edgeDirectionScale>=.9);assert.ok(p.staleFillDirectionScale<1);});
test('Phase 4146 safe lane direction keeps a readable path floor',async()=>{const {safeLaneDirectionReacquisitionPresentation}=await load();const p=safeLaneDirectionReacquisitionPresentation({visible:true,confidence:.9,reacquire:.2,pressure:1},false);assert.ok(p.pathAlphaFloor>=.93);assert.ok(p.pathDirectionScale>=1);});
test('Phase 4147 specialist facing reacquires before recovery trail direction',async()=>{const {specialistFacingReacquisitionPresentation}=await load();const p=specialistFacingReacquisitionPresentation({owner:'attack',reacquire:.2,pressure:1,critical:false},false);assert.ok(p.facingScale>=.82);assert.ok(p.trailDirectionScale<p.facingScale);});
test('Phase 4148 direction reacquisition budget preserves the primary direction owner',async()=>{const {directionReacquisitionBudgetPresentation}=await load();const p=directionReacquisitionBudgetPresentation({criticalCount:2,projectileCount:12,impactCount:8,hazardCount:5,silhouetteCount:4,safeLaneVisible:true},false,false);assert.equal(p.primaryDirectionScale,1);assert.equal(p.canonicalScale,1);assert.ok(p.staleDirectionScale<1);});
test('Phase 4143-4148 live renderers consume direction reacquisition helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileDirectionReacquisitionPresentation/);assert.match(e,/specialistFacingReacquisitionPresentation/);assert.match(s,/impactDirectionReacquisitionPresentation/);assert.match(g,/hazardBoundaryDirectionReacquisitionPresentation/);assert.match(g,/safeLaneDirectionReacquisitionPresentation/);});
