import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/specialist-defeat-ground-retirement-rendering.ts',import.meta.url);
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/specialist-defeat-ground-retirement-rendering.js');}

test('phase 3027 specialist defeat ground retirement module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.specialistDefeatGroundRetirementPresentation,'function');});
test('phase 3028 a fresh specialist fatal pose keeps a grounded shadow under the existing body sprite',async()=>{const {specialistDefeatGroundRetirementPresentation}=await loadModule();const p=specialistDefeatGroundRetirementPresentation('shieldbearer',0,{offsetX:2,offsetY:1,alpha:1,radius:22},false);assert.equal(p.owner,'body');assert.ok(p.shadowAlpha>.2);assert.ok(p.widthScale>=1);assert.ok(Math.abs(p.shadowOffsetX)<2);});
test('phase 3029 assassin fatal motion follows only a bounded fraction of the body displacement',async()=>{const {specialistDefeatGroundRetirementPresentation}=await loadModule();const p=specialistDefeatGroundRetirementPresentation('assassin',.38,{offsetX:12,offsetY:-4,alpha:.72,radius:16},false);assert.ok(Math.abs(p.shadowOffsetX)<=3.2);assert.ok(Math.abs(p.shadowOffsetY)<=1.8);assert.ok(p.shadowAlpha>0);});
test('phase 3030 siege golem retirement reads heavier than assassin without leaving a pulse behind',async()=>{const {specialistDefeatGroundRetirementPresentation}=await loadModule();const a=specialistDefeatGroundRetirementPresentation('assassin',.25,{offsetX:4,offsetY:2,alpha:.8,radius:16},false);const g=specialistDefeatGroundRetirementPresentation('siegeGolem',.25,{offsetX:4,offsetY:2,alpha:.8,radius:28},false);assert.ok(g.widthScale>a.widthScale);assert.equal(g.groundPulseScale,0);assert.equal(a.groundPulseScale,0);});
test('phase 3031 shadow retirement finishes before the body queue expires and reduced motion stays bounded',async()=>{const {specialistDefeatGroundRetirementPresentation}=await loadModule();const late=specialistDefeatGroundRetirementPresentation('nullifier',.92,{offsetX:5,offsetY:3,alpha:.28,radius:18},false);const reduced=specialistDefeatGroundRetirementPresentation('nullifier',.45,{offsetX:10,offsetY:5,alpha:.65,radius:18},true);assert.equal(late.owner,'retire');assert.equal(late.shadowAlpha,0);assert.equal(late.groundPulseScale,0);assert.ok(Math.abs(reduced.shadowOffsetX)<=2);});
test('phase 3032 defeated specialist rendering draws retirement shadow before body and audit stays presentation-only',async()=>{assert.match(gameSource,/specialistDefeatGroundRetirementPresentation/);assert.match(gameSource,/retirement\.shadowAlpha/);assert.match(gameSource,/retirement\.shadowOffsetX/);assert.match(gameSource,/retirement\.groundPulseScale/);assert.equal(fs.existsSync(new URL('../src/game/specialist-defeat-ground-retirement-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-defeat-ground-retirement-audit.js');const audit=mod.runSpecialistDefeatGroundRetirementAudit();assert.equal(audit.samples.length,48);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
