import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-projectile-guard-impact-handoff-rendering.ts',import.meta.url);const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-projectile-guard-impact-handoff-rendering.js');}
test('phase 3147 core projectile guard impact handoff module exists',async()=>{const m=await load();assert.equal(typeof m.coreProjectileGuardImpactHandoffPresentation,'function');});
test('phase 3148 strongly mitigated core projectile hands ownership to core guard',async()=>{const {coreProjectileGuardImpactHandoffPresentation}=await load();const p=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.74,impactTtl:.32,impactMaxTtl:.36},false);assert.equal(p.owner,'core-guard');assert.equal(p.threatAlphaScale,0);assert.ok(p.coreGuardImpactAlpha>.45);assert.ok(p.ordinaryImpactAlphaScale<1);});
test('phase 3149 lightly mitigated core projectile remains ordinary impact',async()=>{const {coreProjectileGuardImpactHandoffPresentation}=await load();const p=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.07,impactTtl:.3,impactMaxTtl:.36},false);assert.equal(p.owner,'impact');assert.equal(p.coreGuardImpactAlpha,0);assert.equal(p.ordinaryImpactAlphaScale,1);});
test('phase 3150 core guard arc and deflect distance are bounded and fade',async()=>{const {coreProjectileGuardImpactHandoffPresentation}=await load();const a=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.82,impactTtl:.34,impactMaxTtl:.36},false),b=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.82,impactTtl:.06,impactMaxTtl:.36},false);assert.ok(a.arcRadius>=16&&a.arcRadius<=34);assert.ok(a.deflectDistance<=20);assert.ok(a.coreGuardImpactAlpha>b.coreGuardImpactAlpha);});
test('phase 3151 reduced flash compresses core guard impact without reviving threat',async()=>{const {coreProjectileGuardImpactHandoffPresentation}=await load();const f=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.7,impactTtl:.28,impactMaxTtl:.36},false),r=coreProjectileGuardImpactHandoffPresentation({preventedRatio:.7,impactTtl:.28,impactMaxTtl:.36},true);assert.equal(r.threatAlphaScale,0);assert.ok(r.coreGuardImpactAlpha<f.coreGuardImpactAlpha);assert.equal(r.owner,'core-guard');});
test('phase 3152 live core projectile damage returns applied amount and queues presentation-only core guard handoff',async()=>{const e=enemySource(),g=gameSource();assert.match(e,/onCoreDamage: \(amount: number, source\?: DamageReasonSource\) => number \| void/);assert.match(e,/coreProjectileGuardImpactHandoffPresentation/);assert.match(e,/ctx\.onCoreDamage\(p\.damage, 'projectile'\)/);assert.match(e,/projectileCoreGuardImpactVfx/);assert.match(g,/onCoreDamage: \(amount, source = 'contact'\)/);assert.match(g,/return applied/);const a=await import('../dist/game/core-projectile-guard-impact-handoff-audit.js');const audit=a.runCoreProjectileGuardImpactHandoffAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
