import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/ranged-enemy-projectile-launch-origin-rendering.ts',import.meta.url);const src=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/ranged-enemy-projectile-launch-origin-rendering.js');}
test('phase 3081 ranged enemy projectile launch module exists',async()=>{const m=await load();assert.equal(typeof m.rangedEnemyProjectileLaunchOriginPresentation,'function');});
test('phase 3082 archer release origin follows attack pullback lunge and facing',async()=>{const {rangedEnemyProjectileLaunchOriginPresentation}=await load();const p=rangedEnemyProjectileLaunchOriginPresentation({type:'archer',radius:18,facingX:1,facingY:0,pullback:.5,lunge:.35,resolve:0},false);assert.equal(p.owner,'attack-pose');assert.ok(p.originOffsetX>8);assert.ok(Math.abs(p.originOffsetY)<=8);assert.ok(p.convergeSeconds>0);});
test('phase 3083 attack resolve keeps projectile visually attached during first release frames',async()=>{const {rangedEnemyProjectileLaunchOriginPresentation}=await load();const release=rangedEnemyProjectileLaunchOriginPresentation({type:'archer',radius:18,facingX:.8,facingY:.6,pullback:0,lunge:.35,resolve:1},false);assert.ok(Math.hypot(release.originOffsetX,release.originOffsetY)>=12);assert.ok(release.resolveFollow>0);});
test('phase 3084 ranged launch offsets remain bounded for unusual facing inputs',async()=>{const {rangedEnemyProjectileLaunchOriginPresentation}=await load();const p=rangedEnemyProjectileLaunchOriginPresentation({type:'archer',radius:40,facingX:99,facingY:-120,pullback:1,lunge:1,resolve:1},false);assert.ok(Math.hypot(p.originOffsetX,p.originOffsetY)<=36);});
test('phase 3085 reduced motion compresses launch displacement but keeps attack owner',async()=>{const {rangedEnemyProjectileLaunchOriginPresentation}=await load();const f=rangedEnemyProjectileLaunchOriginPresentation({type:'archer',radius:18,facingX:1,facingY:0,pullback:.5,lunge:.35,resolve:1},false);const r=rangedEnemyProjectileLaunchOriginPresentation({type:'archer',radius:18,facingX:1,facingY:0,pullback:.5,lunge:.35,resolve:1},true);assert.equal(r.owner,'attack-pose');assert.ok(Math.abs(r.originOffsetX)<Math.abs(f.originOffsetX));assert.ok(r.convergeSeconds<f.convergeSeconds);});
test('phase 3086 live archer fire path captures attack pose but gameplay projectile velocity stays unchanged and audit is presentation only',async()=>{assert.match(src,/rangedEnemyProjectileLaunchOriginPresentation/);assert.match(src,/fireEnemyProjectile\(enemy, targetObj\.pos, ctx\.reducedMotion\?\?false\)/);assert.match(src,/visualLaunchOffset/);assert.match(src,/visualLaunchTtl/);assert.match(src,/dir\.x \* 260 \* this\.endlessProjectileSpeedMultiplier/);const a=await import('../dist/game/ranged-enemy-projectile-launch-origin-audit.js');const audit=a.runRangedEnemyProjectileLaunchOriginAudit();assert.equal(audit.samples.length,48);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
