import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/specialist-attack-hit-arbitration-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/specialist-attack-hit-arbitration-rendering.js');}

test('phase 2991 specialist attack hit arbitration module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.specialistAttackHitArbitrationPresentation,'function');});
test('phase 2992 committed specialist windup suppresses competing nonfatal hit stagger',async()=>{const mod=await loadModule();const p=mod.specialistAttackHitArbitrationPresentation('shieldbearer',{pullback:.9,lunge:0,resolve:0,hitStagger:.9,tier:'heavy',fatal:false},false);assert.equal(p.owner,'attack');assert.ok(p.attackScale>.9);assert.ok(p.hitStaggerScale<.5);assert.ok(p.attackCommitment>.65);});
test('phase 2993 critical hit remains readable without stealing a committed siege attack',async()=>{const mod=await loadModule();const heavy=mod.specialistAttackHitArbitrationPresentation('siegeGolem',{pullback:.86,lunge:.08,resolve:0,hitStagger:.9,tier:'heavy',fatal:false},false);const critical=mod.specialistAttackHitArbitrationPresentation('siegeGolem',{pullback:.86,lunge:.08,resolve:0,hitStagger:1,tier:'critical',fatal:false},false);assert.equal(critical.owner,'attack');assert.ok(critical.hitStaggerScale>=heavy.hitStaggerScale);assert.ok(critical.hitStaggerScale<=.6);assert.ok(critical.attackScale>.9);});
test('phase 2994 hit stagger regains ownership once attack commitment has cleared',async()=>{const mod=await loadModule();const p=mod.specialistAttackHitArbitrationPresentation('assassin',{pullback:0,lunge:0,resolve:.08,hitStagger:.95,tier:'critical',fatal:false},false);assert.equal(p.owner,'hit');assert.ok(p.hitStaggerScale>.9);assert.ok(p.attackScale<=1);});
test('phase 2995 fatal transition always outranks attack and hit while reduced motion keeps priority identity',async()=>{const mod=await loadModule();const full=mod.specialistAttackHitArbitrationPresentation('nullifier',{pullback:.8,lunge:.2,resolve:.3,hitStagger:1,tier:'critical',fatal:true},false);const reduced=mod.specialistAttackHitArbitrationPresentation('nullifier',{pullback:.8,lunge:.2,resolve:.3,hitStagger:1,tier:'critical',fatal:true},true);assert.equal(full.owner,'fatal');assert.equal(reduced.owner,'fatal');assert.equal(full.attackScale,0);assert.equal(full.attackResolveScale,0);assert.equal(full.hitStaggerScale,0);assert.equal(full.fatalTransitionScale,1);});
test('phase 2996 specialist render composes arbitration and audit stays presentation-only',async()=>{assert.match(enemySource,/specialistAttackHitArbitrationPresentation/);assert.match(enemySource,/attackScale/);assert.match(enemySource,/hitStaggerScale/);assert.match(enemySource,/attackResolveScale/);assert.equal(fs.existsSync(new URL('../src/game/specialist-attack-hit-arbitration-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-attack-hit-arbitration-audit.js');const audit=mod.runSpecialistAttackHitArbitrationAudit();assert.equal(audit.samples.length,96);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
