import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/regular-defeat-ground-retirement-rendering.ts',import.meta.url);
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/regular-defeat-ground-retirement-rendering.js');}

test('phase 3045 regular and elite defeat ground retirement module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.regularDefeatGroundRetirementPresentation,'function');});
test('phase 3046 fresh regular fatal pose gets a small grounded shadow under the existing sprite',async()=>{const {regularDefeatGroundRetirementPresentation}=await loadModule();const p=regularDefeatGroundRetirementPresentation('grunt',0,{offsetX:3,offsetY:1,alpha:1,radius:15},false);assert.equal(p.owner,'body');assert.ok(p.shadowAlpha>.16&&p.shadowAlpha<.4);assert.ok(Math.abs(p.shadowOffsetX)<2);});
test('phase 3047 agile regular enemies retire lighter than brute bodies without extra ground pulses',async()=>{const {regularDefeatGroundRetirementPresentation}=await loadModule();const h=regularDefeatGroundRetirementPresentation('hound',.28,{offsetX:8,offsetY:-2,alpha:.78,radius:14},false);const b=regularDefeatGroundRetirementPresentation('brute',.28,{offsetX:8,offsetY:-2,alpha:.78,radius:23},false);assert.ok(b.widthScale>h.widthScale);assert.equal(h.groundPulseScale,0);assert.equal(b.groundPulseScale,0);});
test('phase 3048 elite retirement keeps more ground weight than grunt but still fades before the body queue ends',async()=>{const {regularDefeatGroundRetirementPresentation}=await loadModule();const g=regularDefeatGroundRetirementPresentation('grunt',.48,{offsetX:5,offsetY:2,alpha:.62,radius:15},false);const e=regularDefeatGroundRetirementPresentation('elite',.48,{offsetX:5,offsetY:2,alpha:.62,radius:28},false);const late=regularDefeatGroundRetirementPresentation('elite',.93,{offsetX:2,offsetY:1,alpha:.2,radius:28},false);assert.ok(e.shadowAlpha>g.shadowAlpha);assert.equal(late.shadowAlpha,0);});
test('phase 3049 regular fatal shadow follows bounded recoil and reduced motion tightens it further',async()=>{const {regularDefeatGroundRetirementPresentation}=await loadModule();const full=regularDefeatGroundRetirementPresentation('archer',.34,{offsetX:12,offsetY:6,alpha:.72,radius:16},false);const reduced=regularDefeatGroundRetirementPresentation('archer',.34,{offsetX:12,offsetY:6,alpha:.72,radius:16},true);assert.ok(Math.abs(full.shadowOffsetX)<=3);assert.ok(Math.abs(full.shadowOffsetY)<=1.8);assert.ok(Math.abs(reduced.shadowOffsetX)<Math.abs(full.shadowOffsetX));});
test('phase 3050 defeated-body rendering uses regular retirement outside specialists and audit stays presentation-only',async()=>{assert.match(gameSource,/regularDefeatGroundRetirementPresentation/);assert.match(gameSource,/regularRetirement/);assert.match(gameSource,/deathGroundRetirement/);assert.equal(fs.existsSync(new URL('../src/game/regular-defeat-ground-retirement-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/regular-defeat-ground-retirement-audit.js');const audit=mod.runRegularDefeatGroundRetirementAudit();assert.equal(audit.samples.length,96);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
