import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-hazard-lifecycle-owner-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-hazard-lifecycle-owner-rendering.js');}
test('phase 3123 boss hazard lifecycle owner module exists',async()=>{const m=await load();assert.equal(typeof m.bossHazardLifecycleOwnerPresentation,'function');});
test('phase 3124 telegraph state owns lifecycle before activation',async()=>{const {bossHazardLifecycleOwnerPresentation}=await load();const p=bossHazardLifecycleOwnerPresentation({telegraph:.7,ttl:4,aftermathTtl:0,aftermathMaxTtl:0},false);assert.equal(p.owner,'telegraph');assert.equal(p.telegraphAlphaScale,1);assert.equal(p.activeAlphaScale,0);assert.equal(p.aftermathAlphaScale,0);});
test('phase 3125 active state fully retires telegraph ownership',async()=>{const {bossHazardLifecycleOwnerPresentation}=await load();const p=bossHazardLifecycleOwnerPresentation({telegraph:0,ttl:2,aftermathTtl:0,aftermathMaxTtl:0},false);assert.equal(p.owner,'active');assert.equal(p.telegraphAlphaScale,0);assert.equal(p.activeAlphaScale,1);});
test('phase 3126 aftermath owns lifecycle only after active hazard has expired',async()=>{const {bossHazardLifecycleOwnerPresentation}=await load();const p=bossHazardLifecycleOwnerPresentation({telegraph:0,ttl:0,aftermathTtl:.7,aftermathMaxTtl:.78},false);assert.equal(p.owner,'aftermath');assert.equal(p.activeAlphaScale,0);assert.ok(p.aftermathAlphaScale>0);});
test('phase 3127 reduced flash compresses aftermath intensity without creating overlapping owners',async()=>{const {bossHazardLifecycleOwnerPresentation}=await load();const f=bossHazardLifecycleOwnerPresentation({telegraph:0,ttl:0,aftermathTtl:.6,aftermathMaxTtl:.78},false),r=bossHazardLifecycleOwnerPresentation({telegraph:0,ttl:0,aftermathTtl:.6,aftermathMaxTtl:.78},true);assert.equal(r.owner,'aftermath');assert.ok(r.aftermathAlphaScale<f.aftermathAlphaScale);assert.equal(r.telegraphAlphaScale,0);assert.equal(r.activeAlphaScale,0);});
test('phase 3128 live hazard and aftermath renderers share lifecycle owner and audit stays presentation only',async()=>{const s=gameSource();assert.match(s,/bossHazardLifecycleOwnerPresentation/);assert.match(s,/telegraphAlphaScale/);assert.match(s,/activeAlphaScale/);assert.match(s,/aftermathAlphaScale/);const a=await import('../dist/game/boss-hazard-lifecycle-owner-audit.js');const audit=a.runBossHazardLifecycleOwnerAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
