import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const url=new URL('../src/game/specialist-recovery-hit-handoff-rendering.ts',import.meta.url);
async function load(){assert.equal(fs.existsSync(url),true);return import('../dist/game/specialist-recovery-hit-handoff-rendering.js');}
test('phase 3405 specialist recovery hit handoff module exists',async()=>{const m=await load();assert.equal(typeof m.specialistRecoveryHitHandoffPresentation,'function');});
test('phase 3406 committed pullback or lunge keeps attack ownership even under heavy hit pressure',async()=>{const m=await load();const p=m.specialistRecoveryHitHandoffPresentation({pullback:.82,lunge:.3,resolve:.15,hitStagger:1,tier:'heavy'},false);assert.equal(p.owner,'attack');assert.equal(p.attackResolveScale,1);assert.ok(p.hitStaggerScale<1);});
test('phase 3407 late attack recovery yields cleanly to a strong heavy hit',async()=>{const m=await load();const p=m.specialistRecoveryHitHandoffPresentation({pullback:0,lunge:0,resolve:.82,hitStagger:.9,tier:'heavy'},false);assert.equal(p.owner,'hit');assert.ok(p.attackResolveScale<.6);assert.ok(p.hitStaggerScale>.85);});
test('phase 3408 critical stagger takes recovery ownership earlier than heavy stagger',async()=>{const m=await load();const heavy=m.specialistRecoveryHitHandoffPresentation({pullback:0,lunge:0,resolve:.55,hitStagger:.68,tier:'heavy'},false),critical=m.specialistRecoveryHitHandoffPresentation({pullback:0,lunge:0,resolve:.55,hitStagger:.68,tier:'critical'},false);assert.ok(critical.hitStaggerScale>=heavy.hitStaggerScale);assert.ok(critical.attackResolveScale<=heavy.attackResolveScale);});
test('phase 3409 reduced motion keeps owner identity while all scales remain bounded',async()=>{const m=await load();const a=m.specialistRecoveryHitHandoffPresentation({pullback:0,lunge:0,resolve:.8,hitStagger:.92,tier:'critical'},false),b=m.specialistRecoveryHitHandoffPresentation({pullback:0,lunge:0,resolve:.8,hitStagger:.92,tier:'critical'},true);assert.equal(a.owner,b.owner);for(const v of [b.attackResolveScale,b.hitStaggerScale,b.silhouetteAlphaScale])assert.ok(v>=0&&v<=1);});
test('phase 3410 specialist render composes recovery handoff and audit remains presentation-only',async()=>{assert.match(source,/specialistRecoveryHitHandoffPresentation/);assert.match(source,/specialistRecoveryHandoff/);assert.match(source,/attackResolveScale/);const a=await import('../dist/game/specialist-recovery-hit-handoff-audit.js');const r=a.runSpecialistRecoveryHitHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
