import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/hero-action-pose-emphasis-rendering.js');}
const input=(over={})=>({owner:'cast',cast:.75,recovery:0,ultimateWindup:0,ultimateRelease:0,ultimateRecovery:0,hit:0,facingX:1,facingY:0,...over});
test('phase 3507 active cast pose leans forward and compresses vertically for clearer spell commitment',async()=>{const m=await load();const p=m.heroActionPoseEmphasisPresentation(input(),false);assert.equal(p.poseOwner,'cast');assert.ok(p.forwardLead>0);assert.ok(p.scaleX>1);assert.ok(p.scaleY<1);});
test('phase 3508 ultimate windup lifts and expands the hero more than an ordinary cast',async()=>{const m=await load();const cast=m.heroActionPoseEmphasisPresentation(input(),false),ult=m.heroActionPoseEmphasisPresentation(input({owner:'ultimate',cast:0,ultimateWindup:.9}),false);assert.equal(ult.poseOwner,'ultimate');assert.ok(ult.lift>cast.lift);assert.ok(ult.scaleX>cast.scaleX);});
test('phase 3509 ultimate release shifts farther into facing direction than windup',async()=>{const m=await load();const wind=m.heroActionPoseEmphasisPresentation(input({owner:'ultimate',cast:0,ultimateWindup:.9}),false),release=m.heroActionPoseEmphasisPresentation(input({owner:'ultimate',cast:0,ultimateRelease:.95}),false);assert.ok(release.forwardLead>wind.forwardLead);assert.ok(release.releaseAccentScale>wind.releaseAccentScale);});
test('phase 3510 recovery returns body scale toward neutral and lowers cast overlay ownership',async()=>{const m=await load();const cast=m.heroActionPoseEmphasisPresentation(input(),false),rec=m.heroActionPoseEmphasisPresentation(input({owner:'movement',cast:0,recovery:.8}),false);assert.equal(rec.poseOwner,'recovery');assert.ok(Math.abs(rec.scaleX-1)<Math.abs(cast.scaleX-1));assert.ok(rec.castOverlayAlphaScale<cast.castOverlayAlphaScale);});
test('phase 3511 hit pressure suppresses decorative action pose without changing action identity',async()=>{const m=await load();const clean=m.heroActionPoseEmphasisPresentation(input(),false),hit=m.heroActionPoseEmphasisPresentation(input({hit:.9}),false);assert.equal(hit.poseOwner,'cast');assert.ok(hit.poseStrength<clean.poseStrength);assert.equal(hit.presentationOnly,true);});
test('phase 3512 live hero body and cast overlays consume pose emphasis presentation-only',async()=>{const s=source();assert.match(s,/heroActionPoseEmphasisPresentation/);assert.match(s,/heroActionPose\.forwardLead/);assert.match(s,/heroActionPose\.castOverlayAlphaScale/);const mod=fs.readFileSync(new URL('../src/game/hero-action-pose-emphasis-rendering.ts',import.meta.url),'utf8');assert.doesNotMatch(mod,/damage|cooldown|mana|hp\s*[+\-*/]?=/i);const a=await import('../dist/game/hero-action-pose-emphasis-audit.js');const r=a.runHeroActionPoseEmphasisAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
