import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-cleared-safe-lane-arbitration-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-cleared-safe-lane-arbitration-rendering.js');}
test('phase 3195 boss cleared-ground safe-lane arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.bossClearedSafeLaneArbitrationPresentation,'function');});
test('phase 3196 corridor cleared memory shares ownership when safe lane lies inside corridor',async()=>{const {bossClearedSafeLaneArbitrationPresentation}=await load();const p=bossClearedSafeLaneArbitrationPresentation({shape:'corridor',center:{x:400,y:300},angle:0,halfLength:180,halfWidth:30,safeLaneTarget:{x:500,y:312},safeLaneConfidence:.82},false);assert.equal(p.owner,'shared');assert.equal(p.agrees,true);assert.ok(p.clearedAlphaScale>0&&p.clearedAlphaScale<1);assert.equal(p.safeLaneAlphaScale,1);});
test('phase 3197 contradictory corridor memory retires under authoritative safe lane',async()=>{const {bossClearedSafeLaneArbitrationPresentation}=await load();const p=bossClearedSafeLaneArbitrationPresentation({shape:'corridor',center:{x:400,y:300},angle:0,halfLength:170,halfWidth:28,safeLaneTarget:{x:410,y:430},safeLaneConfidence:.9},false);assert.equal(p.owner,'safe-lane');assert.equal(p.agrees,false);assert.equal(p.clearedAlphaScale,0);assert.equal(p.safeLaneAlphaScale,1);});
test('phase 3198 cross memory agrees with either orthogonal arm',async()=>{const {bossClearedSafeLaneArbitrationPresentation}=await load();const horizontal=bossClearedSafeLaneArbitrationPresentation({shape:'cross',center:{x:400,y:300},angle:0,halfLength:150,halfWidth:24,safeLaneTarget:{x:520,y:312},safeLaneConfidence:.76},false);const vertical=bossClearedSafeLaneArbitrationPresentation({shape:'cross',center:{x:400,y:300},angle:0,halfLength:150,halfWidth:24,safeLaneTarget:{x:410,y:420},safeLaneConfidence:.76},false);assert.equal(horizontal.agrees,true);assert.equal(vertical.agrees,true);});
test('phase 3199 circular or non-mythic/no-lane memory stays independent',async()=>{const {bossClearedSafeLaneArbitrationPresentation}=await load();const circle=bossClearedSafeLaneArbitrationPresentation({shape:'circle',center:{x:400,y:300},angle:0,halfLength:0,halfWidth:0,safeLaneTarget:{x:700,y:500},safeLaneConfidence:.9},false);const none=bossClearedSafeLaneArbitrationPresentation({shape:'corridor',center:{x:400,y:300},angle:0,halfLength:150,halfWidth:24},false);assert.equal(circle.owner,'cleared');assert.equal(circle.clearedAlphaScale,1);assert.equal(none.owner,'cleared');});
test('phase 3200 live mythic safe-lane target arbitrates geometry-aware cleared ground with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/bossClearedSafeLaneArbitrationPresentation/);assert.match(s,/currentMythicSafeLanePresentation/);assert.match(s,/clearedAlphaScale/);const a=await import('../dist/game/boss-cleared-safe-lane-arbitration-audit.js');const r=a.runBossClearedSafeLaneArbitrationAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
