import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/enemy-hit-death-transition-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/enemy-hit-death-transition-rendering.js');}
const motion={motionBlend:0.78,stride:1.2,facingX:1,facingY:0,turn:0.35,recovery:0.12};

test('phase 2973 enemy hit death transition module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.enemyHitStaggerPresentation,'function');assert.equal(typeof mod.enemyDeathTransitionPresentation,'function');});
test('phase 2974 heavy and critical hits increase stagger while keeping transforms bounded',async()=>{const mod=await loadModule();const normal=mod.enemyHitStaggerPresentation('grunt',0.1,'normal',-1,0,motion,false);const heavy=mod.enemyHitStaggerPresentation('grunt',0.1,'heavy',-1,0,motion,false);const critical=mod.enemyHitStaggerPresentation('grunt',0.1,'critical',-1,0,motion,false);assert.ok(heavy.stagger>normal.stagger);assert.ok(critical.stagger>heavy.stagger);assert.ok(Math.hypot(critical.offsetX,critical.offsetY)<=7);assert.ok(Math.abs(critical.rotation)<=0.18);});
test('phase 2975 death starts from the final hit direction and motion instead of popping to neutral',async()=>{const mod=await loadModule();const hit=mod.enemyHitStaggerPresentation('assassin',0.1,'critical',-1,0,motion,false);const death=mod.enemyDeathTransitionPresentation('assassin',{radius:18,facingX:1,facingY:0,motionBlend:0.78,turn:0.35,impactX:-1,impactY:0,tier:'critical'},0,false);assert.ok(death.alpha>0.85);assert.ok(death.carry>0.5);assert.ok(Math.sign(death.offsetX)===Math.sign(hit.offsetX));assert.ok(Math.abs(death.offsetX-hit.offsetX)<4);});
test('phase 2976 role weight differentiates assassin fall from siege golem collapse',async()=>{const mod=await loadModule();const snapshot={radius:22,facingX:1,facingY:0,motionBlend:0.7,turn:0.5,impactX:-1,impactY:0,tier:'heavy'};const assassin=mod.enemyDeathTransitionPresentation('assassin',snapshot,0.55,false);const golem=mod.enemyDeathTransitionPresentation('siegeGolem',snapshot,0.55,false);assert.ok(Math.abs(assassin.rotation)>Math.abs(golem.rotation));assert.ok(golem.offsetY>assassin.offsetY);assert.ok(golem.scaleY<assassin.scaleY);});
test('phase 2977 reduced motion keeps death direction and role identity with lower displacement',async()=>{const mod=await loadModule();const snapshot={radius:18,facingX:0.8,facingY:0.6,motionBlend:0.8,turn:-0.4,impactX:-0.8,impactY:-0.6,tier:'critical'};const full=mod.enemyDeathTransitionPresentation('assassin',snapshot,0.4,false);const reduced=mod.enemyDeathTransitionPresentation('assassin',snapshot,0.4,true);assert.equal(reduced.role,full.role);assert.ok(Math.hypot(reduced.offsetX,reduced.offsetY)<Math.hypot(full.offsetX,full.offsetY));assert.ok(Math.abs(reduced.rotation)<Math.abs(full.rotation));assert.equal(reduced.alpha,full.alpha);});
test('phase 2978 fatal damage snapshots motion and game renders a bounded defeated body queue using existing sprites',async()=>{assert.match(enemySource,/hitImpactTier/);assert.match(enemySource,/hitDirectionX/);assert.match(enemySource,/deathPose/);assert.match(gameSource,/enemyDefeatBodyTransitions/);assert.match(gameSource,/drawEnemyDefeatBodyTransitions/);assert.match(gameSource,/enemyDeathTransitionPresentation/);assert.match(gameSource,/enemySpriteRect/);assert.equal(fs.existsSync(new URL('../src/game/enemy-hit-death-transition-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/enemy-hit-death-transition-audit.js');const audit=mod.runEnemyHitDeathTransitionAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
