import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/hero-motion-budget-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-motion-budget-rendering.js');}

test('phase 3003 hero motion budget module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.heroMotionBudgetPresentation,'function');});
test('phase 3004 neutral movement keeps full locomotion ownership',async()=>{const mod=await loadModule();const p=mod.heroMotionBudgetPresentation({movement:.9,cast:0,ultimate:0,hit:0,evade:0},false);assert.equal(p.owner,'movement');assert.equal(p.movementScale,1);assert.equal(p.castScale,1);assert.equal(p.ultimateScale,1);assert.ok(p.totalLoad<=p.budgetCap+.0001);});
test('phase 3005 rapid cast plus movement compresses locomotion before cast readability',async()=>{const mod=await loadModule();const p=mod.heroMotionBudgetPresentation({movement:1,cast:.9,ultimate:0,hit:.35,evade:0},false);assert.equal(p.owner,'cast');assert.ok(p.movementScale<.7);assert.ok(p.castScale>.82);assert.ok(p.hitScale<1);assert.ok(p.totalLoad<=p.budgetCap+.0001);});
test('phase 3006 ultimate release owns the budget over simultaneous cast and hit micro transforms',async()=>{const mod=await loadModule();const p=mod.heroMotionBudgetPresentation({movement:1,cast:1,ultimate:1,hit:1,evade:1},false);assert.equal(p.owner,'ultimate');assert.ok(p.ultimateScale>.88);assert.ok(p.movementScale<.45);assert.ok(p.castScale<.8);assert.ok(p.hitScale<.7);const appliedLoad=p.movementScale+p.castScale+p.ultimateScale+p.hitScale+p.transitionScale;assert.ok(appliedLoad<=p.budgetCap+.0001);assert.ok(p.totalLoad<=p.budgetCap+.0001);});
test('phase 3007 perfect evade stays legible when no ultimate owns the body and reduced motion preserves owner',async()=>{const mod=await loadModule();const full=mod.heroMotionBudgetPresentation({movement:.8,cast:.45,ultimate:.1,hit:.7,evade:1},false);const reduced=mod.heroMotionBudgetPresentation({movement:.8,cast:.45,ultimate:.1,hit:.7,evade:1},true);assert.equal(full.owner,'evade');assert.equal(reduced.owner,'evade');assert.ok(full.transitionScale>.75);assert.ok(full.hitScale<.75);assert.ok(reduced.totalLoad<=reduced.budgetCap+.0001);});
test('phase 3008 hero render applies budget scales and audit stays presentation-only',async()=>{assert.match(gameSource,/heroMotionBudgetPresentation/);assert.match(gameSource,/motionBudget\.movementScale/);assert.match(gameSource,/motionBudget\.castScale/);assert.match(gameSource,/motionBudget\.ultimateScale/);assert.match(gameSource,/motionBudget\.hitScale/);assert.equal(fs.existsSync(new URL('../src/game/hero-motion-budget-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-motion-budget-audit.js');const audit=mod.runHeroMotionBudgetAudit();assert.equal(audit.samples.length,96);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
