import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/hero-ultimate-body-continuity-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-ultimate-body-continuity-rendering.js');}

test('phase 2967 hero ultimate body continuity module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceHeroUltimateBodyState,'function');assert.equal(typeof mod.heroUltimateBodyPresentation,'function');});
test('phase 2968 meteor storm carries a readable windup into release and recovery',async()=>{const mod=await loadModule();let s=mod.advanceHeroUltimateBodyState(undefined,'meteorStorm',0,false);const wind=mod.heroUltimateBodyPresentation(s,1,0,false);s=mod.advanceHeroUltimateBodyState(s,null,0.09,false);const release=mod.heroUltimateBodyPresentation(s,1,0,false);s=mod.advanceHeroUltimateBodyState(s,null,0.20,false);const recover=mod.heroUltimateBodyPresentation(s,1,0,false);assert.ok(wind.windup>0.7);assert.ok(release.release>wind.release);assert.ok(release.offsetY<wind.offsetY);assert.ok(recover.recovery>0.25);assert.equal(release.stance,'meteor-release');});
test('phase 2969 black hole uses inward compression and counter-rotation distinct from meteor',async()=>{const mod=await loadModule();let a=mod.advanceHeroUltimateBodyState(undefined,'meteorStorm',0,false);let b=mod.advanceHeroUltimateBodyState(undefined,'blackHole',0,false);a=mod.advanceHeroUltimateBodyState(a,null,0.11,false);b=mod.advanceHeroUltimateBodyState(b,null,0.11,false);const meteor=mod.heroUltimateBodyPresentation(a,0.8,0.6,false);const hole=mod.heroUltimateBodyPresentation(b,0.8,0.6,false);assert.notEqual(meteor.stance,hole.stance);assert.ok(hole.scaleX<meteor.scaleX);assert.ok(Math.abs(hole.rotation)>0.015);assert.ok(Math.hypot(hole.offsetX,hole.offsetY)<=7);});
test('phase 2970 ultimate continuity suppresses ordinary cast recovery pop while active and fully clears',async()=>{const mod=await loadModule();let s=mod.advanceHeroUltimateBodyState(undefined,'blackHole',0,false);s=mod.advanceHeroUltimateBodyState(s,null,0.18,false);let p=mod.heroUltimateBodyPresentation(s,1,0,false);assert.ok(p.castRecoverySuppression>0.4);for(let i=0;i<40;i++)s=mod.advanceHeroUltimateBodyState(s,null,0.05,false);p=mod.heroUltimateBodyPresentation(s,1,0,false);assert.equal(s.kind,null);assert.equal(p.castRecoverySuppression,0);assert.equal(p.offsetX,0);assert.equal(p.offsetY,0);assert.equal(p.rotation,0);assert.equal(p.scaleX,1);assert.equal(p.scaleY,1);});
test('phase 2971 reduced motion preserves ultimate phase identity with compressed transform',async()=>{const mod=await loadModule();let s=mod.advanceHeroUltimateBodyState(undefined,'meteorStorm',0,false);s=mod.advanceHeroUltimateBodyState(s,null,0.1,false);const full=mod.heroUltimateBodyPresentation(s,1,0,false);const reduced=mod.heroUltimateBodyPresentation(s,1,0,true);assert.equal(reduced.stance,full.stance);assert.equal(reduced.release,full.release);assert.ok(Math.hypot(reduced.offsetX,reduced.offsetY)<Math.hypot(full.offsetX,full.offsetY));assert.ok(Math.abs(reduced.rotation)<=Math.abs(full.rotation));});
test('phase 2972 successful ultimate cast integrates body continuity and audit stays presentation-only',async()=>{assert.match(gameSource,/heroUltimateBodyState/);assert.match(gameSource,/advanceHeroUltimateBodyState/);assert.match(gameSource,/heroUltimateBodyPresentation/);assert.match(gameSource,/action === 'ultimate1'/);assert.match(gameSource,/meteorStorm/);assert.match(gameSource,/blackHole/);assert.equal(fs.existsSync(new URL('../src/game/hero-ultimate-body-continuity-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-ultimate-body-continuity-audit.js');const audit=mod.runHeroUltimateBodyContinuityAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
