import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/hero-cast-cadence-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-cast-cadence-rendering.js');}

test('phase 2931 hero cast cadence module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceHeroCastCadenceState,'function');assert.equal(typeof mod.heroCastCadencePresentation,'function');});
test('phase 2932 consecutive casts inside bridge window build chain continuity',async()=>{const mod=await loadModule();let s=mod.advanceHeroCastCadenceState(undefined,true,0.016,false);s=mod.advanceHeroCastCadenceState(s,false,0.11,false);s=mod.advanceHeroCastCadenceState(s,true,0.016,false);assert.ok(s.chain>=2);assert.ok(s.bridge>0.6);});
test('phase 2933 chained cast suppresses recover-to-neutral pop',async()=>{const mod=await loadModule();let s=mod.advanceHeroCastCadenceState(undefined,true,0.016,false);s=mod.advanceHeroCastCadenceState(s,false,0.12,false);s=mod.advanceHeroCastCadenceState(s,true,0.016,false);const p=mod.heroCastCadencePresentation(s,0.9,0.8,0.2,false);assert.ok(p.recoverBlend<0.8);assert.ok(p.castBlend>=0.9);assert.ok(p.neutralReturn<0.4);});
test('phase 2934 moving cast chain preserves controlled forward lead',async()=>{const mod=await loadModule();let s=mod.advanceHeroCastCadenceState(undefined,true,0.016,false);s=mod.advanceHeroCastCadenceState(s,true,0.08,false);const moving=mod.heroCastCadencePresentation(s,1,0.5,0.9,false);const still=mod.heroCastCadencePresentation(s,1,0.5,0,false);assert.ok(moving.chainLead>still.chainLead);assert.ok(moving.chainLead<=3.8);});
test('phase 2935 reduced motion keeps chain identity with compressed transform',async()=>{const mod=await loadModule();let s=mod.advanceHeroCastCadenceState(undefined,true,0.016,false);s=mod.advanceHeroCastCadenceState(s,true,0.08,false);const full=mod.heroCastCadencePresentation(s,1,0.6,0.9,false);const reduced=mod.heroCastCadencePresentation(s,1,0.6,0.9,true);assert.equal(reduced.chain,full.chain);assert.ok(reduced.chainLead<full.chainLead);assert.ok(Math.abs(reduced.bodyScale-1)<Math.abs(full.bodyScale-1));});
test('phase 2936 game integrates cadence state and deterministic audit stays presentation-only',async()=>{assert.match(gameSource,/heroCastCadenceState/);assert.match(gameSource,/advanceHeroCastCadenceState/);assert.match(gameSource,/heroCastCadencePresentation/);assert.equal(fs.existsSync(new URL('../src/game/hero-cast-cadence-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-cast-cadence-audit.js');const audit=mod.runHeroCastCadenceAudit();assert.equal(audit.samples.length,48);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
