import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/safe-lane-forecast-visual-coherence-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/safe-lane-forecast-visual-coherence-rendering.js');}
test('phase 3231 safe-lane forecast visual-coherence module exists',async()=>{const m=await load();assert.equal(typeof m.safeLaneForecastVisualCoherencePresentation,'function');});
test('phase 3232 stable forecast keeps current target for all primary safe-lane visuals',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:500,y:310},currentConfidence:.82,nextTarget:{x:410,y:430},forecastUrgency:.3,transitionMs:3200},false);assert.equal(p.owner,'current');assert.deepEqual(p.target,{x:500,y:310});assert.equal(p.forecastPromoted,false);});
test('phase 3233 imminent high-urgency forecast promotes nextTarget for line label icon and arrival VFX',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:500,y:310},currentConfidence:.78,nextTarget:{x:410,y:430},forecastUrgency:.82,transitionMs:760},false);assert.equal(p.owner,'forecast');assert.deepEqual(p.target,{x:410,y:430});assert.equal(p.forecastPromoted,true);});
test('phase 3234 promoted forecast keeps transition bridge secondary rather than competing with the primary target',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:500,y:310},currentConfidence:.78,nextTarget:{x:410,y:430},forecastUrgency:.9,transitionMs:640},false);assert.ok(p.bridgeAlphaScale>0&&p.bridgeAlphaScale<1);assert.equal(p.primaryAlphaScale,1);});
test('phase 3235 reduced flash never raises bridge or primary safe-lane emphasis',async()=>{const m=await load();const input={currentTarget:{x:500,y:310},currentConfidence:.78,nextTarget:{x:410,y:430},forecastUrgency:.9,transitionMs:640};const normal=m.safeLaneForecastVisualCoherencePresentation(input,false),reduced=m.safeLaneForecastVisualCoherencePresentation(input,true);assert.ok(reduced.bridgeAlphaScale<=normal.bridgeAlphaScale);assert.ok(reduced.primaryAlphaScale<=normal.primaryAlphaScale);});
test('phase 3236 live mythic rendering reuses one forecast visual target across line transition VFX icons and label with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/safeLaneForecastVisualCoherencePresentation/);assert.match(s,/safeLaneVisualTarget/);assert.match(s,/drawMapSafeLaneTransitionVfx\(ctx,safeLane,safeLaneVisualTarget/);assert.match(s,/drawMythicArenaGeometrySafeLaneIcon\([^\n]*safeLaneVisualTarget/);const a=await import('../dist/game/safe-lane-forecast-visual-coherence-audit.js');const r=a.runSafeLaneForecastVisualCoherenceAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
