import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-critical-reengagement-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4149 boss telegraph re-engagement locks danger edge authority',async()=>{const {bossTelegraphReengagementLockPresentation}=await load();const p=bossTelegraphReengagementLockPresentation({active:true,critical:true,reacquire:.2,crowd:1},false);assert.ok(p.edgeAlphaScale>=.96);assert.ok(p.staleDecorationScale<1);});
test('Phase 4150 boss projectile re-engagement keeps canonical body visible',async()=>{const {bossProjectileReengagementLockPresentation}=await load();const p=bossProjectileReengagementLockPresentation({active:true,critical:true,reacquire:.2,laneProximity:.9,crowd:1},false,false);assert.equal(p.bodyScale,1);assert.ok(p.trailScale>=.8);});
test('Phase 4151 boss impact re-engagement retires fill before edge',async()=>{const {bossImpactReengagementLockPresentation}=await load();const p=bossImpactReengagementLockPresentation({bossProximity:1,reacquire:.2,crowd:1,critical:false},false);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);});
test('Phase 4152 safe lane critical re-engagement keeps escape path floor',async()=>{const {safeLaneCriticalReengagementLockPresentation}=await load();const p=safeLaneCriticalReengagementLockPresentation({visible:true,confidence:.9,bossPressure:1,critical:true,reacquire:.2},false);assert.ok(p.pathAlphaFloor>=.95);assert.ok(p.safeLaneScale>=1);});
test('Phase 4153 specialist boss re-engagement preserves body and facing',async()=>{const {specialistBossReengagementLockPresentation}=await load();const p=specialistBossReengagementLockPresentation({bossProximity:1,owner:'attack',reacquire:.2,critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.directionScale>=.8);assert.ok(p.secondaryScale<1);});
test('Phase 4154 critical re-engagement budget preserves canonical and telegraph owners',async()=>{const {criticalReengagementBudgetPresentation}=await load();const p=criticalReengagementBudgetPresentation({bossActive:true,criticalCount:2,projectileCount:12,impactCount:8,hazardCount:5,silhouetteCount:4,safeLaneVisible:true},false,false);assert.equal(p.canonicalScale,1);assert.equal(p.telegraphEdgeScale,1);assert.ok(p.secondaryScale<1);assert.ok(p.safeLaneScale>=1);});
test('Phase 4149-4154 live renderers consume critical re-engagement helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/bossProjectileReengagementLockPresentation/);assert.match(e,/specialistBossReengagementLockPresentation/);assert.match(s,/bossImpactReengagementLockPresentation/);assert.match(g,/bossTelegraphReengagementLockPresentation/);assert.match(g,/safeLaneCriticalReengagementLockPresentation/);});
