import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-depth-plane-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4119 projectile depth plane protects body while flattening deep trail',async()=>{const {projectileDepthPlanePresentation}=await load();const p=projectileDepthPlanePresentation({bodyOverlap:1,laneProximity:.8,crowd:1,critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.trailScale<.9);assert.ok(p.trailLineScale<=1);});
test('Phase 4120 impact depth plane keeps edge stronger than fill near hero',async()=>{const {impactDepthPlanePresentation}=await load();const p=impactDepthPlanePresentation({heroProximity:1,crowd:1,critical:false},false);assert.ok(p.edgeScale>=p.fillScale);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);});
test('Phase 4121 hazard foreground boundary remains stable under dense overlap',async()=>{const {hazardDepthPlanePresentation}=await load();const p=hazardDepthPlanePresentation({telegraph:true,laneProximity:.9,crowd:1,critical:true},false);assert.ok(p.edgeAlphaScale>=.94);assert.ok(p.fillScale<1);});
test('Phase 4122 safe lane contour keeps foreground floor',async()=>{const {safeLaneContourDepthPresentation}=await load();const p=safeLaneContourDepthPresentation({visible:true,confidence:.9,pressure:1},false);assert.ok(p.contourAlphaScale>=1);assert.ok(p.contourWidthScale>=1);});
test('Phase 4123 specialist rim survives background hazard density',async()=>{const {specialistRimDepthPresentation}=await load();const p=specialistRimDepthPresentation({owner:'attack',hazardPressure:1,crowd:1,critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.rimAlphaScale>=.72);assert.ok(p.secondaryScale<1);});
test('Phase 4124 depth plane budget preserves canonical foreground owners',async()=>{const {depthPlaneBudgetPresentation}=await load();const p=depthPlaneBudgetPresentation({criticalCount:2,projectileCount:14,impactCount:8,hazardCount:6,silhouetteCount:5,safeLaneVisible:true},false,false);assert.equal(p.canonicalScale,1);assert.equal(p.criticalAlphaScale,1);assert.ok(p.backgroundScale<1);assert.ok(p.safeLaneScale>=1);});
test('Phase 4119-4124 live renderers consume depth plane helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileDepthPlanePresentation/);assert.match(e,/specialistRimDepthPresentation/);assert.match(s,/impactDepthPlanePresentation/);assert.match(g,/safeLaneContourDepthPresentation/);assert.match(g,/hazardDepthPlanePresentation/);});
