import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-cluster-split-lineage-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-cluster-split-lineage-rendering.js');}
const keyAt=(m,s,x,y)=>m.secondaryImpactSplitLineageFor(s,{x,y}).key;
test('phase 3207 split-lineage entries expose explicit retirement state for cycle arbitration',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:180,y:220}},{pos:{x:320,y:220}}],.016);assert.ok(s.entries.length>=2);assert.equal(s.entries.every(e=>e.retired===false),true);});
test('phase 3208 initial split creates distinct active branch lineages',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:250,y:220}},{pos:{x:258,y:220}}],.016);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:190,y:220}},{pos:{x:198,y:220}},{pos:{x:310,y:220}},{pos:{x:318,y:220}}],.04);assert.notEqual(keyAt(m,s,194,220),keyAt(m,s,314,220));assert.equal(s.entries.every(e=>e.retired===false),true);});
test('phase 3209 merge retires the unmatched child instead of leaving it matchable',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:190,y:220}},{pos:{x:198,y:220}},{pos:{x:310,y:220}},{pos:{x:318,y:220}}],.016);const right=keyAt(m,s,314,220);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:246,y:220}},{pos:{x:254,y:220}}],.04);const retired=s.entries.find(e=>e.key===right);assert.ok(retired);assert.equal(retired.retired,true);});
test('phase 3210 split after merge never resurrects the retired child onto a new branch',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:190,y:220}},{pos:{x:198,y:220}},{pos:{x:310,y:220}},{pos:{x:318,y:220}}],.016);const oldRight=keyAt(m,s,314,220);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:246,y:220}},{pos:{x:254,y:220}}],.04);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:188,y:220}},{pos:{x:196,y:220}},{pos:{x:304,y:220}},{pos:{x:312,y:220}}],.04);assert.notEqual(keyAt(m,s,308,220),oldRight);});
test('phase 3211 repeated merge-split cycles allocate fresh child identities before old tombstones expire',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:180,y:210}},{pos:{x:320,y:210}}],.016);const old1=keyAt(m,s,320,210);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:250,y:210}}],.04);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:185,y:210}},{pos:{x:315,y:210}}],.04);const fresh1=keyAt(m,s,315,210);assert.notEqual(fresh1,old1);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:250,y:210}}],.04);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:185,y:210}},{pos:{x:315,y:210}}],.04);const fresh2=keyAt(m,s,315,210);assert.notEqual(fresh2,old1);assert.notEqual(fresh2,fresh1);});
test('phase 3212 live secondary budget still consumes cycle-safe lineage keys with presentation-only audit',async()=>{const s=spellSource();assert.match(s,/secondaryImpactClusterSplitLineage/);assert.match(s,/stableClusterKey:lineageKey/);const a=await import('../dist/game/secondary-impact-cluster-cycle-lineage-audit.js');const r=a.runSecondaryImpactClusterCycleLineageAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
