import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-displacement-aftermath-origin-rendering.ts',import.meta.url);
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-displacement-aftermath-origin-rendering.js');}

test('phase 3069 boss displacement aftermath origin module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.bossDisplacementAftermathOriginPresentation,'function');});
test('phase 3070 large displacement aftermath follows the bounded rebase origin rather than the stale full pre dash origin',async()=>{const {bossDisplacementAftermathOriginPresentation}=await loadModule();const p=bossDisplacementAftermathOriginPresentation({rebase:1,groundOffsetX:-34,groundOffsetY:14,specialStrength:1,settle:.8},false);assert.ok(p.originOffsetX<0);assert.ok(Math.abs(p.originOffsetX)<=18);assert.ok(Math.abs(p.originOffsetY)<=11);assert.ok(p.aftermathAlphaScale<1);});
test('phase 3071 settled boss returns aftermath origin to current body origin monotonically',async()=>{const {bossDisplacementAftermathOriginPresentation}=await loadModule();const a=bossDisplacementAftermathOriginPresentation({rebase:.9,groundOffsetX:-18,groundOffsetY:6,specialStrength:.7,settle:.8},false);const b=bossDisplacementAftermathOriginPresentation({rebase:.45,groundOffsetX:-18,groundOffsetY:6,specialStrength:.3,settle:.45},false);const c=bossDisplacementAftermathOriginPresentation({rebase:0,groundOffsetX:0,groundOffsetY:0,specialStrength:0,settle:.1},false);assert.ok(Math.abs(b.originOffsetX)<Math.abs(a.originOffsetX));assert.equal(c.originOffsetX,0);assert.equal(c.originOffsetY,0);});
test('phase 3072 special action telegraph keeps priority by suppressing stale displacement aftermath cue density',async()=>{const {bossDisplacementAftermathOriginPresentation}=await loadModule();const p=bossDisplacementAftermathOriginPresentation({rebase:.8,groundOffsetX:-16,groundOffsetY:4,specialStrength:1,settle:.7},false);assert.ok(p.contactPulseScale<.4);assert.ok(p.aftermathAlphaScale<.7);});
test('phase 3073 reduced motion tightens aftermath trail origin and alpha without changing owner semantics',async()=>{const {bossDisplacementAftermathOriginPresentation}=await loadModule();const full=bossDisplacementAftermathOriginPresentation({rebase:1,groundOffsetX:-28,groundOffsetY:10,specialStrength:.6,settle:.8},false);const reduced=bossDisplacementAftermathOriginPresentation({rebase:1,groundOffsetX:-28,groundOffsetY:10,specialStrength:.6,settle:.8},true);assert.equal(full.owner,'rebase');assert.equal(reduced.owner,'rebase');assert.ok(Math.abs(reduced.originOffsetX)<Math.abs(full.originOffsetX));assert.ok(reduced.aftermathAlphaScale<=full.aftermathAlphaScale);});
test('phase 3074 boss contact aftermath uses the same rebase origin and audit stays presentation only',async()=>{assert.match(enemySource,/bossDisplacementAftermathOriginPresentation/);assert.match(enemySource,/bossAftermath\.originOffsetX/);assert.match(enemySource,/bossAftermath\.contactPulseScale/);assert.match(enemySource,/Math\.min\([^;]*bossAftermath\.contactPulseScale/);assert.doesNotMatch(enemySource,/bossSpecialOriginHandoff\.contactPulseScale\*bossAftermath\.contactPulseScale/);assert.match(enemySource,/ctx\.translate\(bossAftermath\.originOffsetX,bossAftermath\.originOffsetY\)/);assert.equal(fs.existsSync(new URL('../src/game/boss-displacement-aftermath-origin-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-displacement-aftermath-origin-audit.js');const audit=mod.runBossDisplacementAftermathOriginAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
