import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/enemy-portal-ground-materialize-rendering.ts',import.meta.url);
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/enemy-portal-ground-materialize-rendering.js');}

test('phase 3063 portal ground materialize module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceEnemyPortalGroundMaterializeState,'function');assert.equal(typeof mod.enemyPortalGroundMaterializePresentation,'function');});
test('phase 3064 ordinary lane portal spawn begins with muted locomotion and a settling shadow',async()=>{const {advanceEnemyPortalGroundMaterializeState,enemyPortalGroundMaterializePresentation}=await loadModule();const s=advanceEnemyPortalGroundMaterializeState(undefined,{kind:'regular'},0,false);const p=enemyPortalGroundMaterializePresentation(s,false);assert.ok(s&&s.strength>.95);assert.ok(p.locomotionScale<.35);assert.ok(p.shadowAlphaScale<.7);assert.ok(p.groundPulseScale<.35);});
test('phase 3065 elite and specialist portal spawns keep distinct grounded weight without new assets',async()=>{const {advanceEnemyPortalGroundMaterializeState,enemyPortalGroundMaterializePresentation}=await loadModule();const elite=enemyPortalGroundMaterializePresentation(advanceEnemyPortalGroundMaterializeState(undefined,{kind:'elite'},0,false),false);const specialist=enemyPortalGroundMaterializePresentation(advanceEnemyPortalGroundMaterializeState(undefined,{kind:'specialist'},0,false),false);assert.ok(elite.shadowWidthScale>specialist.shadowWidthScale);assert.ok(elite.shadowWidthScale>1);assert.ok(specialist.shadowAlphaScale>=.4);});
test('phase 3066 materialize ownership retires completely after the portal window instead of becoming permanent per enemy overhead',async()=>{const {advanceEnemyPortalGroundMaterializeState,enemyPortalGroundMaterializePresentation}=await loadModule();let s=advanceEnemyPortalGroundMaterializeState(undefined,{kind:'regular'},0,false);for(let i=0;i<10;i++)s=advanceEnemyPortalGroundMaterializeState(s,null,.08,false);assert.equal(s,undefined);const p=enemyPortalGroundMaterializePresentation(s,false);assert.equal(p.locomotionScale,1);assert.equal(p.shadowAlphaScale,1);});
test('phase 3067 reduced motion shortens the portal ground handoff while keeping spawn identity readable',async()=>{const {advanceEnemyPortalGroundMaterializeState,enemyPortalGroundMaterializePresentation}=await loadModule();let full=advanceEnemyPortalGroundMaterializeState(undefined,{kind:'regular'},0,false),reduced=advanceEnemyPortalGroundMaterializeState(undefined,{kind:'regular'},0,true);full=advanceEnemyPortalGroundMaterializeState(full,null,.12,false);reduced=advanceEnemyPortalGroundMaterializeState(reduced,null,.12,true);assert.ok((reduced?.strength??0)<(full?.strength??0));assert.ok(enemyPortalGroundMaterializePresentation(reduced,true).shadowAlphaScale>.4);});
test('phase 3068 ordinary spawn attaches materialize state only alongside portal vfx and audit stays presentation only',async()=>{assert.match(enemySource,/spawnGroundMaterialize/);assert.match(enemySource,/advanceEnemyPortalGroundMaterializeState/);assert.match(enemySource,/enemyPortalGroundMaterializePresentation/);assert.match(enemySource,/spawnPortalVfx\.push/);assert.match(enemySource,/portalKind !== 'boss'/);assert.match(enemySource,/ctx\.reducedMotion\?\?false/);assert.match(gameSource,/reducedMotion: this\.presentationSettings\.reducedMotion/);assert.equal(fs.existsSync(new URL('../src/game/enemy-portal-ground-materialize-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/enemy-portal-ground-materialize-audit.js');const audit=mod.runEnemyPortalGroundMaterializeAudit();assert.equal(audit.samples.length,48);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
