import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-rhythm-recovery-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now()+Math.random());}
test('Phase 4197 projectile recovery staggers slot return instead of synchronized snapback',async()=>{const {projectileThreatRhythmRecoveryPresentation}=await load();const a=projectileThreatRhythmRecoveryPresentation({release:.55,stress:.8,critical:false,slot:0}),b=projectileThreatRhythmRecoveryPresentation({release:.55,stress:.8,critical:false,slot:3});assert.equal(a.primaryScale,1);assert.ok(a.secondaryScale>b.secondaryScale+.05);});
test('Phase 4198 impact recovery remains bounded during high stress',async()=>{const {impactThreatRhythmRecoveryPresentation}=await load();const p=impactThreatRhythmRecoveryPresentation({release:.35,stress:1,critical:false,slot:2});assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale>=0&&p.secondaryScale<1);});
test('Phase 4199 hazard recovery respects reduced presentation settings',async()=>{const {hazardThreatRhythmRecoveryPresentation}=await load();const p=hazardThreatRhythmRecoveryPresentation({release:.7,stress:.9,critical:true,slot:1},true,true);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<=1);});
test('Phase 4200 safe lane recovery never attenuates canonical lane ownership',async()=>{const {safeLaneThreatRhythmRecoveryPresentation}=await load();const p=safeLaneThreatRhythmRecoveryPresentation({release:.5,stress:1,critical:true,slot:0});assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);});
test('Phase 4201 specialist recovery increases gradually with release',async()=>{const {specialistThreatRhythmRecoveryPresentation}=await load();const early=specialistThreatRhythmRecoveryPresentation({release:.2,stress:.7,critical:false,slot:1}),late=specialistThreatRhythmRecoveryPresentation({release:.9,stress:.7,critical:false,slot:1});assert.ok(late.secondaryScale>early.secondaryScale);});
test('Phase 4202 recovery budget caps simultaneous secondary rebound',async()=>{const {threatRhythmRecoveryBudgetPresentation}=await load();const p=threatRhythmRecoveryBudgetPresentation({activeCount:12,criticalCount:2,stress:1,release:.7,safeLaneVisible:true});assert.equal(p.maxConcurrentRecoveries,1);assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4197-4202 live renderers consume threat rhythm recovery helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileThreatRhythmRecoveryPresentation/);assert.match(e,/specialistThreatRhythmRecoveryPresentation/);assert.match(s,/impactThreatRhythmRecoveryPresentation/);assert.match(g,/hazardThreatRhythmRecoveryPresentation/);assert.match(g,/safeLaneThreatRhythmRecoveryPresentation/);assert.match(e,/projectileRhythmRecovery\.secondaryScale/);});
