import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-canonical-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-canonical-rendering.js');}
test('phase 3135 secondary impact canonical module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactCanonicalPresentation,'function');});
test('phase 3136 splash secondary impact never inherits primary launch offset',async()=>{const {secondaryImpactCanonicalPresentation}=await load();const p=secondaryImpactCanonicalPresentation('splash',{x:120,y:80},false);assert.equal(p.owner,'canonical');assert.deepEqual(p.entryOffset,{x:0,y:0});assert.deepEqual(p.pos,{x:120,y:80});});
test('phase 3137 chain secondary impact is canonical at the struck target',async()=>{const {secondaryImpactCanonicalPresentation}=await load();const p=secondaryImpactCanonicalPresentation('chain',{x:220,y:160},false);assert.equal(p.owner,'canonical');assert.equal(p.kind,'chain');assert.deepEqual(p.entryOffset,{x:0,y:0});});
test('phase 3138 secondary impacts use smaller bounded visual weight',async()=>{const {secondaryImpactCanonicalPresentation}=await load();const s=secondaryImpactCanonicalPresentation('splash',{x:0,y:0},false),c=secondaryImpactCanonicalPresentation('chain',{x:0,y:0},false);assert.ok(s.sizeScale>=.45&&s.sizeScale<=.8);assert.ok(c.sizeScale>=.45&&c.sizeScale<=.8);});
test('phase 3139 reduced flash lowers secondary impact alpha only',async()=>{const {secondaryImpactCanonicalPresentation}=await load();const f=secondaryImpactCanonicalPresentation('chain',{x:0,y:0},false),r=secondaryImpactCanonicalPresentation('chain',{x:0,y:0},true);assert.deepEqual(r.pos,f.pos);assert.deepEqual(r.entryOffset,{x:0,y:0});assert.ok(r.alphaScale<f.alphaScale);});
test('phase 3140 splash and chain live paths queue canonical secondary impact visuals with presentation-only audit',async()=>{const s=spellSource();assert.match(s,/secondaryImpactCanonicalPresentation\('splash'/);assert.match(s,/secondaryImpactCanonicalPresentation\('chain'/);assert.match(s,/entryOffset:secondary\.entryOffset/);assert.match(s,/alphaScale:secondary\.alphaScale/);const a=await import('../dist/game/secondary-impact-canonical-audit.js');const audit=a.runSecondaryImpactCanonicalAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
