import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/perfect-evade-trail-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/perfect-evade-trail-vfx-assets.js');}
test('phase 2553 perfect evade trail atlas covers four heroes x three directional states',async()=>{const mod=await load(),audit=mod.auditPerfectEvadeTrailVfxAtlas();assert.equal(audit.heroCount,4);assert.equal(audit.stateCount,3);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.PERFECT_EVADE_TRAIL_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:512,height:384});assert.ok(b.length>5000);});
test('phase 2554 perfect evade records the real hero facing vector without changing reward math',()=>{assert.match(gameSource,/queuePerfectEvadeTrailVfx\(this\.hero\.facing\.x,this\.hero\.facing\.y\)/);assert.match(gameSource,/this\.arenaEvadeMoveMultiplier = Math\.min\(1\.08, dodgeStep\.reward\.moveSpeedMultiplier \* chainReward\.moveSpeedBonusMultiplier\)/);});
test('phase 2555 evade trail progresses escape slipstream success and rotates with movement direction',()=>{assert.match(gameSource,/progress<0\.28\?'escape':progress<0\.72\?'slipstream':'success'/);assert.match(gameSource,/Math\.atan2\(cue\.dirY,cue\.dirX\)/);assert.match(gameSource,/perfectEvadeTrailVfxSprite\(cue\.heroId,state\)/);});
test('phase 2556 evade trail queue is bounded resettable and advances using safe dt',()=>{assert.match(gameSource,/perfectEvadeTrailVfx\.length>12/);assert.match(gameSource,/for\(const cue of this\.perfectEvadeTrailVfx\)cue\.ttl-=safeDt/);assert.match(gameSource,/this\.perfectEvadeTrailVfx=\[\]/);});
test('phase 2557 evade trail image loading is fail-open and reduced flash capped',()=>{assert.match(gameSource,/initializePerfectEvadeTrailVfxAtlas/);assert.match(gameSource,/perfectEvadeTrailVfxAtlasImage/);assert.match(gameSource,/this\.presentationSettings\.reducedFlash\?0\.34:0\.68/);assert.match(gameSource,/this\.queueHeroResponseVfx\('perfectEvade',1\)/);});
test('phase 2558 evade trail audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/perfect-evade-trail-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/perfect-evade-trail-vfx-audit.js'),audit=mod.runPerfectEvadeTrailVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/perfectEvadeTrailVfxPassed/);assert.match(candidateSource,/perfectEvadeTrailVfxPassed/);assert.match(candidateSource,/perfect-evade-trail-vfx/);});
