import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-spatial-separation-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href);}
test('Phase 4101 projectile corridor yields trail before canonical body',async()=>{const {projectileCorridorSeparationPresentation}=await load();const p=projectileCorridorSeparationPresentation({bodyOverlap:1,laneProximity:1,neighborCount:8,critical:false},false);assert.equal(p.bodyAlphaScale,1);assert.ok(p.trailAlphaScale<.7);assert.ok(p.trailAlphaScale>=.42);});
test('Phase 4102 boss telegraph and safe lane outrank overlapping decoration',async()=>{const {telegraphSafeLaneSeparationPresentation}=await load();const p=telegraphSafeLaneSeparationPresentation({telegraphActive:true,safeLaneVisible:true,overlap:1,critical:true},false);assert.ok(p.telegraphEdgeAlphaScale>=.94);assert.ok(p.safeLaneAlphaScale>=1);assert.ok(p.secondaryAlphaScale<1);});
test('Phase 4103 hero corridor impact retires fill before edge',async()=>{const {impactCorridorSeparationPresentation}=await load();const p=impactCorridorSeparationPresentation({heroProximity:1,safeLaneProximity:.9,neighborCount:7,critical:false},false);assert.equal(p.canonicalAlphaScale,1);assert.ok(p.fillAlphaScale<p.edgeAlphaScale);});
test('Phase 4104 specialist direction survives hazard crowd',async()=>{const {specialistDirectionalSeparationPresentation}=await load();const p=specialistDirectionalSeparationPresentation({owner:'attack',hazardPressure:1,crowd:1,attackStrength:1},false);assert.equal(p.bodyAlphaScale,1);assert.ok(p.directionAlphaScale>=.68);assert.ok(p.secondaryAlphaScale<1);});
test('Phase 4105 canonical corridor keeps safe lane floor',async()=>{const {canonicalCorridorProtectionPresentation}=await load();const p=canonicalCorridorProtectionPresentation({safeLaneVisible:true,laneConfidence:.9,threatPressure:1,edgeProximity:.8},false);assert.equal(p.canonicalBodyAlphaScale,1);assert.ok(p.pathAlphaFloor>=.92);assert.ok(p.safeLaneAlphaScale>=1);});
test('Phase 4106 spatial budget preserves critical and body before secondary vfx',async()=>{const {spatialThreatSeparationBudgetPresentation}=await load();const p=spatialThreatSeparationBudgetPresentation({criticalCount:2,safeLaneVisible:true,projectileCount:12,impactCount:8,hazardCount:6,silhouetteCount:5},false,false);assert.equal(p.criticalAlphaScale,1);assert.equal(p.canonicalBodyAlphaScale,1);assert.ok(p.secondaryAlphaScale<1);assert.ok(p.safeLaneAlphaScale>=1);});
test('Phase 4101-4106 live renderers consume spatial separation helpers',async()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileCorridorSeparationPresentation/);assert.match(e,/specialistDirectionalSeparationPresentation/);assert.match(s,/impactCorridorSeparationPresentation/);assert.match(g,/canonicalCorridorProtectionPresentation/);assert.match(g,/telegraphSafeLaneSeparationPresentation/);});
