import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/boss-anticipation-recovery-handoff-rendering.js');}
const input=(over={})=>({charge:.8,recovery:0,stagger:0,ringAlphaScale:1.1,bodyStrength:.8,...over});
test('phase 3537 active special charge owns boss anticipation while recovery is absent',async()=>{const m=await load();const p=m.bossAnticipationRecoveryHandoffPresentation(input(),false,false);assert.equal(p.owner,'anticipation');assert.ok(p.ringScale>.8);});
test('phase 3538 boss recovery takes ownership after charge collapses and retires the secondary ring first',async()=>{const m=await load();const p=m.bossAnticipationRecoveryHandoffPresentation(input({charge:.08,recovery:.8,bodyStrength:.08}),false,false);assert.equal(p.owner,'recovery');assert.ok(p.secondaryRingScale<p.bodyScale);});
test('phase 3539 stagger has highest visual ownership over both anticipation and recovery',async()=>{const m=await load();const p=m.bossAnticipationRecoveryHandoffPresentation(input({recovery:.5,stagger:.9}),false,false);assert.equal(p.owner,'stagger');assert.ok(p.ringScale<.45);assert.ok(p.bodyScale<.55);});
test('phase 3540 early recovery keeps a small primary ring tail but never a second full warning ring',async()=>{const m=await load();const p=m.bossAnticipationRecoveryHandoffPresentation(input({charge:.12,recovery:.35,bodyStrength:.12}),false,false);assert.ok(p.ringScale>0);assert.ok(p.secondaryRingScale<=.25);});
test('phase 3541 reduced flash lowers alpha scale without changing geometry ownership scales',async()=>{const m=await load();const a=m.bossAnticipationRecoveryHandoffPresentation(input(),false,false),b=m.bossAnticipationRecoveryHandoffPresentation(input(),false,true);assert.equal(a.ringScale,b.ringScale);assert.equal(a.bodyScale,b.bodyScale);assert.ok(b.alphaScale<a.alphaScale);});
test('phase 3542 live boss anticipation ring and body consume recovery handoff scales',async()=>{const s=source();assert.match(s,/bossAnticipationRecoveryHandoffPresentation/);assert.match(s,/bossAnticipationHandoff\.ringScale/);assert.match(s,/bossAnticipationHandoff\.bodyScale/);const a=await import('../dist/game/boss-anticipation-recovery-handoff-audit.js');const r=a.runBossAnticipationRecoveryHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
