import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-special-origin-handoff-rendering.ts',import.meta.url);
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-special-origin-handoff-rendering.js');}

test('phase 3051 boss special origin handoff module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceBossSpecialOriginHandoffState,'function');assert.equal(typeof mod.bossSpecialOriginHandoffPresentation,'function');});
test('phase 3052 newly summoned adds begin materialized at their own ground origin with locomotion suppressed',async()=>{const {advanceBossSpecialOriginHandoffState,bossSpecialOriginHandoffPresentation}=await loadModule();const s=advanceBossSpecialOriginHandoffState(undefined,{kind:'materialize',offsetX:0,offsetY:0},0,18,false);const p=bossSpecialOriginHandoffPresentation(s,false);assert.equal(s.kind,'materialize');assert.ok(p.shadowAlphaScale<.7);assert.ok(p.locomotionScale<.35);assert.equal(p.groundOffsetX,0);});
test('phase 3053 materialized add settles into ordinary ground ownership without a stale portal origin',async()=>{const {advanceBossSpecialOriginHandoffState,bossSpecialOriginHandoffPresentation}=await loadModule();let s=advanceBossSpecialOriginHandoffState(undefined,{kind:'materialize',offsetX:0,offsetY:0},0,18,false);for(let i=0;i<8;i++)s=advanceBossSpecialOriginHandoffState(s,null,.08,18,false);const p=bossSpecialOriginHandoffPresentation(s,false);assert.ok(s.strength<.08);assert.ok(p.shadowAlphaScale>.94);assert.ok(p.locomotionScale>.94);assert.ok(Math.abs(p.groundOffsetX)<.2);});
test('phase 3054 summon owner suppresses boss stale contact pulse without moving the boss ground origin',async()=>{const {advanceBossSpecialOriginHandoffState,bossSpecialOriginHandoffPresentation}=await loadModule();const s=advanceBossSpecialOriginHandoffState(undefined,{kind:'summon',offsetX:0,offsetY:0},0,34,false);const p=bossSpecialOriginHandoffPresentation(s,false);assert.equal(s.kind,'summon');assert.equal(p.groundOffsetX,0);assert.ok(p.contactPulseScale<.5);assert.ok(p.shadowAlphaScale>.7);});
test('phase 3055 teleport-style displacement keeps a bounded trailing ground origin and reduced motion tightens it',async()=>{const {advanceBossSpecialOriginHandoffState,bossSpecialOriginHandoffPresentation}=await loadModule();const full=advanceBossSpecialOriginHandoffState(undefined,{kind:'teleport',offsetX:-90,offsetY:28},0,36,false);const reduced=advanceBossSpecialOriginHandoffState(undefined,{kind:'teleport',offsetX:-90,offsetY:28},0,36,true);const pf=bossSpecialOriginHandoffPresentation(full,false),pr=bossSpecialOriginHandoffPresentation(reduced,true);assert.ok(pf.groundOffsetX<0&&Math.abs(pf.groundOffsetX)<=20);assert.ok(Math.abs(pr.groundOffsetX)<Math.abs(pf.groundOffsetX));assert.ok(pf.contactPulseScale<.3);});
test('phase 3056 boss summon dash and add render share special-origin state and audit stays presentation-only',async()=>{assert.match(enemySource,/bossSpecialOriginHandoff/);assert.match(enemySource,/advanceBossSpecialOriginHandoffState/);assert.match(enemySource,/bossSpecialOriginHandoffPresentation/);assert.match(enemySource,/kind:'materialize'/);assert.match(enemySource,/kind:'summon'/);assert.match(enemySource,/kind:'teleport'/);assert.match(enemySource,/const bossLocomotionOwnershipScale = bossGroundCue \? bossGroundCue\.locomotionScale : 1;/);assert.match(enemySource,/const bossShadowMotionScale = \(bossGroundCue \? bossGroundCue\.shadowMotionScale : 1\)\*bossGroundRebase\.shadowMotionScale;/);assert.equal(fs.existsSync(new URL('../src/game/boss-special-origin-handoff-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-special-origin-handoff-audit.js');const audit=mod.runBossSpecialOriginHandoffAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
