import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/projectile-trail-launch-handoff-rendering.ts',import.meta.url);const spellSource=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/projectile-trail-launch-handoff-rendering.js');}
test('phase 3093 projectile trail launch handoff module exists',async()=>{const m=await load();assert.equal(typeof m.projectileTrailLaunchHandoffPresentation,'function');});
test('phase 3094 trail head shares visual launch owner during convergence',async()=>{const {projectileTrailLaunchHandoffPresentation}=await load();const p=projectileTrailLaunchHandoffPresentation({gameplayPos:{x:100,y:80},velocity:{x:300,y:0},launchOffset:{x:-20,y:6},launchTtl:.1,launchMaxTtl:.1,radius:10},false);assert.equal(p.owner,'launch');assert.ok(p.head.x<100);assert.ok(Math.abs(p.head.y-86)<.01);});
test('phase 3095 trail tail extends backward from visual head rather than canonical origin',async()=>{const {projectileTrailLaunchHandoffPresentation}=await load();const p=projectileTrailLaunchHandoffPresentation({gameplayPos:{x:100,y:80},velocity:{x:300,y:0},launchOffset:{x:-18,y:0},launchTtl:.08,launchMaxTtl:.1,radius:10},false);assert.ok(p.tail.x<p.head.x);assert.equal(p.tail.y,p.head.y);assert.ok(p.length>=10&&p.length<=34);});
test('phase 3096 completed convergence returns canonical owner and canonical head',async()=>{const {projectileTrailLaunchHandoffPresentation}=await load();const p=projectileTrailLaunchHandoffPresentation({gameplayPos:{x:120,y:90},velocity:{x:0,y:300},launchOffset:{x:-16,y:5},launchTtl:0,launchMaxTtl:.1,radius:9},false);assert.equal(p.owner,'canonical');assert.deepEqual(p.head,{x:120,y:90});});
test('phase 3097 reduced motion shortens trail without changing owner semantics',async()=>{const {projectileTrailLaunchHandoffPresentation}=await load();const input={gameplayPos:{x:100,y:80},velocity:{x:210,y:150},launchOffset:{x:-18,y:4},launchTtl:.08,launchMaxTtl:.1,radius:9};const f=projectileTrailLaunchHandoffPresentation(input,false),r=projectileTrailLaunchHandoffPresentation(input,true);assert.equal(r.owner,f.owner);assert.ok(r.length<f.length);});
test('phase 3098 hero and enemy projectile renderers reuse launch metadata for trails and audit stays presentation only',async()=>{assert.match(spellSource,/projectileTrailLaunchHandoffPresentation/);assert.match(spellSource,/trail\.tail/);assert.match(enemySource,/projectileTrailLaunchHandoffPresentation/);assert.match(enemySource,/trail\.head/);assert.match(spellSource,/projectileTrailLaunchHandoffPresentation\([^;]+reducedMotion\)/s);assert.match(enemySource,/projectileTrailLaunchHandoffPresentation\([^;]+reducedMotion\)/s);assert.match(gameSource,/renderProjectiles\([^;]+reducedMotion\)/s);const a=await import('../dist/game/projectile-trail-launch-handoff-audit.js');const audit=a.runProjectileTrailLaunchHandoffAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
