import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-hazard-cleared-ground-memory-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-hazard-cleared-ground-memory-rendering.js');}
test('phase 3159 boss hazard cleared ground memory module exists',async()=>{const m=await load();assert.equal(typeof m.bossHazardClearedGroundMemoryPresentation,'function');});
test('phase 3160 cleared memory stays hidden while normal aftermath still owns the lane',async()=>{const {bossHazardClearedGroundMemoryPresentation}=await load();const p=bossHazardClearedGroundMemoryPresentation({memoryTtl:1.1,memoryMaxTtl:1.25,aftermathActive:true,nextHazardDistance:999,nextHazardTelegraph:0},false);assert.equal(p.owner,'hidden');assert.equal(p.clearedAlpha,0);});
test('phase 3161 memory becomes a low weight cleared-ground cue after aftermath retirement',async()=>{const {bossHazardClearedGroundMemoryPresentation}=await load();const p=bossHazardClearedGroundMemoryPresentation({memoryTtl:.38,memoryMaxTtl:1.25,aftermathActive:false,nextHazardDistance:999,nextHazardTelegraph:0},false);assert.equal(p.owner,'cleared');assert.ok(p.clearedAlpha>0&&p.clearedAlpha<=.2);assert.ok(p.radiusScale>=.96&&p.radiusScale<=1.08);});
test('phase 3162 nearby repeated hazard receives ownership and clears old safe-ground memory',async()=>{const {bossHazardClearedGroundMemoryPresentation}=await load();const p=bossHazardClearedGroundMemoryPresentation({memoryTtl:.42,memoryMaxTtl:1.25,aftermathActive:false,nextHazardDistance:62,nextHazardTelegraph:.72},false);assert.equal(p.owner,'telegraph');assert.equal(p.clearedAlpha,0);assert.ok(p.telegraphAlphaScale>1);});
test('phase 3163 reduced flash keeps cleared-ground memory subtle and handoff bounded',async()=>{const {bossHazardClearedGroundMemoryPresentation}=await load();const f=bossHazardClearedGroundMemoryPresentation({memoryTtl:.34,memoryMaxTtl:1.25,aftermathActive:false,nextHazardDistance:999,nextHazardTelegraph:0},false),r=bossHazardClearedGroundMemoryPresentation({memoryTtl:.34,memoryMaxTtl:1.25,aftermathActive:false,nextHazardDistance:999,nextHazardTelegraph:0},true);assert.equal(r.owner,'cleared');assert.ok(r.clearedAlpha<f.clearedAlpha);const h=bossHazardClearedGroundMemoryPresentation({memoryTtl:.34,memoryMaxTtl:1.25,aftermathActive:false,nextHazardDistance:50,nextHazardTelegraph:.8},true);assert.ok(h.telegraphAlphaScale<=1.06);});
test('phase 3164 live boss hazard expiry keeps short memory and hands it to repeated telegraphs with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/bossHazardClearedGroundMemory/);assert.match(s,/bossHazardClearedGroundMemoryPresentation/);assert.match(s,/queueBossHazardAftermathVfx/);assert.match(s,/telegraphAlphaScale/);const a=await import('../dist/game/boss-hazard-cleared-ground-memory-audit.js');const audit=a.runBossHazardClearedGroundMemoryAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
