import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const encounterSource=fs.readFileSync(new URL('../src/game/boss-encounters.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/boss-counterplay-reward-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/boss-counterplay-reward-vfx-assets.js');}
test('phase 2565 boss counterplay reward atlas covers six bosses x burst aura',async()=>{const mod=await load(),audit=mod.auditBossCounterplayRewardVfxAtlas();assert.equal(audit.archetypeCount,6);assert.equal(audit.stateCount,2);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.BOSS_COUNTERPLAY_REWARD_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:768,height:256});assert.ok(b.length>5000);});
test('phase 2566 final weakpoint break queues reward burst at actual completion center',()=>{assert.match(gameSource,/queueBossCounterplayRewardBurstVfx\(archetype,breakCenter\.x,breakCenter\.y\)/);assert.match(gameSource,/const finalBreak=completed&&previousDestroyed<total/);});
test('phase 2567 benefit aura is driven by actual boss counterplay modifiers not a fake timer',()=>{assert.match(gameSource,/bossCounterplayBenefitActive\(archetype,this\.bossEncounter\.modifiers\)/);assert.match(gameSource,/bossCounterplayRewardVfxSprite\(archetype,'aura'\)/);assert.doesNotMatch(gameSource,/bossCounterplayBenefitVfxUntilMs/);});
test('phase 2568 inferno benefit lifecycle remains the existing six second vulnerability timer',()=>{assert.match(encounterSource,/this\.vulnerabilityTimer = 6/);assert.match(encounterSource,/this\.vulnerabilityTimer = Math\.max\(0, this\.vulnerabilityTimer - Math\.max\(0, dt\)\)/);assert.match(gameSource,/bossCounterplayBenefitActive\(archetype,this\.bossEncounter\.modifiers\)/);assert.match(gameSource,/drawBossCounterplayRewardVfx/);});
test('phase 2569 reward burst queue is bounded resettable fail-open and reduced-flash capped',()=>{assert.match(gameSource,/bossCounterplayRewardBurstVfx\.length>8/);assert.match(gameSource,/this\.bossCounterplayRewardBurstVfx=\[\]/);assert.match(gameSource,/initializeBossCounterplayRewardVfxAtlas/);assert.match(gameSource,/this\.presentationSettings\.reducedFlash\?0\.36:0\.72/);});
test('phase 2570 counterplay reward audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/boss-counterplay-reward-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-counterplay-reward-vfx-audit.js'),audit=mod.runBossCounterplayRewardVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/bossCounterplayRewardVfxPassed/);assert.match(candidateSource,/bossCounterplayRewardVfxPassed/);assert.match(candidateSource,/boss-counterplay-reward-vfx/);});
