import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const spellSource=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/crowd-control-propagation-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/crowd-control-propagation-vfx-assets.js');}
test('phase 2559 crowd control propagation atlas covers four heroes x three control spells',async()=>{const mod=await load(),audit=mod.auditCrowdControlPropagationVfxAtlas();assert.equal(audit.heroCount,4);assert.equal(audit.kindCount,3);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.CROWD_CONTROL_PROPAGATION_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:512,height:384});assert.ok(b.length>5000);});
test('phase 2560 chain lightning overlays propagation on actual arc segments without changing jump budget',()=>{assert.match(spellSource,/crowdControlPropagationVfxSprite\(arc\.heroId,'chainLightning'\)/);assert.match(spellSource,/for\(let i=1;i<arc\.points\.length;i\+\+\)/);assert.match(spellSource,/chainJumpBudget\(tuning\.jumps \+ identity\.chainJumpBonus \+ evolution\.jumpBonus \+ fusion\.jumpBonus, world\.hero\.temporaryChainJumpBonus\)/);});
test('phase 2561 frost nova overlay expands using the existing nova radius and ttl',()=>{assert.match(spellSource,/crowdControlPropagationVfxSprite\(nova\.heroId,'frostNova'\)/);assert.match(spellSource,/const t = 1 - Math\.max\(0, nova\.ttl \/ 0\.34\)/);assert.match(spellSource,/nova\.radius \* t/);});
test('phase 2562 black hole pull-lock overlay anchors to the existing hole radius',()=>{assert.match(spellSource,/crowdControlPropagationVfxSprite\(hole\.heroId,'blackHole'\)/);assert.match(spellSource,/hole\.radius \* 2\.34/);assert.match(spellSource,/pullMultiplier: evolution\.pullMultiplier/);});
test('phase 2563 propagation atlas is game-loaded fail-open and reduced-flash aware',()=>{assert.match(gameSource,/initializeCrowdControlPropagationVfxAtlas/);assert.match(gameSource,/crowdControlPropagationVfxAtlasImage/);assert.match(gameSource,/this\.presentationSettings\.reducedFlash/);assert.match(spellSource,/reducedFlash \? 0\.32 : 0\.58/);});
test('phase 2564 propagation audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/crowd-control-propagation-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/crowd-control-propagation-vfx-audit.js'),audit=mod.runCrowdControlPropagationVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/crowdControlPropagationVfxPassed/);assert.match(candidateSource,/crowdControlPropagationVfxPassed/);assert.match(candidateSource,/crowd-control-propagation-vfx/);});
