import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/hero-projectile-launch-origin-rendering.ts',import.meta.url);const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const spellSource=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-projectile-launch-origin-rendering.js');}
test('phase 3075 hero projectile launch origin module exists',async()=>{const m=await load();assert.equal(typeof m.heroProjectileLaunchOriginPresentation,'function');assert.equal(typeof m.visualLaunchPosition,'function');});
test('phase 3076 normal cast launch follows body pose and facing with bounded muzzle distance',async()=>{const {heroProjectileLaunchOriginPresentation}=await load();const p=heroProjectileLaunchOriginPresentation({bodyOffsetX:8,bodyOffsetY:-5,facingX:1,facingY:0,radius:24,kind:'normal'},false);assert.equal(p.owner,'body-pose');assert.ok(p.originOffsetX>8);assert.ok(Math.abs(p.originOffsetX)<=30);assert.ok(Math.abs(p.originOffsetY)<=12);});
test('phase 3077 visual launch position converges to unchanged gameplay projectile position',async()=>{const {visualLaunchPosition}=await load();const a=visualLaunchPosition({x:100,y:80},{x:-14,y:5},.12,.12);const b=visualLaunchPosition({x:112,y:80},{x:-14,y:5},.03,.12);const c=visualLaunchPosition({x:120,y:80},{x:-14,y:5},0,.12);assert.ok(a.x<100);assert.ok(Math.abs(b.x-112)<Math.abs(a.x-100));assert.deepEqual(c,{x:120,y:80});});
test('phase 3078 ultimate launch keeps stronger pose ownership without changing gameplay target',async()=>{const {heroProjectileLaunchOriginPresentation}=await load();const n=heroProjectileLaunchOriginPresentation({bodyOffsetX:5,bodyOffsetY:-4,facingX:.8,facingY:.6,radius:24,kind:'normal'},false);const u=heroProjectileLaunchOriginPresentation({bodyOffsetX:5,bodyOffsetY:-4,facingX:.8,facingY:.6,radius:24,kind:'ultimate'},false);assert.ok(u.forwardDistance>n.forwardDistance);assert.ok(u.convergeSeconds>=n.convergeSeconds);assert.ok(Math.hypot(u.originOffsetX,u.originOffsetY)<=36);});
test('phase 3079 reduced motion tightens body offset and convergence while preserving facing owner',async()=>{const {heroProjectileLaunchOriginPresentation}=await load();const f=heroProjectileLaunchOriginPresentation({bodyOffsetX:10,bodyOffsetY:-8,facingX:0,facingY:1,radius:26,kind:'ultimate'},false);const r=heroProjectileLaunchOriginPresentation({bodyOffsetX:10,bodyOffsetY:-8,facingX:0,facingY:1,radius:26,kind:'ultimate'},true);assert.equal(r.owner,'body-pose');assert.ok(Math.abs(r.originOffsetX)<=Math.abs(f.originOffsetX));assert.ok(r.convergeSeconds<f.convergeSeconds);});
test('phase 3080 game caches final body offset and spells use visual-only launch origin with presentation-only audit',async()=>{assert.match(gameSource,/heroLastRenderedBodyOffset/);assert.match(gameSource,/visualBodyOffset:this\.heroLastRenderedBodyOffset/);assert.match(spellSource,/visualLaunchOffset/);assert.match(spellSource,/visualLaunchTtl/);assert.match(spellSource,/visualLaunchPosition/);assert.doesNotMatch(spellSource,/vel:\s*\{[^}]*visualLaunch/);const a=await import('../dist/game/hero-projectile-launch-origin-audit.js');const audit=a.runHeroProjectileLaunchOriginAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
