import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/hero-action-pose-handoff-rendering.js');}
const input=(over={})=>({owner:'cast',cast:.8,recovery:0,ultimateWindup:0,ultimateRelease:0,ultimateRecovery:0,hit:0,releaseAccent:.2,...over});
test('phase 3525 active ultimate handoff suppresses duplicate cast pose ownership',async()=>{const m=await load();const p=m.heroActionPoseHandoffPresentation(input({owner:'ultimate',cast:.55,ultimateWindup:.8}),false);assert.equal(p.owner,'ultimate');assert.ok(p.castPoseScale<.5);assert.ok(p.ultimatePoseScale>.8);});
test('phase 3526 recovery takes ownership without additive cast and recovery overlays peaking together',async()=>{const m=await load();const p=m.heroActionPoseHandoffPresentation(input({owner:'movement',cast:.15,recovery:.85}),false);assert.equal(p.owner,'recovery');assert.ok(p.castOverlayScale+p.recoverOverlayScale<=1.35);});
test('phase 3527 strong hit becomes presentation owner over decorative action pose layers',async()=>{const m=await load();const p=m.heroActionPoseHandoffPresentation(input({hit:.9}),false);assert.equal(p.owner,'hit');assert.ok(p.actionPoseScale<.45);});
test('phase 3528 ultimate release accent carries into early recovery without a second full release peak',async()=>{const m=await load();const p=m.heroActionPoseHandoffPresentation(input({owner:'movement',recovery:.45,ultimateRecovery:.35,releaseAccent:.9}),false);assert.equal(p.owner,'recovery');assert.ok(p.releaseCarry>0);assert.ok(p.releaseCarry<.7);});
test('phase 3529 reduced motion resolves directly to one owner with no additive carry motion',async()=>{const m=await load();const p=m.heroActionPoseHandoffPresentation(input({owner:'ultimate',cast:.5,ultimateWindup:.8,releaseAccent:.8}),true);assert.equal(p.owner,'ultimate');assert.equal(p.releaseCarry,0);assert.equal(p.singlePoseOwner,true);});
test('phase 3530 live hero pose emphasis consumes handoff scales before body and overlays draw',async()=>{const s=source();assert.match(s,/heroActionPoseHandoffPresentation/);assert.match(s,/heroActionPoseHandoff\.actionPoseScale/);assert.match(s,/heroActionPoseHandoff\.castOverlayScale/);const a=await import('../dist/game/hero-action-pose-handoff-audit.js');const r=a.runHeroActionPoseHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
