import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-rhythm-stagger-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now()+Math.random());}
test('Phase 4191 projectile secondary peaks separate by deterministic rhythm slot',async()=>{const {projectileThreatRhythmPresentation}=await load();const a=projectileThreatRhythmPresentation({phase:.5,stress:.8,critical:false,slot:0}),b=projectileThreatRhythmPresentation({phase:.5,stress:.8,critical:false,slot:1});assert.equal(a.primaryScale,1);assert.ok(a.secondaryScale>b.secondaryScale+.08);});
test('Phase 4192 impact rhythm keeps critical ownership while fill cadence yields',async()=>{const {impactThreatRhythmPresentation}=await load();const p=impactThreatRhythmPresentation({phase:.75,stress:1,critical:true,slot:2});assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale>=.5&&p.secondaryScale<=1);});
test('Phase 4193 hazard rhythm is bounded under high crowd stress',async()=>{const {hazardThreatRhythmPresentation}=await load();const p=hazardThreatRhythmPresentation({phase:.25,stress:1,critical:false,slot:3},false,true);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale>=0&&p.secondaryScale<=1);});
test('Phase 4194 safe lane rhythm never attenuates canonical path ownership',async()=>{const {safeLaneThreatRhythmPresentation}=await load();const p=safeLaneThreatRhythmPresentation({phase:.5,stress:1,critical:true,slot:0},false,true);assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);assert.ok(p.secondaryScale<=1);});
test('Phase 4195 specialist rhythm assignment is deterministic',async()=>{const {specialistThreatRhythmPresentation}=await load();const a=specialistThreatRhythmPresentation({phase:.37,stress:.7,critical:false,slot:13}),b=specialistThreatRhythmPresentation({phase:.37,stress:.7,critical:false,slot:13});assert.deepEqual(a,b);assert.equal(a.primaryScale,1);});
test('Phase 4196 dense rhythm budget caps simultaneous secondary peaks',async()=>{const {threatRhythmBudgetPresentation}=await load();const p=threatRhythmBudgetPresentation({activeCount:12,criticalCount:2,stress:1,safeLaneVisible:true});assert.equal(p.maxConcurrentPeaks,1);assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4191-4196 cross-family rhythm assigns distinct temporal ownership slots',async()=>{const m=await load();const input={phase:.5,stress:.9,critical:false,slot:0};const values=[m.projectileThreatRhythmPresentation(input),m.impactThreatRhythmPresentation(input),m.hazardThreatRhythmPresentation(input),m.safeLaneThreatRhythmPresentation(input),m.specialistThreatRhythmPresentation(input)];assert.equal(new Set(values.map((value)=>value.slot)).size,5);assert.ok(Math.max(...values.map((value)=>value.secondaryScale))-Math.min(...values.map((value)=>value.secondaryScale))>.2);});
test('Phase 4196 safe lane presence reserves global secondary rhythm budget',async()=>{const {threatRhythmBudgetPresentation}=await load();const base={activeCount:12,criticalCount:1,stress:.8};const absent=threatRhythmBudgetPresentation({...base,safeLaneVisible:false}),present=threatRhythmBudgetPresentation({...base,safeLaneVisible:true});assert.equal(present.safeLaneScale,1);assert.ok(present.secondaryScale<=absent.secondaryScale-.08);});
test('Phase 4191-4196 live renderers consume threat rhythm stagger helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileThreatRhythmPresentation/);assert.match(e,/specialistThreatRhythmPresentation/);assert.match(s,/impactThreatRhythmPresentation/);assert.match(g,/hazardThreatRhythmPresentation/);assert.match(g,/safeLaneThreatRhythmPresentation/);assert.match(e,/projectileRhythm\.secondaryScale/);assert.match(s,/impactRhythm\.secondaryScale/);});
