import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/hero-action-transition-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-action-transition-rendering.js');}

test('phase 2949 hero action transition module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceHeroActionTransitionState,'function');assert.equal(typeof mod.heroActionTransitionPresentation,'function');});
test('phase 2950 hit-to-cast transition retains bounded recoil instead of snapping to neutral',async()=>{const mod=await loadModule();let s=mod.advanceHeroActionTransitionState(undefined,'hit',0.016,false);s=mod.advanceHeroActionTransitionState(s,null,0.05,false);s=mod.advanceHeroActionTransitionState(s,'cast',0.016,false);const p=mod.heroActionTransitionPresentation(s,1,0,0.2,false);assert.equal(s.last,'cast');assert.ok(p.hitToCast>0.2);assert.ok(p.hitRecoilScale<1&&p.hitRecoilScale>=0.35);assert.ok(p.castContinuity>0.25);});
test('phase 2951 cast-to-evade transition suppresses recovery pop and carries escape direction',async()=>{const mod=await loadModule();let s=mod.advanceHeroActionTransitionState(undefined,'cast',0.016,false);s=mod.advanceHeroActionTransitionState(s,null,0.07,false);s=mod.advanceHeroActionTransitionState(s,'evade',0.016,false);const p=mod.heroActionTransitionPresentation(s,1,0,0.85,false);assert.equal(s.last,'evade');assert.ok(p.castToEvade>0.2);assert.ok(p.recoverSuppression>0.2);assert.ok(p.offsetX>0);assert.ok(p.evadeContinuity>0.4);});
test('phase 2952 rapid hit-cast-evade sequence stays within bounded body transform',async()=>{const mod=await loadModule();let s=mod.advanceHeroActionTransitionState(undefined,'hit',0.016,false);s=mod.advanceHeroActionTransitionState(s,'cast',0.04,false);s=mod.advanceHeroActionTransitionState(s,'evade',0.04,false);const p=mod.heroActionTransitionPresentation(s,0.8,0.6,1,false);assert.ok(Math.hypot(p.offsetX,p.offsetY)<=6.5);assert.ok(p.rotation<=0.16&&p.rotation>=-0.16);assert.ok(p.scaleX>=0.92&&p.scaleX<=1.08);assert.ok(p.scaleY>=0.92&&p.scaleY<=1.08);});
test('phase 2953 reduced motion preserves transition identity while compressing displacement',async()=>{const mod=await loadModule();let s=mod.advanceHeroActionTransitionState(undefined,'cast',0.016,false);s=mod.advanceHeroActionTransitionState(s,'evade',0.06,false);const full=mod.heroActionTransitionPresentation(s,1,0,0.8,false);const reduced=mod.heroActionTransitionPresentation(s,1,0,0.8,true);assert.equal(reduced.castToEvade,full.castToEvade);assert.equal(reduced.evadeContinuity,full.evadeContinuity);assert.ok(Math.abs(reduced.offsetX)<Math.abs(full.offsetX));assert.ok(Math.abs(reduced.rotation)<=Math.abs(full.rotation));});
test('phase 2954 game integrates hit cast evade transition events and deterministic audit stays presentation-only',async()=>{assert.match(gameSource,/heroActionTransitionState/);assert.match(gameSource,/advanceHeroActionTransitionState/);assert.match(gameSource,/heroActionTransitionPresentation/);assert.match(gameSource,/['"]hit['"]/);assert.match(gameSource,/['"]cast['"]/);assert.match(gameSource,/['"]evade['"]/);assert.equal(fs.existsSync(new URL('../src/game/hero-action-transition-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-action-transition-audit.js');const audit=mod.runHeroActionTransitionAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
