import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const url=new URL('../src/game/hero-cast-aim-hold-rendering.ts',import.meta.url);
async function load(){assert.equal(fs.existsSync(url),true);return import('../dist/game/hero-cast-aim-hold-rendering.js');}
test('phase 3399 hero cast aim hold module exists',async()=>{const m=await load();assert.equal(typeof m.advanceHeroCastAimHoldState,'function');assert.equal(typeof m.heroCastAimHoldPresentation,'function');});
test('phase 3400 a successful cast captures a normalized target-facing direction',async()=>{const m=await load();const s=m.advanceHeroCastAimHoldState(undefined,{x:3,y:4},0,false);assert.ok(Math.abs(Math.hypot(s.lockedX,s.lockedY)-1)<1e-6);assert.ok(s.hold>0);});
test('phase 3401 recovery keeps the cast direction when locomotion facing flips immediately',async()=>{const m=await load();let s=m.advanceHeroCastAimHoldState(undefined,{x:1,y:0},0,false);s=m.advanceHeroCastAimHoldState(s,null,.22,false);const p=m.heroCastAimHoldPresentation(s,-1,0,0,.95,false);assert.equal(p.owner,'cast');assert.ok(p.facingX>.35);assert.ok(p.retention>.4);});
test('phase 3402 the hold expires back to current facing without changing cast timing',async()=>{const m=await load();let s=m.advanceHeroCastAimHoldState(undefined,{x:1,y:0},0,false);s=m.advanceHeroCastAimHoldState(s,null,1,false);const p=m.heroCastAimHoldPresentation(s,-1,0,0,.8,false);assert.equal(p.owner,'current');assert.ok(p.facingX<-.99);assert.equal(p.retention,0);});
test('phase 3403 reduced motion preserves direction identity with a shorter bounded hold',async()=>{const m=await load();const full=m.advanceHeroCastAimHoldState(undefined,{x:0,y:1},0,false),reduced=m.advanceHeroCastAimHoldState(undefined,{x:0,y:1},0,true);assert.ok(reduced.hold>0&&reduced.hold<full.hold);const p=m.heroCastAimHoldPresentation(reduced,1,0,1,0,true);assert.ok(Number.isFinite(p.overlayAngle));assert.equal(p.owner,'cast');});
test('phase 3404 game wires cast trigger update reset and orientation through presentation-only audit',async()=>{assert.match(source,/heroCastAimHoldState/);assert.match(source,/advanceHeroCastAimHoldState/);assert.match(source,/heroCastAimHoldPresentation/);assert.match(source,/castAimHold\.facingX/);const a=await import('../dist/game/hero-cast-aim-hold-audit.js');const r=a.runHeroCastAimHoldAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
