import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-hazard-telegraph-handoff-rendering.ts',import.meta.url);const arenaSource=fs.readFileSync(new URL('../src/game/boss-arena.ts',import.meta.url),'utf8');const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-hazard-telegraph-handoff-rendering.js');}
test('phase 3105 boss hazard telegraph handoff module exists',async()=>{const m=await load();assert.equal(typeof m.bossHazardTelegraphHandoffPresentation,'function');});
test('phase 3106 fresh hazard starts with launch ownership but visible telegraph support',async()=>{const {bossHazardTelegraphHandoffPresentation}=await load();const p=bossHazardTelegraphHandoffPresentation({telegraph:1.05,launchTtl:.22,launchMaxTtl:.22},false);assert.equal(p.owner,'launch');assert.ok(p.launchCueAlpha>0);assert.ok(p.telegraphAlphaScale>0&&p.telegraphAlphaScale<1);});
test('phase 3107 launch cue fades as telegraph ownership rises',async()=>{const {bossHazardTelegraphHandoffPresentation}=await load();const a=bossHazardTelegraphHandoffPresentation({telegraph:.95,launchTtl:.18,launchMaxTtl:.22},false);const b=bossHazardTelegraphHandoffPresentation({telegraph:.86,launchTtl:.04,launchMaxTtl:.22},false);assert.ok(b.launchCueAlpha<a.launchCueAlpha);assert.ok(b.telegraphAlphaScale>a.telegraphAlphaScale);});
test('phase 3108 active hazard retires launch cue completely',async()=>{const {bossHazardTelegraphHandoffPresentation}=await load();const p=bossHazardTelegraphHandoffPresentation({telegraph:0,launchTtl:.08,launchMaxTtl:.22},false);assert.equal(p.owner,'active');assert.equal(p.launchCueAlpha,0);assert.equal(p.retireLaunchOrigin,true);});
test('phase 3109 reduced flash lowers launch cue without weakening final telegraph ownership',async()=>{const {bossHazardTelegraphHandoffPresentation}=await load();const f=bossHazardTelegraphHandoffPresentation({telegraph:.95,launchTtl:.16,launchMaxTtl:.22},false),r=bossHazardTelegraphHandoffPresentation({telegraph:.95,launchTtl:.16,launchMaxTtl:.22},true);assert.ok(r.launchCueAlpha<f.launchCueAlpha);assert.equal(r.telegraphAlphaScale,f.telegraphAlphaScale);});
test('phase 3110 arena retires stale launch origin and renderer arbitrates launch line against active telegraph with presentation-only audit',async()=>{assert.match(arenaSource,/delete h\.launchOrigin/);assert.match(arenaSource,/delete h\.launchTtl/);assert.match(gameSource,/bossHazardTelegraphHandoffPresentation/);assert.match(gameSource,/launchCueAlpha/);assert.match(gameSource,/telegraphAlphaScale/);const a=await import('../dist/game/boss-hazard-telegraph-handoff-audit.js');const audit=a.runBossHazardTelegraphHandoffAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
