import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/specialist-silhouette-crowd-budget-rendering.js');}
const input=(over={})=>({specialistCount:1,owner:'strike',hit:0,baseAlpha:.6,...over});
test('phase 3549 single specialist keeps full silhouette readability budget',async()=>{const m=await load();const p=m.specialistSilhouetteCrowdBudgetPresentation(input(),false);assert.equal(p.alphaScale,1);assert.equal(p.trailScale,1);});
test('phase 3550 crowded specialists reduce trail density before hiding current attack identity',async()=>{const m=await load();const solo=m.specialistSilhouetteCrowdBudgetPresentation(input(),false),crowd=m.specialistSilhouetteCrowdBudgetPresentation(input({specialistCount:8}),false);assert.ok(crowd.alphaScale<solo.alphaScale);assert.ok(crowd.trailScale<solo.trailScale);assert.ok(crowd.alphaScale>.35);});
test('phase 3551 strike owner retains more crowd visibility than resolve owner at equal density',async()=>{const m=await load();const strike=m.specialistSilhouetteCrowdBudgetPresentation(input({specialistCount:7,owner:'strike'}),false),resolve=m.specialistSilhouetteCrowdBudgetPresentation(input({specialistCount:7,owner:'resolve'}),false);assert.ok(strike.alphaScale>resolve.alphaScale);});
test('phase 3552 hit owner reduces decorative silhouette density most aggressively',async()=>{const m=await load();const p=m.specialistSilhouetteCrowdBudgetPresentation(input({specialistCount:6,owner:'hit',hit:.9}),false);assert.ok(p.alphaScale<.45);assert.ok(p.shapeScale<.8);});
test('phase 3553 reduced motion caps crowded trail distance while preserving finite owner visibility',async()=>{const m=await load();const p=m.specialistSilhouetteCrowdBudgetPresentation(input({specialistCount:9}),true);assert.ok(p.trailScale<=.5);assert.ok(p.alphaScale>0);});
test('phase 3554 live enemy render computes specialist count once and applies crowd budget to silhouettes',async()=>{const s=source();assert.match(s,/activeSpecialistCount/);assert.match(s,/specialistSilhouetteCrowdBudgetPresentation/);assert.match(s,/specialistCrowdBudget\.alphaScale/);const a=await import('../dist/game/specialist-silhouette-crowd-budget-audit.js');const r=a.runSpecialistSilhouetteCrowdBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
