import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/projectile-threat-position-handoff-rendering.ts',import.meta.url);const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const threatSource=()=>fs.readFileSync(new URL('../src/game/projectile-threat-visibility.ts',import.meta.url),'utf8');const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/projectile-threat-position-handoff-rendering.js');}
test('phase 3117 projectile threat position handoff module exists',async()=>{const m=await load();assert.equal(typeof m.projectileThreatPositionHandoff,'function');});
test('phase 3118 launch convergence threat cue follows visual projectile position',async()=>{const {projectileThreatPositionHandoff}=await load();const p=projectileThreatPositionHandoff({gameplayPos:{x:100,y:80},launchOffset:{x:-20,y:6},launchTtl:.1,launchMaxTtl:.1},false);assert.equal(p.owner,'launch');assert.ok(p.pos.x<100);assert.ok(p.pos.y>80);});
test('phase 3119 completed convergence hands threat tracking back to canonical position',async()=>{const {projectileThreatPositionHandoff}=await load();const p=projectileThreatPositionHandoff({gameplayPos:{x:100,y:80},launchOffset:{x:-20,y:6},launchTtl:0,launchMaxTtl:.1},false);assert.equal(p.owner,'canonical');assert.deepEqual(p.pos,{x:100,y:80});});
test('phase 3120 reduced motion threat position matches the already-compressed live visual launch offset',async()=>{const {projectileThreatPositionHandoff}=await load();const input={gameplayPos:{x:100,y:80},launchOffset:{x:-18,y:6},launchTtl:.08,launchMaxTtl:.1};const r=projectileThreatPositionHandoff(input,true),blend=.8*.8;assert.equal(r.owner,'launch');assert.ok(Math.abs(r.pos.x-(100-18*blend))<.001);assert.ok(Math.abs(r.pos.y-(80+6*blend))<.001);});
test('phase 3121 threat scoring can consume visualPos while canonical projectile pos remains available',()=>{const s=threatSource();assert.match(s,/visualPos\?:Vec2/);assert.match(s,/const threatPos=p\.visualPos\?\?p\.pos/);});
test('phase 3122 enemy threat views and both world/edge cues use visual threat position with presentation-only audit',async()=>{const e=enemySource(),g=gameSource();assert.match(e,/projectileThreatPositionHandoff/);assert.match(e,/visualPos:/);assert.match(g,/p\.visualPos\?\?p\.pos/);assert.match(g,/projectile\.visualPos\?\?projectile\.pos/);const a=await import('../dist/game/projectile-threat-position-handoff-audit.js');const audit=a.runProjectileThreatPositionHandoffAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
