import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const u=new URL('../src/game/secondary-impact-lineage-label-placement-hold-rendering.ts',import.meta.url);const spells=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');async function load(){assert.equal(fs.existsSync(u),true);return import('../dist/game/secondary-impact-lineage-label-placement-hold-rendering.js');}
const p=(x,y,visible=true)=>({visible,pos:{x,y},presentationOnly:true});
test('phase 3261 secondary label placement hold module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactLineageHeldPlacement,'function');});
test('phase 3262 first visible placement is adopted immediately',async()=>{const m=await load();let mem=[];let r=m.secondaryImpactLineageHeldPlacement(mem,'lineage-1',p(300,260),[],[],1280,800);mem=r.memory;assert.deepEqual(r.placement.pos,{x:300,y:260});assert.equal(mem.length,1);});
test('phase 3263 moving primary blockers do not jitter a still-clean held label slot',async()=>{const m=await load();let r=m.secondaryImpactLineageHeldPlacement([],'lineage-1',p(300,260),[],[],1280,800);let mem=m.advanceSecondaryImpactLineageLabelPlacementHold(r.memory,.03);r=m.secondaryImpactLineageHeldPlacement(mem,'lineage-1',p(340,286),[{x:380,y:286}],[],1280,800);assert.deepEqual(r.placement.pos,{x:300,y:260});});
test('phase 3264 blocked held slot yields immediately to a clean fallback instead of overlapping',async()=>{const m=await load();let r=m.secondaryImpactLineageHeldPlacement([],'lineage-1',p(300,260),[],[],1280,800);r=m.secondaryImpactLineageHeldPlacement(r.memory,'lineage-1',p(340,286),[{x:300,y:260}],[],1280,800);assert.deepEqual(r.placement.pos,{x:340,y:286});});
test('phase 3265 expired hold adopts a new fallback and hidden fallback never resurrects stale text',async()=>{const m=await load();let r=m.secondaryImpactLineageHeldPlacement([],'lineage-1',p(300,260),[],[],1280,800);let mem=m.advanceSecondaryImpactLineageLabelPlacementHold(r.memory,m.SECONDARY_IMPACT_LABEL_PLACEMENT_HOLD_SECONDS*1.2);r=m.secondaryImpactLineageHeldPlacement(mem,'lineage-1',p(340,286),[],[],1280,800);assert.deepEqual(r.placement.pos,{x:340,y:286});r=m.secondaryImpactLineageHeldPlacement(r.memory,'lineage-1',p(0,0,false),[],[],1280,800);assert.equal(r.placement.visible,false);});
test('phase 3266 SpellSystem resets advances and consumes placement hold as presentation-only memory',async()=>{const s=spells();assert.match(s,/secondaryImpactLineageLabelPlacementHold/);assert.match(s,/advanceSecondaryImpactLineageLabelPlacementHold/);assert.match(s,/secondaryImpactLineageHeldPlacement/);const a=await import('../dist/game/secondary-impact-lineage-label-placement-hold-audit.js');const r=a.runSecondaryImpactLineageLabelPlacementHoldAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.passed,true);});
