import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const terrainSource=fs.readFileSync(new URL('../src/game/terrain.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/crystal-interaction-lifecycle-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/crystal-interaction-lifecycle-vfx-assets.js');}

test('phase 2511 crystal lifecycle atlas covers three maps x four interaction states',async()=>{const mod=await load(),audit=mod.auditCrystalInteractionLifecycleVfxAtlas();assert.equal(audit.mapCount,3);assert.equal(audit.stateCount,4);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.CRYSTAL_INTERACTION_LIFECYCLE_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:384,height:512});assert.ok(b.length>6000);});
test('phase 2512 charging crystal reads existing charge ratio and adds image cue only after magic contact',()=>{assert.match(gameSource,/crystal\.charge\s*\/\s*Math\.max\(1,crystal\.threshold\)/);assert.match(gameSource,/crystalInteractionLifecycleVfxSprite\(mapId,'charging'\)/);assert.match(terrainSource,/crystal\.charge \+= strength/);});
test('phase 2513 primed crystal uses a high charge threshold without changing blast threshold',()=>{assert.match(gameSource,/chargeRatio >= 0\.7/);assert.match(gameSource,/crystalInteractionLifecycleVfxSprite\(mapId,'primed'\)/);assert.match(terrainSource,/if \(crystal\.charge >= crystal\.threshold\) crystal\.blastPending = true/);});
test('phase 2514 crystal blast transitions into bounded blast afterglow queue from existing presentation event',()=>{assert.match(gameSource,/crystalInteractionLifecycleVfx/);assert.match(gameSource,/event\.kind==='crystalBlast'/);assert.match(gameSource,/crystalInteractionLifecycleVfx\.length>12/);assert.match(gameSource,/state=progress<0\.45\?'blast':'afterglow'/);assert.match(gameSource,/this\.crystalInteractionLifecycleVfx = \[\]/);});
test('phase 2515 crystal lifecycle atlas loads independently while legacy destruction effects remain',()=>{assert.match(gameSource,/initializeCrystalInteractionLifecycleVfxAtlas/);assert.match(gameSource,/crystalInteractionLifecycleVfxAtlasImage/);assert.match(gameSource,/environmentDestructionVfxDescriptor\(this\.terrain\.currentLayout\.id,'crystalBlast'/);});
test('phase 2516 crystal lifecycle audit is release-bound deterministic and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/crystal-interaction-lifecycle-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/crystal-interaction-lifecycle-vfx-audit.js'),audit=mod.runCrystalInteractionLifecycleVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/crystalInteractionLifecycleVfxPassed/);assert.match(candidateSource,/crystalInteractionLifecycleVfxPassed/);assert.match(candidateSource,/crystal-interaction-lifecycle-vfx/);});
