import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/boss-ground-cue-arbitration-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-ground-cue-arbitration-rendering.js');}

test('phase 3015 boss ground cue arbitration module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.bossGroundCueArbitrationPresentation,'function');});
test('phase 3016 normal boss locomotion keeps body shadow and contact pulse in the same ownership lane',async()=>{const mod=await loadModule();const p=mod.bossGroundCueArbitrationPresentation(2,{motion:.8,settle:.2,recovery:0,stagger:0,specialTimer:4},false);assert.equal(p.owner,'locomotion');assert.equal(p.locomotionScale,1);assert.equal(p.shadowMotionScale,1);assert.equal(p.contactPulseScale,1);});
test('phase 3017 special telegraph freezes conflicting ground settle cues before the attack',async()=>{const mod=await loadModule();const p=mod.bossGroundCueArbitrationPresentation(3,{motion:.5,settle:.8,recovery:.3,stagger:.7,specialTimer:.6},false);assert.equal(p.owner,'telegraph');assert.ok(p.locomotionScale<.35);assert.ok(p.contactPulseScale<=.08);assert.ok(p.locomotionShadowBoostScale<.35);});
test('phase 3018 special recovery transfers weight into the shadow without replaying locomotion contact pulse',async()=>{const mod=await loadModule();const p=mod.bossGroundCueArbitrationPresentation(2,{motion:.3,settle:.7,recovery:.9,stagger:.5,specialTimer:4},false);assert.equal(p.owner,'recovery');assert.ok(p.recoveryShadowBoostScale>.8);assert.ok(p.contactPulseScale<.4);assert.ok(p.locomotionScale<.6);});
test('phase 3019 heavy stagger keeps a grounded shadow and reduced motion preserves ownership',async()=>{const mod=await loadModule();const full=mod.bossGroundCueArbitrationPresentation(1,{motion:.55,settle:.25,recovery:.04,stagger:.95,specialTimer:4},false);const reduced=mod.bossGroundCueArbitrationPresentation(1,{motion:.55,settle:.25,recovery:.04,stagger:.95,specialTimer:4},true);assert.equal(full.owner,'stagger');assert.equal(reduced.owner,'stagger');assert.ok(full.shadowMotionScale<.55);assert.ok(full.contactPulseScale<.6);assert.ok(reduced.locomotionScale<=full.locomotionScale);});
test('phase 3020 boss render applies ground cue arbitration and audit stays presentation-only',async()=>{assert.match(enemySource,/bossGroundCueArbitrationPresentation/);assert.match(enemySource,/bossGroundCue\.locomotionScale/);assert.match(enemySource,/bossGroundCue\.shadowMotionScale/);assert.match(enemySource,/bossGroundCue\.contactPulseScale/);assert.match(enemySource,/bossGroundCue\.recoveryShadowBoostScale/);assert.equal(fs.existsSync(new URL('../src/game/boss-ground-cue-arbitration-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-ground-cue-arbitration-audit.js');const audit=mod.runBossGroundCueArbitrationAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
