import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const spellSource=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
const terrainSource=fs.readFileSync(new URL('../src/game/terrain.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/enemy-finisher-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/enemy-finisher-vfx-assets.js');}

test('phase 2541 enemy finisher atlas covers six kill sources x burst afterglow',async()=>{const mod=await load(),audit=mod.auditEnemyFinisherVfxAtlas();assert.equal(audit.sourceCount,6);assert.equal(audit.stateCount,2);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.ENEMY_FINISHER_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:768,height:256});assert.ok(b.length>5000);});
test('phase 2542 enemy death event records presentation-only visual source without changing damage math',()=>{assert.match(enemySource,/export type EnemyDeathVisualSource='normal'\|'explosion'\|'freeze'\|'ultimate'\|'finalForm'\|'fusion'/);assert.match(enemySource,/visualSource\?:EnemyDeathVisualSource/);assert.match(enemySource,/damage\(enemy: Enemy, amount: number, source\?: Vec2, visualSource:EnemyDeathVisualSource='normal'\)/);assert.match(enemySource,/enemy\.hp -= remaining \* \(enemy\.damageTakenMultiplier \?\? 1\) \* bossEncounterMultiplier/);});
test('phase 2543 spell terrain and fusion paths label actual finisher sources',()=>{assert.match(spellSource,/'freeze'/);assert.match(spellSource,/'ultimate'/);assert.match(terrainSource,/'explosion'/);assert.match(gameSource,/this\.enemies\.damage\(enemy, damage, origin,'fusion'\)/);assert.match(gameSource,/this\.enemies\.damage\(enemy, baseDamage\)/);assert.match(gameSource,/markLastDeathVisualSource\('finalForm'\)/);});
test('phase 2544 death processing queues finisher burst then afterglow at the actual death position',()=>{assert.match(gameSource,/queueEnemyFinisherVfx\(death\.visualSource\?\?'normal',death\.x,death\.y,death\.type\)/);assert.match(gameSource,/progress<0\.38\?'burst':'afterglow'/);assert.match(gameSource,/enemyFinisherVfxSprite\(cue\.source,state\)/);});
test('phase 2545 enemy finisher queue is bounded resettable and old death fallback remains',()=>{assert.match(gameSource,/enemyFinisherVfx\.length>24/);assert.match(gameSource,/this\.enemyFinisherVfx=\[\]/);assert.match(gameSource,/this\.emitDeathPresentation\(death\)/);assert.match(gameSource,/enemyCombatVfxSprite\(burst\.type, 'death'\)/);});
test('phase 2546 enemy finisher audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/enemy-finisher-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/enemy-finisher-vfx-audit.js'),audit=mod.runEnemyFinisherVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/enemyFinisherVfxPassed/);assert.match(candidateSource,/enemyFinisherVfxPassed/);assert.match(candidateSource,/enemy-finisher-vfx/);});
