import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-hazard-aftermath-terrain-retirement-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-hazard-aftermath-terrain-retirement-rendering.js');}
test('phase 3141 boss hazard aftermath terrain retirement module exists',async()=>{const m=await load();assert.equal(typeof m.bossHazardAftermathTerrainRetirementPresentation,'function');});
test('phase 3142 fresh aftermath owns the cleared ground immediately after expiry',async()=>{const {bossHazardAftermathTerrainRetirementPresentation}=await load();const p=bossHazardAftermathTerrainRetirementPresentation({aftermathTtl:.72,aftermathMaxTtl:.78,nextHazardDistance:999,nextHazardTelegraph:0},false);assert.equal(p.owner,'aftermath');assert.ok(p.aftermathAlphaScale>.5);});
test('phase 3143 late aftermath retires into low terrain ambience',async()=>{const {bossHazardAftermathTerrainRetirementPresentation}=await load();const p=bossHazardAftermathTerrainRetirementPresentation({aftermathTtl:.18,aftermathMaxTtl:.78,nextHazardDistance:999,nextHazardTelegraph:0},false);assert.equal(p.owner,'terrain');assert.ok(p.terrainAlphaScale>0);assert.ok(p.aftermathAlphaScale<.35);});
test('phase 3144 nearby next telegraph suppresses old aftermath ownership',async()=>{const {bossHazardAftermathTerrainRetirementPresentation}=await load();const p=bossHazardAftermathTerrainRetirementPresentation({aftermathTtl:.44,aftermathMaxTtl:.78,nextHazardDistance:54,nextHazardTelegraph:.7},false);assert.equal(p.owner,'retired');assert.ok(p.aftermathAlphaScale<=.08);});
test('phase 3145 reduced flash keeps terrain ambience bounded',async()=>{const {bossHazardAftermathTerrainRetirementPresentation}=await load();const f=bossHazardAftermathTerrainRetirementPresentation({aftermathTtl:.14,aftermathMaxTtl:.78,nextHazardDistance:999,nextHazardTelegraph:0},false),r=bossHazardAftermathTerrainRetirementPresentation({aftermathTtl:.14,aftermathMaxTtl:.78,nextHazardDistance:999,nextHazardTelegraph:0},true);assert.equal(r.owner,'terrain');assert.ok(r.terrainAlphaScale<f.terrainAlphaScale);});
test('phase 3146 live aftermath renderer checks current hazards before drawing and audit stays presentation only',async()=>{const s=gameSource();assert.match(s,/bossHazardAftermathTerrainRetirementPresentation/);assert.match(s,/this\.bossArena\.hazards/);assert.match(s,/terrainAlphaScale/);const a=await import('../dist/game/boss-hazard-aftermath-terrain-retirement-audit.js');const audit=a.runBossHazardAftermathTerrainRetirementAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
