import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/safe-lane-gap-feather-rendering.js');}
const route={from:{x:100,y:100},to:{x:500,y:100}};
test('phase 3465 route without a hazard gap remains one unbroken safe-lane body segment',async()=>{const m=await load();const p=m.safeLaneGapFeatherPresentation({...route,gap:null},false);assert.equal(p.gapApplied,false);assert.equal(p.bodySegments.length,1);assert.equal(p.featherSegments.length,0);});
test('phase 3466 hazard gap trims solid lane body before fading toward both gap edges',async()=>{const m=await load();const p=m.safeLaneGapFeatherPresentation({...route,gap:{start:.4,end:.6}},false);assert.equal(p.gapApplied,true);assert.equal(p.bodySegments.length,2);assert.ok(p.bodySegments[0].to.x<260);assert.ok(p.bodySegments[1].from.x>340);assert.ok(p.featherSegments.length>=4);});
test('phase 3467 feather opacity falls toward the gap instead of ending at one hard alpha step',async()=>{const m=await load();const p=m.safeLaneGapFeatherPresentation({...route,gap:{start:.35,end:.65}},false);const left=p.featherSegments.filter(s=>s.side==='start');assert.ok(left.length>=2);assert.ok(left[0].alphaScale>left.at(-1).alphaScale);});
test('phase 3468 destination locator remains authoritative even when the full center of the path is feathered out',async()=>{const m=await load();const p=m.safeLaneGapFeatherPresentation({...route,gap:{start:.05,end:.95}},false);assert.equal(p.locatorVisible,true);assert.ok(p.bodySegments.length>=1);});
test('phase 3469 reduced flash lowers feather alpha without widening or moving the navigation gap',async()=>{const m=await load();const a=m.safeLaneGapFeatherPresentation({...route,gap:{start:.4,end:.6}},false),b=m.safeLaneGapFeatherPresentation({...route,gap:{start:.4,end:.6}},true);assert.deepEqual(a.bodySegments,b.bodySegments);assert.equal(a.featherSegments.length,b.featherSegments.length);assert.ok(b.featherSegments[0].alphaScale<a.featherSegments[0].alphaScale);});
test('phase 3470 live safe-lane renders feather segments separately and preserves locator ownership',async()=>{const modSource=fs.readFileSync(new URL('../src/game/safe-lane-gap-feather-rendering.ts',import.meta.url),'utf8');assert.match(source,/safeLaneGapFeatherPresentation/);assert.match(source,/safeLaneGapFeather\.featherSegments/);assert.match(source,/safeLaneGapFeather\.locatorVisible/);assert.doesNotMatch(modSource,/damage|cooldown|hero\.pos\s*=/i);const a=await import('../dist/game/safe-lane-gap-feather-audit.js');const r=a.runSafeLaneGapFeatherAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
