import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import { heroActionLaunchOriginCoherencePresentation } from '../dist/game/hero-action-launch-origin-coherence-rendering.js';

test('cast owner uses retained body facing over divergent movement facing',()=>{const p=heroActionLaunchOriginCoherencePresentation({owner:'cast',bodyOffsetX:8,bodyOffsetY:-4,bodyFacingX:-1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:22,poseStrength:.8,kind:'normal'},false);assert.ok(p.facingX<-.95);assert.equal(p.owner,'action-pose');});
test('movement owner follows movement facing',()=>{const p=heroActionLaunchOriginCoherencePresentation({owner:'movement',bodyOffsetX:1,bodyOffsetY:0,bodyFacingX:-1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:22,poseStrength:0,kind:'normal'},false);assert.ok(p.facingX>.95);});
test('ultimate can lead farther than normal without exceeding bound',()=>{const n=heroActionLaunchOriginCoherencePresentation({owner:'cast',bodyOffsetX:7,bodyOffsetY:-3,bodyFacingX:1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:24,poseStrength:.9,kind:'normal'},false),u=heroActionLaunchOriginCoherencePresentation({owner:'ultimate',bodyOffsetX:7,bodyOffsetY:-3,bodyFacingX:1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:24,poseStrength:.9,kind:'ultimate'},false);assert.ok(u.forwardDistance>n.forwardDistance);assert.ok(Math.hypot(u.originOffsetX,u.originOffsetY)<=38.001);});
test('pose strength contributes bounded body-follow offset',()=>{const a=heroActionLaunchOriginCoherencePresentation({owner:'cast',bodyOffsetX:10,bodyOffsetY:0,bodyFacingX:1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:22,poseStrength:0,kind:'normal'},false),b=heroActionLaunchOriginCoherencePresentation({owner:'cast',bodyOffsetX:10,bodyOffsetY:0,bodyFacingX:1,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:22,poseStrength:1,kind:'normal'},false);assert.ok(b.bodyFollow>=a.bodyFollow);assert.ok(b.bodyFollow<=1);});
test('reduced motion reduces displacement while preserving facing owner',()=>{const f=heroActionLaunchOriginCoherencePresentation({owner:'ultimate',bodyOffsetX:12,bodyOffsetY:-8,bodyFacingX:0,bodyFacingY:-1,movementFacingX:1,movementFacingY:0,radius:28,poseStrength:1,kind:'ultimate'},false),r=heroActionLaunchOriginCoherencePresentation({owner:'ultimate',bodyOffsetX:12,bodyOffsetY:-8,bodyFacingX:0,bodyFacingY:-1,movementFacingX:1,movementFacingY:0,radius:28,poseStrength:1,kind:'ultimate'},true);assert.ok(Math.hypot(r.originOffsetX,r.originOffsetY)<Math.hypot(f.originOffsetX,f.originOffsetY));assert.ok(r.facingY<-.95);});
test('presentation is finite and wired into live spell launch',()=>{const p=heroActionLaunchOriginCoherencePresentation({owner:'recovery',bodyOffsetX:NaN,bodyOffsetY:Infinity,bodyFacingX:0,bodyFacingY:0,movementFacingX:1,movementFacingY:0,radius:999,poseStrength:2,kind:'normal'},false);assert.ok(Number.isFinite(p.originOffsetX)&&Number.isFinite(p.originOffsetY));assert.equal(p.presentationOnly,true);const game=fs.readFileSync('src/game/game.ts','utf8'),spells=fs.readFileSync('src/game/spells.ts','utf8');assert.match(game,/heroLastRenderedActionFacing/);assert.match(spells,/heroActionLaunchOriginCoherencePresentation/);});
