import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-boss-focus-corridor-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4131 boss telegraph corridor reserves edge authority',async()=>{const {bossTelegraphFocusCorridorPresentation}=await load();const p=bossTelegraphFocusCorridorPresentation({active:true,critical:true,overlap:1,crowd:1},false);assert.ok(p.edgeAlphaScale>=.96);assert.ok(p.secondaryScale<1);});
test('Phase 4132 boss projectile arrival keeps projectile body canonical',async()=>{const {bossProjectileFocusCorridorPresentation}=await load();const p=bossProjectileFocusCorridorPresentation({critical:true,laneProximity:1,crowd:1},false,false);assert.equal(p.bodyScale,1);assert.ok(p.trailScale>=.78);});
test('Phase 4133 boss-zone impacts retire fill before edge',async()=>{const {bossImpactFocusCorridorPresentation}=await load();const p=bossImpactFocusCorridorPresentation({bossProximity:1,crowd:1,critical:false},false);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);});
test('Phase 4134 safe lane remains readable during boss focus',async()=>{const {bossSafeLaneFocusCorridorPresentation}=await load();const p=bossSafeLaneFocusCorridorPresentation({visible:true,confidence:.9,bossPressure:1,critical:true},false);assert.ok(p.pathAlphaFloor>=.94);assert.ok(p.safeLaneScale>=1);});
test('Phase 4135 specialist secondary layers yield near boss focus',async()=>{const {bossSpecialistFocusCorridorPresentation}=await load();const p=bossSpecialistFocusCorridorPresentation({bossProximity:1,owner:'attack',critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4136 unified boss focus budget preserves canonical and telegraph',async()=>{const {bossFocusCorridorBudgetPresentation}=await load();const p=bossFocusCorridorBudgetPresentation({bossActive:true,criticalCount:2,projectileCount:10,impactCount:7,hazardCount:5,silhouetteCount:4,safeLaneVisible:true},false,false);assert.equal(p.canonicalScale,1);assert.equal(p.telegraphEdgeScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4131-4136 live renderers consume boss focus helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/bossProjectileFocusCorridorPresentation/);assert.match(e,/bossSpecialistFocusCorridorPresentation/);assert.match(s,/bossImpactFocusCorridorPresentation/);assert.match(g,/bossTelegraphFocusCorridorPresentation/);assert.match(g,/bossSafeLaneFocusCorridorPresentation/);});
