import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const game=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const freeze=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');const candidate=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');const exists=fs.existsSync(new URL('../dist/game/boss-safe-response-window-confirmation.js',import.meta.url));const mod=exists?await import('../dist/game/boss-safe-response-window-confirmation.js'):null;
const safe={bossId:7,currentCycle:4,ackBossId:7,ackCycle:3,specialTimer:2.1,heroCritical:false,coreCritical:false,damageSeverity:null,dangerProjectileCount:0};
test('phase 2655 safe response confirms only after the acknowledged boss cycle advances',()=>{assert.ok(mod);if(!mod)return;assert.equal(mod.bossSafeResponseWindowConfirmation(safe).confirmed,true);assert.equal(mod.bossSafeResponseWindowConfirmation({...safe,currentCycle:3}).confirmed,false);});
test('phase 2656 acknowledgement must belong to the same boss and immediately previous cycle',()=>{assert.ok(mod);if(!mod)return;assert.equal(mod.bossSafeResponseWindowConfirmation({...safe,ackBossId:8}).confirmed,false);assert.equal(mod.bossSafeResponseWindowConfirmation({...safe,ackCycle:2}).confirmed,false);});
test('phase 2657 confirmation refuses critical health heavy damage and dangerous incoming projectiles',()=>{assert.ok(mod);if(!mod)return;for(const patch of [{heroCritical:true},{coreCritical:true},{damageSeverity:'critical'},{damageSeverity:'heavy'},{dangerProjectileCount:1}])assert.equal(mod.bossSafeResponseWindowConfirmation({...safe,...patch}).confirmed,false);});
test('phase 2658 confirmation requires a genuinely reset special timer and makes no global-safety claim',()=>{assert.ok(mod);if(!mod)return;assert.equal(mod.bossSafeResponseWindowConfirmation({...safe,specialTimer:.9}).confirmed,false);const r=mod.bossSafeResponseWindowConfirmation(safe);assert.equal(r.claimsGlobalSafety,false);assert.ok(r.visualSeconds>0&&r.visualSeconds<1);});
test('phase 2659 game latches one brief confirmation per boss cycle and clears it on boss loss or change',()=>{assert.match(game,/bossSafeResponseWindowUntil/);assert.match(game,/bossSafeResponseBossId/);assert.match(game,/bossSafeResponseCycle/);assert.match(game,/updateBossSafeResponseWindowConfirmation\(\)/);assert.match(game,/dangerProjectileCues/);assert.match(game,/drawBossSafeResponseWindowConfirmation\(ctx\)/);assert.match(game,/대응 여유/);});
test('phase 2660 boss safe-window audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/boss-safe-response-window-confirmation-audit.ts',import.meta.url)),true);if(!fs.existsSync(new URL('../dist/game/boss-safe-response-window-confirmation-audit.js',import.meta.url)))return;const a=(await import('../dist/game/boss-safe-response-window-confirmation-audit.js')).runBossSafeResponseWindowConfirmationAudit();assert.equal(a.samples.length,64);assert.equal(a.actionCount,9);assert.equal(a.presentationOnly,true);assert.equal(a.gameplayFormulaMutation,false);assert.equal(a.snapshotSchemaMutation,false);assert.equal(a.passed,true);assert.match(freeze,/bossSafeResponseWindowConfirmationPassed/);assert.match(candidate,/bossSafeResponseWindowConfirmationPassed/);assert.match(candidate,/boss-safe-response-window-confirmation/);});
