import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-mixed-pressure-guard-arbitration-rendering.ts',import.meta.url);const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-mixed-pressure-guard-arbitration-rendering.js');}
test('phase 3183 core mixed-pressure guard arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.advanceCoreMixedPressureGuardArbitration,'function');});
test('phase 3184 projectile-only pressure owns core guard highlight',async()=>{const m=await load();const s=m.advanceCoreMixedPressureGuardArbitration(m.createCoreMixedPressureGuardArbitrationState(),{projectileStrength:.78,contactStrength:0},.016);const p=m.coreMixedPressureGuardArbitrationPresentation(s,false);assert.equal(s.owner,'projectile');assert.equal(p.projectileAlphaScale,1);assert.ok(p.contactAlphaScale<=.18);});
test('phase 3185 contact-only pressure owns core guard highlight',async()=>{const m=await load();const s=m.advanceCoreMixedPressureGuardArbitration(m.createCoreMixedPressureGuardArbitrationState(),{projectileStrength:0,contactStrength:.74},.016);const p=m.coreMixedPressureGuardArbitrationPresentation(s,false);assert.equal(s.owner,'contact');assert.equal(p.contactAlphaScale,1);assert.ok(p.projectileAlphaScale<=.18);});
test('phase 3186 mixed pressure suppresses secondary owner instead of double highlighting',async()=>{const m=await load();const s=m.advanceCoreMixedPressureGuardArbitration(m.createCoreMixedPressureGuardArbitrationState(),{projectileStrength:.82,contactStrength:.61},.016);const p=m.coreMixedPressureGuardArbitrationPresentation(s,false);assert.equal(s.owner,'projectile');assert.ok(p.projectileAlphaScale>=.95);assert.ok(p.contactAlphaScale<=.18);assert.ok(p.projectileAlphaScale+p.contactAlphaScale<1.2);});
test('phase 3187 near-tie repeated pressure holds previous owner briefly',async()=>{const m=await load();let s=m.advanceCoreMixedPressureGuardArbitration(m.createCoreMixedPressureGuardArbitrationState(),{projectileStrength:.72,contactStrength:.48},.016);assert.equal(s.owner,'projectile');s=m.advanceCoreMixedPressureGuardArbitration(s,{projectileStrength:.61,contactStrength:.65},.04);assert.equal(s.owner,'projectile');s=m.advanceCoreMixedPressureGuardArbitration(s,{projectileStrength:.54,contactStrength:.78},.18);assert.equal(s.owner,'contact');});
test('phase 3188 live enemy render shares arbitration across projectile and contact core guard cues with presentation-only audit',async()=>{const s=enemySource();assert.match(s,/coreMixedPressureGuardArbitration/);assert.match(s,/projectileAlphaScale/);assert.match(s,/contactAlphaScale/);assert.match(s,/liveMixedCoreGuardState/);const a=await import('../dist/game/core-mixed-pressure-guard-arbitration-audit.js');const r=a.runCoreMixedPressureGuardArbitrationAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
