import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const u=new URL('../src/game/safe-lane-combat-attention-budget-rendering.ts',import.meta.url);const game=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(u),true);return import('../dist/game/safe-lane-combat-attention-budget-rendering.js');}
test('phase 3303 safe-lane combat-attention budget module exists',async()=>{const m=await load();assert.equal(typeof m.safeLaneCombatAttentionBudgetPresentation,'function');});
test('phase 3304 calm combat preserves the full safe-lane cue stack',async()=>{const m=await load();const p=m.safeLaneCombatAttentionBudgetPresentation({heroCritical:false,coreCritical:false,lawActive:false},false);assert.equal(p.primaryAlphaScale,1);assert.equal(p.bridgeAlphaScale,1);assert.equal(p.detailVisible,true);assert.equal(p.directionVisible,true);});
test('phase 3305 hero critical keeps the primary locator but demotes forecast detail and direction',async()=>{const m=await load();const p=m.safeLaneCombatAttentionBudgetPresentation({heroCritical:true,coreCritical:false,lawActive:false},false);assert.ok(p.primaryAlphaScale>=.5);assert.ok(p.bridgeAlphaScale<1);assert.equal(p.detailVisible,false);assert.equal(p.directionVisible,false);});
test('phase 3306 core critical receives at least as much demotion as hero critical',async()=>{const m=await load();const hero=m.safeLaneCombatAttentionBudgetPresentation({heroCritical:true,coreCritical:false,lawActive:false},false),core=m.safeLaneCombatAttentionBudgetPresentation({heroCritical:false,coreCritical:true,lawActive:false},false);assert.ok(core.bridgeAlphaScale<=hero.bridgeAlphaScale);assert.ok(core.arrivalAlphaScale<=hero.arrivalAlphaScale);});
test('phase 3307 active Last Law owns identity attention while retaining a subdued navigational locator',async()=>{const m=await load();const p=m.safeLaneCombatAttentionBudgetPresentation({heroCritical:false,coreCritical:false,lawActive:true},false);assert.equal(p.identityOwner,'law');assert.equal(p.directionVisible,false);assert.equal(p.detailVisible,false);assert.ok(p.primaryAlphaScale>0);});
test('phase 3308 live safe-lane render applies attention scales before bridge detail and direction with presentation-only audit',async()=>{const s=game();assert.match(s,/safeLaneCombatAttentionBudgetPresentation/);assert.match(s,/safeLaneAttention/);const a=await import('../dist/game/safe-lane-combat-attention-budget-audit.js');const r=a.runSafeLaneCombatAttentionBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
