import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/hero-ground-contact-ownership-rendering.ts',import.meta.url);
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-ground-contact-ownership-rendering.js');}

test('phase 3021 hero ground contact ownership module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.heroGroundContactOwnershipPresentation,'function');});
test('phase 3022 locomotion keeps a stable ground owner when no higher action is active',async()=>{const {heroGroundContactOwnershipPresentation}=await loadModule();const p=heroGroundContactOwnershipPresentation({movement:.82,cast:0,evade:0,ultimate:0,actionOffsetX:3,actionOffsetY:1,lift:0},false);assert.equal(p.owner,'locomotion');assert.ok(p.locomotionGroundScale>=.78);assert.ok(p.actionFollowScale>=.5);assert.ok(Math.abs(p.shadowOffsetX)<=2.4);});
test('phase 3023 rapid cast owns the shadow before locomotion and keeps bounded forward follow',async()=>{const {heroGroundContactOwnershipPresentation}=await loadModule();const p=heroGroundContactOwnershipPresentation({movement:1,cast:.86,evade:0,ultimate:0,actionOffsetX:7,actionOffsetY:-2,lift:2.2},false);assert.equal(p.owner,'cast');assert.ok(p.locomotionGroundScale<.7);assert.ok(p.actionFollowScale>.2&&p.actionFollowScale<.5);assert.ok(Math.abs(p.shadowOffsetX)<=3.2);});
test('phase 3024 perfect evade anchors the shadow more strongly than cast while preserving direction',async()=>{const {heroGroundContactOwnershipPresentation}=await loadModule();const cast=heroGroundContactOwnershipPresentation({movement:.7,cast:.8,evade:0,ultimate:0,actionOffsetX:8,actionOffsetY:1,lift:1},false);const evade=heroGroundContactOwnershipPresentation({movement:.7,cast:.2,evade:.95,ultimate:0,actionOffsetX:8,actionOffsetY:1,lift:1},false);assert.equal(evade.owner,'evade');assert.ok(evade.actionFollowScale<cast.actionFollowScale);assert.ok(evade.shadowOffsetX>0);});
test('phase 3025 ultimate lift keeps the shadow grounded and softens it instead of following the lifted body',async()=>{const {heroGroundContactOwnershipPresentation}=await loadModule();const p=heroGroundContactOwnershipPresentation({movement:.5,cast:.5,evade:.4,ultimate:1,actionOffsetX:9,actionOffsetY:-9,lift:9},false);assert.equal(p.owner,'ultimate');assert.ok(Math.abs(p.shadowOffsetX)<=2);assert.ok(Math.abs(p.shadowOffsetY)<=1.6);assert.ok(p.widthScale<1);assert.ok(p.alphaScale<.85);});
test('phase 3026 hero render shares the action owner with the ground shadow and audit stays presentation-only',async()=>{assert.match(gameSource,/heroGroundContactOwnershipPresentation/);assert.match(gameSource,/heroGroundOwnership\.locomotionGroundScale/);assert.match(gameSource,/heroGroundOwnership\.shadowOffsetX/);assert.match(gameSource,/heroGroundOwnership\.alphaScale/);assert.equal(fs.existsSync(new URL('../src/game/hero-ground-contact-ownership-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-ground-contact-ownership-audit.js');const audit=mod.runHeroGroundContactOwnershipAudit();assert.equal(audit.samples.length,96);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
