import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
const game=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const events=fs.readFileSync(new URL('../src/game/field-events.ts',import.meta.url),'utf8');
const snapshot=fs.readFileSync(new URL('../src/game/endless/snapshot.ts',import.meta.url),'utf8');
test('phase 2201 shows response and effect helpers in existing tactical field-event row',()=>{for(const needle of ['FIELD_EVENT_RESPONSE_IDENTITY_ATLAS','FIELD_EVENT_EFFECT_PROFILE_IDENTITY_ATLAS','initializeFieldEventResponseIdentityAtlas','initializeFieldEventEffectProfileIdentityAtlas','drawFieldEventResponseEffectRecall','fieldEventId: event.id'])assert.match(game,new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(game,/drawStatusRow\(ctx, y, row\.accent, row\.title, row\.detail, row\.iconId\)/);});
test('phase 2202 adds only response helper to golden goblin and supply drop world targets',()=>{assert.match(game,/drawGoldenGoblinEventResponseIdentity/);assert.match(game,/goldenGoblinEnemyId/);assert.match(game,/drawSupplyCrate[\s\S]*drawFieldEventResponseIdentity\(ctx,'supplyDrop'/);assert.doesNotMatch(game,/drawFieldEventEffectProfileIdentity\(ctx,'supplyDrop'[^\n]*drawSupplyCrate/);});
test('phase 2203 event start toast keeps base event icon and adds at most response plus effect helpers',()=>{assert.match(game,/showFieldEventStartToast/);assert.match(game,/handleFieldEventStart[\s\S]*showFieldEventStartToast\(`\$\{event\.name\} 발생!`, event\.id\)/);assert.match(game,/eventToastFieldEventId/);assert.match(game,/drawFieldEventToastHelperIcons/);});
test('phase 2204 hides only new field-event helpers during hero core critical or imminent boss special',()=>{assert.match(game,/hideFieldEventHelperIdentity/);assert.match(game,/heroCritical/);assert.match(game,/coreCritical/);assert.match(game,/bossSpecialTimer\s*<=\s*1\.2/);});
test('phase 2201-2204 preserves field-event gameplay and endless snapshot schema',()=>{assert.match(events,/cooldownMultiplier:\s*0\.68[\s\S]*spawnPressureMultiplier:\s*1\.5/);assert.match(events,/goldMultiplier:\s*2/);assert.match(events,/eliteIntervalMultiplier:\s*0\.42/);assert.match(events,/duration:\s*22/);assert.match(events,/duration:\s*30/);assert.match(events,/duration:\s*25/);assert.match(events,/duration:\s*14/);assert.doesNotMatch(snapshot,/fieldEventResponseIdentity|fieldEventEffectProfileIdentity|eventToastFieldEventId/);});
