import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/character-silhouette-direction-owner-rendering.js');}
const base={kind:'specialist',locomotion:{x:1,y:0},target:{x:0,y:1},hitDirection:{x:-1,y:0},attack:0,recovery:0,hit:0,special:0};
test('phase 3459 strong hit owns specialist silhouette direction over locomotion',async()=>{const m=await load();const p=m.characterSilhouetteDirectionOwnerPresentation({...base,hit:.8},false);assert.equal(p.owner,'hit');assert.ok(p.facingX<-.95);});
test('phase 3460 active boss special aligns silhouette trail away from the special target line',async()=>{const m=await load();const p=m.characterSilhouetteDirectionOwnerPresentation({...base,kind:'boss',special:.8},false);assert.equal(p.owner,'special');assert.ok(p.facingY>.95);});
test('phase 3461 attack commitment owns specialist silhouette direction toward its target',async()=>{const m=await load();const p=m.characterSilhouetteDirectionOwnerPresentation({...base,attack:.7},false);assert.equal(p.owner,'attack');assert.ok(p.facingY>.95);});
test('phase 3462 recovery keeps the committed target direction instead of snapping to locomotion',async()=>{const m=await load();const p=m.characterSilhouetteDirectionOwnerPresentation({...base,recovery:.6},false);assert.equal(p.owner,'recovery');assert.ok(p.facingY>.95);});
test('phase 3463 neutral silhouette direction falls back to normalized locomotion and stays finite',async()=>{const m=await load();const p=m.characterSilhouetteDirectionOwnerPresentation({...base,locomotion:{x:2,y:0}},false);assert.equal(p.owner,'locomotion');assert.equal(p.facingX,1);assert.equal(p.facingY,0);assert.ok(Number.isFinite(p.trailDistanceScale));});
test('phase 3464 live specialist and boss silhouettes consume the owned direction presentation-only',async()=>{const modSource=fs.readFileSync(new URL('../src/game/character-silhouette-direction-owner-rendering.ts',import.meta.url),'utf8');assert.match(source,/characterSilhouetteDirectionOwnerPresentation/);assert.match(source,/owned:silhouetteDirection/);assert.match(source,/characterSilhouetteDirectionPivotPresentation/);assert.doesNotMatch(modSource,/damage|cooldown|attackTimer\s*=/i);const a=await import('../dist/game/character-silhouette-direction-owner-audit.js');const r=a.runCharacterSilhouetteDirectionOwnerAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
