import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as finish from '../dist/game/specialist-strike-impact-side-finish-rendering.js';
const fn=finish.specialistAttackSilhouetteRecoveryTrailPresentation;
test('specialist attack silhouette recovery trail helper exists',()=>assert.equal(typeof fn,'function'));
test('active strike keeps attack silhouette direction',()=>{const p=fn?.({type:'assassin',attackFacingX:1,attackFacingY:0,recoveryFacingX:0,recoveryFacingY:1,lunge:.9,resolve:0,recoveryBlend:0},false);assert.ok(p);assert.equal(p.owner,'attack');assert.ok(p.facingX>.9);assert.ok(Math.abs(p.facingY)<.2);});
test('recovery blends trail toward locomotion facing',()=>{const p=fn?.({type:'shieldbearer',attackFacingX:1,attackFacingY:0,recoveryFacingX:0,recoveryFacingY:1,lunge:0,resolve:.55,recoveryBlend:.6},false);assert.ok(p);assert.equal(p.owner,'handoff');assert.ok(p.facingY>0);assert.ok(p.trailAlphaScale<1);});
test('late recovery trail owns locomotion direction',()=>{const p=fn?.({type:'siegeGolem',attackFacingX:1,attackFacingY:0,recoveryFacingX:0,recoveryFacingY:1,lunge:0,resolve:.1,recoveryBlend:.96},false);assert.ok(p);assert.equal(p.owner,'recovery');assert.ok(p.facingY>.9);assert.ok(p.trailDistanceScale<1);});
test('reduced motion shortens recovery trail without changing owner',()=>{const a=fn?.({type:'nullifier',attackFacingX:1,attackFacingY:0,recoveryFacingX:0,recoveryFacingY:1,lunge:0,resolve:.4,recoveryBlend:.65},false),b=fn?.({type:'nullifier',attackFacingX:1,attackFacingY:0,recoveryFacingX:0,recoveryFacingY:1,lunge:0,resolve:.4,recoveryBlend:.65},true);assert.ok(a&&b);assert.equal(a.owner,b.owner);assert.ok(b.trailDistanceScale<a.trailDistanceScale);});
test('live specialist silhouette applies recovery trail presentation',()=>{const s=fs.readFileSync('src/game/enemies.ts','utf8');assert.match(s,/specialistAttackSilhouetteRecoveryTrailPresentation/);assert.match(s,/specialistSilhouetteRecoveryTrail/);});
