import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/hero-hit-ground-handoff-rendering.ts',import.meta.url);
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-hit-ground-handoff-rendering.js');}

test('phase 3039 hero hit ground handoff module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.heroHitGroundHandoffPresentation,'function');});
test('phase 3040 heavy hit owns ground contact when no higher action is active',async()=>{const {heroHitGroundHandoffPresentation}=await loadModule();const p=heroHitGroundHandoffPresentation({hit:.95,hitOffsetX:-8,hitOffsetY:3,movement:.6,cast:0,evade:0,ultimate:0},false);assert.equal(p.owner,'hit');assert.ok(p.groundMotionScale<.7);assert.ok(p.widthScale>1);assert.ok(p.heightScale<1);});
test('phase 3041 hit shadow follows only a bounded fraction of body recoil',async()=>{const {heroHitGroundHandoffPresentation}=await loadModule();const p=heroHitGroundHandoffPresentation({hit:1,hitOffsetX:-12,hitOffsetY:7,movement:0,cast:0,evade:0,ultimate:0},false);assert.ok(p.shadowOffsetX<0);assert.ok(Math.abs(p.shadowOffsetX)<=2.6);assert.ok(Math.abs(p.shadowOffsetY)<=1.8);});
test('phase 3042 recoil recovery hands ground ownership back smoothly instead of snapping',async()=>{const {heroHitGroundHandoffPresentation}=await loadModule();const hit=heroHitGroundHandoffPresentation({hit:.8,hitOffsetX:-6,hitOffsetY:2,movement:.7,cast:0,evade:0,ultimate:0},false);const recover=heroHitGroundHandoffPresentation({hit:.16,hitOffsetX:-2,hitOffsetY:.5,movement:.7,cast:0,evade:0,ultimate:0},false);assert.equal(recover.owner,'recover');assert.ok(recover.groundMotionScale>hit.groundMotionScale&&recover.groundMotionScale<1);assert.ok(Math.abs(recover.shadowOffsetX)<Math.abs(hit.shadowOffsetX));});
test('phase 3043 evade cast and ultimate keep priority over stale hit-ground ownership',async()=>{const {heroHitGroundHandoffPresentation}=await loadModule();for(const input of [{cast:.8,evade:0,ultimate:0},{cast:.1,evade:.9,ultimate:0},{cast:.5,evade:.5,ultimate:1}]){const p=heroHitGroundHandoffPresentation({hit:.9,hitOffsetX:-8,hitOffsetY:2,movement:.8,...input},false);assert.equal(p.owner,'action');assert.ok(Math.abs(p.shadowOffsetX)<1);}});
test('phase 3044 hero render composes hit ground handoff into the existing shadow and audit stays presentation-only',async()=>{assert.match(gameSource,/heroHitGroundHandoffPresentation/);assert.match(gameSource,/heroHitGroundHandoff\.groundMotionScale/);assert.match(gameSource,/heroHitGroundHandoff\.shadowOffsetX/);assert.match(gameSource,/heroHitGroundHandoff\.widthScale/);assert.equal(fs.existsSync(new URL('../src/game/hero-hit-ground-handoff-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-hit-ground-handoff-audit.js');const audit=mod.runHeroHitGroundHandoffAudit();assert.equal(audit.samples.length,48);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
