import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-contact-guard-memory-rendering.ts',import.meta.url);const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-contact-guard-memory-rendering.js');}
test('phase 3165 core contact guard memory module exists',async()=>{const m=await load();assert.equal(typeof m.coreContactGuardMemoryPresentation,'function');});
test('phase 3166 strong melee mitigation owns contact guard',async()=>{const {coreContactGuardMemoryPresentation}=await load();const p=coreContactGuardMemoryPresentation({preventedRatio:.72,ttl:.34,maxTtl:.4},false);assert.equal(p.owner,'contact-guard');assert.ok(p.contactAlpha>.35);assert.equal(p.projectileArcAlphaScale,0);});
test('phase 3167 weak mitigation remains ordinary contact',async()=>{const {coreContactGuardMemoryPresentation}=await load();const p=coreContactGuardMemoryPresentation({preventedRatio:.05,ttl:.34,maxTtl:.4},false);assert.equal(p.owner,'impact');assert.equal(p.contactAlpha,0);});
test('phase 3168 late contact cue becomes low ground memory',async()=>{const {coreContactGuardMemoryPresentation}=await load();const p=coreContactGuardMemoryPresentation({preventedRatio:.7,ttl:.08,maxTtl:.4},false);assert.equal(p.owner,'memory');assert.ok(p.memoryAlpha>0&&p.memoryAlpha<.22);});
test('phase 3169 reduced flash compresses contact guard but preserves owner',async()=>{const {coreContactGuardMemoryPresentation}=await load();const a=coreContactGuardMemoryPresentation({preventedRatio:.7,ttl:.32,maxTtl:.4},false),b=coreContactGuardMemoryPresentation({preventedRatio:.7,ttl:.32,maxTtl:.4},true);assert.equal(b.owner,'contact-guard');assert.ok(b.contactAlpha<a.contactAlpha);});
test('phase 3170 live core melee path reads applied damage and queues distinct contact guard memory',async()=>{const s=enemySource();assert.match(s,/coreContactGuardMemoryPresentation/);assert.match(s,/coreContactGuardImpactVfx/);assert.match(s,/ctx\.onCoreDamage\(enemy\.damage \* frenzyDamage\s*,\s*'contact'(?:\s*,\s*enemy\.pos)?\)/);const a=await import('../dist/game/core-contact-guard-memory-audit.js');const r=a.runCoreContactGuardMemoryAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
