import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-guard-survival-response-arbitration-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-guard-survival-response-arbitration-rendering.js');}
test('phase 3201 core guard survival-response arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.coreGuardSurvivalResponseArbitrationPresentation,'function');});
test('phase 3202 survival core guard stays visible when no world-space guard owns the hit',async()=>{const m=await load();const p=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:0,worldGuardOwned:false,survivalTtl:.32,survivalMaxTtl:.42},false);assert.equal(p.owner,'survival');assert.equal(p.worldGuardOwned,false);assert.equal(p.survivalAlphaScale,1);});
test('phase 3203 active world-space core guard suppresses duplicate survival response',async()=>{const m=await load();const p=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:.72,worldGuardOwned:false,survivalTtl:.36,survivalMaxTtl:.42},false);assert.equal(p.owner,'world');assert.equal(p.worldGuardOwned,true);assert.equal(p.survivalAlphaScale,0);});
test('phase 3204 once world ownership latches the same survival cue never reanimates',async()=>{const m=await load();const first=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:.58,worldGuardOwned:false,survivalTtl:.34,survivalMaxTtl:.42},false);const later=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:0,worldGuardOwned:first.worldGuardOwned,survivalTtl:.18,survivalMaxTtl:.42},false);assert.equal(first.worldGuardOwned,true);assert.equal(later.owner,'retired');assert.equal(later.survivalAlphaScale,0);});
test('phase 3205 weak world trace does not steal an independent survival cue and reduced flash never raises alpha',async()=>{const m=await load();const normal=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:.08,worldGuardOwned:false,survivalTtl:.3,survivalMaxTtl:.42},false);const reduced=m.coreGuardSurvivalResponseArbitrationPresentation({worldGuardStrength:.08,worldGuardOwned:false,survivalTtl:.3,survivalMaxTtl:.42},true);assert.equal(normal.owner,'survival');assert.ok(reduced.survivalAlphaScale<=normal.survivalAlphaScale);});
test('phase 3206 live survival response reads enemy world guard ownership with presentation-only audit',async()=>{const g=gameSource(),e=enemySource();assert.match(g,/worldGuardOwned/);assert.match(g,/coreGuardSurvivalResponseArbitrationPresentation/);assert.match(e,/coreWorldGuardPresentationState/);const a=await import('../dist/game/core-guard-survival-response-arbitration-audit.js');const r=a.runCoreGuardSurvivalResponseArbitrationAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
