import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/specialist-silhouette-phase-handoff-rendering.js');}
const input=(over={})=>({pullback:0,lunge:.8,resolve:0,hit:0,...over});
test('phase 3531 active strike owns specialist silhouette over simultaneous resolve residue',async()=>{const m=await load();const p=m.specialistSilhouettePhaseHandoffPresentation(input({resolve:.35}),false);assert.equal(p.owner,'strike');assert.ok(p.strikeScale>.8);});
test('phase 3532 early resolve keeps a bounded strike carry so silhouette does not snap phase in one frame',async()=>{const m=await load();const p=m.specialistSilhouettePhaseHandoffPresentation(input({lunge:0,resolve:.25}),false);assert.equal(p.owner,'resolve');assert.ok(p.strikeCarry>0&&p.strikeCarry<.5);});
test('phase 3533 late resolve retires strike carry and lets resolve fade own the ghost',async()=>{const m=await load();const p=m.specialistSilhouettePhaseHandoffPresentation(input({lunge:0,resolve:.85}),false);assert.equal(p.owner,'resolve');assert.ok(p.strikeCarry<.1);assert.ok(p.resolveScale>.5);});
test('phase 3534 strong hit owns over strike and resolve silhouette presentation',async()=>{const m=await load();const p=m.specialistSilhouettePhaseHandoffPresentation(input({hit:.9,resolve:.4}),false);assert.equal(p.owner,'hit');assert.ok(p.attackAlphaScale<.4);});
test('phase 3535 reduced motion removes strike carry but preserves current phase identity',async()=>{const m=await load();const p=m.specialistSilhouettePhaseHandoffPresentation(input({lunge:0,resolve:.25}),true);assert.equal(p.owner,'resolve');assert.equal(p.strikeCarry,0);});
test('phase 3536 live specialist silhouette applies phase handoff before emphasis alpha and trail',async()=>{const s=source();assert.match(s,/specialistSilhouettePhaseHandoffPresentation/);assert.match(s,/specialistSilhouetteHandoff\.attackAlphaScale/);assert.match(s,/specialistSilhouetteHandoff\.trailScale/);const a=await import('../dist/game/specialist-silhouette-phase-handoff-audit.js');const r=a.runSpecialistSilhouettePhaseHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
