import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/hero-action-layer-budget-rendering.js');}
const input=(over={})=>({owner:'movement',movement:.8,cast:0,recovery:0,ultimate:0,hit:0,meter:.4,...over});
test('phase 3543 movement owner keeps locomotion layer strong while cast and recovery stay subdued',async()=>{const m=await load();const p=m.heroActionLayerBudgetPresentation(input(),false);assert.ok(p.movementScale>.8);assert.ok(p.castScale<.4);assert.ok(p.recoveryScale<.4);});
test('phase 3544 cast owner suppresses idle and movement clutter around the spell pose',async()=>{const m=await load();const p=m.heroActionLayerBudgetPresentation(input({owner:'cast',cast:.9}),false);assert.ok(p.castScale>.85);assert.ok(p.movementScale<.5);assert.ok(p.idleScale<.6);});
test('phase 3545 ultimate owner preserves crest identity but caps ordinary cast overlay competition',async()=>{const m=await load();const p=m.heroActionLayerBudgetPresentation(input({owner:'ultimate',ultimate:.9,cast:.5,meter:1}),false);assert.ok(p.crestScale>.55);assert.ok(p.castScale<.6);assert.equal(p.singleActionOwner,true);});
test('phase 3546 recovery owner keeps one recovery layer without restoring full movement texture immediately',async()=>{const m=await load();const p=m.heroActionLayerBudgetPresentation(input({owner:'recovery',recovery:.8,movement:.7}),false);assert.ok(p.recoveryScale>.7);assert.ok(p.movementScale<.65);});
test('phase 3547 hit pressure suppresses decorative overlays before the hero body itself',async()=>{const m=await load();const clean=m.heroActionLayerBudgetPresentation(input({owner:'cast',cast:.8}),false),hit=m.heroActionLayerBudgetPresentation(input({owner:'hit',cast:.8,hit:.9}),false);assert.ok(hit.castScale<clean.castScale);assert.ok(hit.crestScale<clean.crestScale);});
test('phase 3548 live hero idle movement cast recover and crest layers consume one action budget',async()=>{const s=source();assert.match(s,/heroActionLayerBudgetPresentation/);assert.match(s,/heroActionLayerBudget\.movementScale/);assert.match(s,/heroActionLayerBudget\.recoveryScale/);const a=await import('../dist/game/hero-action-layer-budget-audit.js');const r=a.runHeroActionLayerBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
