import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/hero-ultimate-action-handoff-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-ultimate-action-handoff-rendering.js');}

test('phase 2985 hero ultimate action handoff module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceHeroUltimateActionHandoffState,'function');assert.equal(typeof mod.heroUltimateActionHandoffPresentation,'function');});
test('phase 2986 ultimate recovery keeps ownership while the hero remains idle',async()=>{const mod=await loadModule();const p=mod.heroUltimateActionHandoffPresentation({kind:'meteorStorm',elapsed:.26},{normalCast:0},0,false);assert.equal(p.owner,'ultimate');assert.ok(p.ultimatePoseScale>.75);assert.ok(p.movementOwnership<.05);assert.ok(p.normalCastOwnership<.05);});
test('phase 2987 movement during ultimate recovery smoothly takes body ownership',async()=>{const mod=await loadModule();const idle=mod.heroUltimateActionHandoffPresentation({kind:'blackHole',elapsed:.34},{normalCast:0},0,false);const moving=mod.heroUltimateActionHandoffPresentation({kind:'blackHole',elapsed:.34},{normalCast:0},.92,false);assert.equal(moving.owner,'movement');assert.ok(moving.movementOwnership>.55);assert.ok(moving.ultimatePoseScale<idle.ultimatePoseScale);assert.ok(moving.ultimatePoseScale>=.08);});
test('phase 2988 a normal spell cast outranks movement during ultimate recovery',async()=>{const mod=await loadModule();let s=mod.advanceHeroUltimateActionHandoffState(undefined,true,0,false);const p=mod.heroUltimateActionHandoffPresentation({kind:'meteorStorm',elapsed:.31},s,.9,false);assert.equal(p.owner,'spell');assert.ok(p.normalCastOwnership>p.movementOwnership);assert.ok(p.ultimatePoseScale<=.3);assert.ok(p.castRecoverySuppressionScale<.45);});
test('phase 2989 normal spell ownership decays cleanly and reduced motion preserves owner identity',async()=>{const mod=await loadModule();let s=mod.advanceHeroUltimateActionHandoffState(undefined,true,0,false);const full=mod.heroUltimateActionHandoffPresentation({kind:'blackHole',elapsed:.3},s,.35,false);const reduced=mod.heroUltimateActionHandoffPresentation({kind:'blackHole',elapsed:.3},s,.35,true);assert.equal(full.owner,'spell');assert.equal(reduced.owner,full.owner);for(let i=0;i<20;i++)s=mod.advanceHeroUltimateActionHandoffState(s,false,.04,false);assert.equal(s.normalCast,0);const stale=mod.advanceHeroUltimateActionHandoffState(undefined,true,0,false);const reset=mod.advanceHeroUltimateActionHandoffState(stale,false,0,false,true);assert.equal(reset.normalCast,0);const cleared=mod.heroUltimateActionHandoffPresentation({kind:null,elapsed:0},s,.8,false);assert.equal(cleared.owner,'neutral');assert.equal(cleared.ultimatePoseScale,0);});
test('phase 2990 normal spell actions trigger handoff and audit stays presentation-only',async()=>{assert.match(gameSource,/heroUltimateActionHandoffState/);assert.match(gameSource,/advanceHeroUltimateActionHandoffState/);assert.match(gameSource,/heroUltimateActionHandoffPresentation/);assert.match(gameSource,/action === 'spell1'/);assert.match(gameSource,/normalSpellHandoff/);assert.match(gameSource,/heroUltimateActionHandoffState = \{ normalCast:0 \}/);assert.match(gameSource,/ultimatePoseScale/);assert.equal(fs.existsSync(new URL('../src/game/hero-ultimate-action-handoff-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-ultimate-action-handoff-audit.js');const audit=mod.runHeroUltimateActionHandoffAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
