import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/boss-stagger-special-recovery-arbitration-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-stagger-special-recovery-arbitration-rendering.js');}

test('phase 2997 boss stagger special recovery arbitration module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.bossStaggerSpecialRecoveryArbitrationPresentation,'function');});
test('phase 2998 active special recovery owns the boss silhouette over recent heavy stagger',async()=>{const mod=await loadModule();const p=mod.bossStaggerSpecialRecoveryArbitrationPresentation('inferno',2,{stagger:.82,tier:'heavy',recovery:.88,specialTimer:4},false);assert.equal(p.owner,'recovery');assert.ok(p.recoveryScale>.9);assert.ok(p.staggerScale<.3);assert.ok(p.genericRecoilScale<.35);});
test('phase 2999 critical stagger can remain legible but cannot destabilize early special recovery',async()=>{const mod=await loadModule();const heavy=mod.bossStaggerSpecialRecoveryArbitrationPresentation('abyssWitch',2,{stagger:.9,tier:'heavy',recovery:.8,specialTimer:4},false);const critical=mod.bossStaggerSpecialRecoveryArbitrationPresentation('abyssWitch',2,{stagger:1,tier:'critical',recovery:.8,specialTimer:4},false);assert.equal(critical.owner,'recovery');assert.ok(critical.staggerScale>=heavy.staggerScale);assert.ok(critical.staggerScale<=.42);assert.ok(critical.genericRecoilScale<=.38);});
test('phase 3000 stagger regains ownership as special recovery settles',async()=>{const mod=await loadModule();const early=mod.bossStaggerSpecialRecoveryArbitrationPresentation('twinMaw',1,{stagger:.85,tier:'heavy',recovery:.9,specialTimer:4},false);const late=mod.bossStaggerSpecialRecoveryArbitrationPresentation('twinMaw',1,{stagger:.85,tier:'heavy',recovery:.08,specialTimer:4},false);assert.equal(early.owner,'recovery');assert.equal(late.owner,'stagger');assert.ok(late.staggerScale>early.staggerScale);assert.ok(late.genericRecoilScale>early.genericRecoilScale);});
test('phase 3001 a new special telegraph outranks both recovery and stagger and reduced motion keeps ownership',async()=>{const mod=await loadModule();const full=mod.bossStaggerSpecialRecoveryArbitrationPresentation('timeEater',3,{stagger:1,tier:'critical',recovery:.55,specialTimer:.7},false);const reduced=mod.bossStaggerSpecialRecoveryArbitrationPresentation('timeEater',3,{stagger:1,tier:'critical',recovery:.55,specialTimer:.7},true);assert.equal(full.owner,'telegraph');assert.equal(reduced.owner,'telegraph');assert.equal(full.telegraphProtected,true);assert.ok(full.recoveryScale<=.2);assert.ok(full.staggerScale<=1);});
test('phase 3002 boss render applies recovery arbitration and audit stays presentation-only',async()=>{assert.match(enemySource,/bossStaggerSpecialRecoveryArbitrationPresentation/);assert.match(enemySource,/recoveryScale/);assert.match(enemySource,/staggerScale/);assert.match(enemySource,/genericRecoilScale/);assert.equal(fs.existsSync(new URL('../src/game/boss-stagger-special-recovery-arbitration-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-stagger-special-recovery-arbitration-audit.js');const audit=mod.runBossStaggerSpecialRecoveryArbitrationAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
