import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/projectile-multihit-impact-retirement-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/projectile-multihit-impact-retirement-rendering.js');}
test('phase 3111 multihit impact retirement module exists',async()=>{const m=await load();assert.equal(typeof m.projectileMultiHitImpactHandoff,'function');});
test('phase 3112 first impact can inherit residual launch carry',async()=>{const {projectileMultiHitImpactHandoff}=await load();const p=projectileMultiHitImpactHandoff({launchOffset:{x:-18,y:6},launchTtl:.06,launchMaxTtl:.1,priorImpactCount:0,continues:true},false);assert.ok(Math.hypot(p.entryOffset.x,p.entryOffset.y)>0);assert.equal(p.impactOwner,'arrival');});
test('phase 3113 piercing continuation retires launch owner after first impact',async()=>{const {projectileMultiHitImpactHandoff}=await load();const p=projectileMultiHitImpactHandoff({launchOffset:{x:-18,y:6},launchTtl:.06,launchMaxTtl:.1,priorImpactCount:0,continues:true},false);assert.equal(p.retireLaunchOwner,true);assert.equal(p.nextTrailOwner,'canonical');});
test('phase 3114 subsequent impacts never duplicate arrival carry',async()=>{const {projectileMultiHitImpactHandoff}=await load();const p=projectileMultiHitImpactHandoff({launchOffset:{x:-18,y:6},launchTtl:.06,launchMaxTtl:.1,priorImpactCount:1,continues:true},false);assert.deepEqual(p.entryOffset,{x:0,y:0});assert.equal(p.impactOwner,'canonical');});
test('phase 3115 terminal first hit may keep impact carry without persistent trail',async()=>{const {projectileMultiHitImpactHandoff}=await load();const p=projectileMultiHitImpactHandoff({launchOffset:{x:-14,y:4},launchTtl:.04,launchMaxTtl:.1,priorImpactCount:0,continues:false},false);assert.ok(Math.hypot(p.entryOffset.x,p.entryOffset.y)>0);assert.equal(p.nextTrailOwner,'retired');});
test('phase 3116 spell integration retires visual launch metadata on piercing continuation and audit stays presentation only',async()=>{const s=spellSource();assert.match(s,/projectileMultiHitImpactHandoff/);assert.match(s,/delete p\.visualLaunchOffset/);assert.match(s,/delete p\.visualLaunchTtl/);assert.match(s,/delete p\.visualLaunchMaxTtl/);const a=await import('../dist/game/projectile-multihit-impact-retirement-audit.js');const audit=a.runProjectileMultiHitImpactRetirementAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
