import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-special-launch-origin-rendering.ts',import.meta.url);const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const arenaSource=fs.readFileSync(new URL('../src/game/boss-arena.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-special-launch-origin-rendering.js');}
test('phase 3087 boss special launch origin module exists',async()=>{const m=await load();assert.equal(typeof m.bossSpecialLaunchOriginPresentation,'function');});
test('phase 3088 boss projectile launch follows special body language and facing owner',async()=>{const {bossSpecialLaunchOriginPresentation}=await load();const p=bossSpecialLaunchOriginPresentation({archetype:'juggernaut',phase:2,radius:58,facingX:1,facingY:0,specialTimer:0,rebaseOffsetX:0,rebaseOffsetY:0,handoffStrength:0},false);assert.equal(p.owner,'special-body');assert.ok(p.projectileOffsetX>20);assert.ok(Math.abs(p.projectileOffsetY)<=18);});
test('phase 3089 large displacement handoff rebases launch origin without following full stale offset',async()=>{const {bossSpecialLaunchOriginPresentation}=await load();const p=bossSpecialLaunchOriginPresentation({archetype:'juggernaut',phase:3,radius:58,facingX:1,facingY:0,specialTimer:0,rebaseOffsetX:-80,rebaseOffsetY:32,handoffStrength:1},false);assert.equal(p.owner,'rebase');assert.ok(Math.abs(p.projectileOffsetX)<=52);assert.ok(Math.abs(p.hazardOriginOffsetX)<=24);assert.ok(Math.abs(p.hazardOriginOffsetY)<=14);});
test('phase 3090 active special telegraph keeps launch origin attached to body instead of stale pre dash ground point',async()=>{const {bossSpecialLaunchOriginPresentation}=await load();const p=bossSpecialLaunchOriginPresentation({archetype:'inferno',phase:1,radius:58,facingX:.7,facingY:.7,specialTimer:.45,rebaseOffsetX:-30,rebaseOffsetY:10,handoffStrength:.7},false);assert.ok(p.bodyLanguageWeight>0);assert.ok(p.rebaseWeight<1);assert.ok(p.convergeSeconds>0);});
test('phase 3091 reduced motion compresses projectile and hazard visual launch offsets while keeping owner semantics',async()=>{const {bossSpecialLaunchOriginPresentation}=await load();const f=bossSpecialLaunchOriginPresentation({archetype:'twinMaw',phase:3,radius:58,facingX:0,facingY:1,specialTimer:0,rebaseOffsetX:-28,rebaseOffsetY:12,handoffStrength:1},false);const r=bossSpecialLaunchOriginPresentation({archetype:'twinMaw',phase:3,radius:58,facingX:0,facingY:1,specialTimer:0,rebaseOffsetX:-28,rebaseOffsetY:12,handoffStrength:1},true);assert.equal(r.owner,f.owner);assert.ok(Math.hypot(r.projectileOffsetX,r.projectileOffsetY)<Math.hypot(f.projectileOffsetX,f.projectileOffsetY));assert.ok(r.convergeSeconds<f.convergeSeconds);});
test('phase 3092 boss projectiles and hazards use shared visual launch origin without mutating gameplay trajectory and audit stays presentation only',async()=>{assert.match(enemySource,/bossSpecialLaunchOriginPresentation/);assert.match(enemySource,/bossVisualLaunch/);assert.match(arenaSource,/visualLaunchOrigin/);assert.match(arenaSource,/launchOrigin/);assert.match(gameSource,/visualLaunchOrigin:bossLaunchOrigin/);assert.match(enemySource,/vel: \{ x: Math\.cos\(angle\) \* 285/);const a=await import('../dist/game/boss-special-launch-origin-audit.js');const audit=a.runBossSpecialLaunchOriginAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
