import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-lineage-label-placement-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-lineage-label-placement-rendering.js');}
test('phase 3243 secondary impact lineage label spatial-arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactLineageLabelPlacement,'function');});
test('phase 3244 secondary ×N label avoids primary projectile impact label blockers',async()=>{const m=await load();const p=m.secondaryImpactLineageLabelPlacement({anchor:{x:300,y:300},blockers:[{x:300,y:272}],occupied:[],width:1280,height:800});assert.equal(p.visible,true);assert.ok(Math.hypot(p.pos.x-300,p.pos.y-272)>=m.SECONDARY_IMPACT_LABEL_PRIMARY_CLEARANCE);});
test('phase 3245 edge-near secondary labels stay inside the safe viewport inset',async()=>{const m=await load();for(const anchor of [{x:4,y:5},{x:1276,y:795}]){const p=m.secondaryImpactLineageLabelPlacement({anchor,blockers:[],occupied:[],width:1280,height:800});assert.equal(p.visible,true);assert.ok(p.pos.x>=m.SECONDARY_IMPACT_LABEL_SCREEN_INSET&&p.pos.x<=1280-m.SECONDARY_IMPACT_LABEL_SCREEN_INSET);assert.ok(p.pos.y>=m.SECONDARY_IMPACT_LABEL_SCREEN_INSET&&p.pos.y<=800-m.SECONDARY_IMPACT_LABEL_SCREEN_INSET);}});
test('phase 3246 sibling secondary labels arbitrate against already occupied positions',async()=>{const m=await load();const a=m.secondaryImpactLineageLabelPlacement({anchor:{x:400,y:300},blockers:[],occupied:[],width:1280,height:800});const b=m.secondaryImpactLineageLabelPlacement({anchor:{x:408,y:302},blockers:[],occupied:[a.pos],width:1280,height:800});assert.equal(a.visible,true);assert.equal(b.visible,true);assert.ok(Math.hypot(a.pos.x-b.pos.x,a.pos.y-b.pos.y)>=m.SECONDARY_IMPACT_LABEL_SECONDARY_CLEARANCE);});
test('phase 3247 secondary labels hide instead of overlapping when every clean slot is blocked',async()=>{const m=await load();const blockers=[{x:300,y:270},{x:334,y:286},{x:266,y:286},{x:300,y:332},{x:336,y:320},{x:264,y:320}];const p=m.secondaryImpactLineageLabelPlacement({anchor:{x:300,y:300},blockers,occupied:[],width:1280,height:800});assert.equal(p.visible,false);});
test('phase 3248 live spell render receives current primary projectile label blockers and applies spatial arbitration with presentation-only audit',async()=>{assert.match(spellSource(),/secondaryImpactLineageLabelPlacement/);assert.match(spellSource(),/primaryProjectileLabelBlockers/);assert.match(gameSource(),/projectileImpactLabelBlockers/);assert.match(enemySource(),/projectileImpactLabelBlockers/);const a=await import('../dist/game/secondary-impact-lineage-label-placement-audit.js');const r=a.runSecondaryImpactLineageLabelPlacementAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
