import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-focus-transfer-coherence-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4185 projectile focus transfer prevents simultaneous full primary and trail emphasis',async()=>{const {projectileFocusTransferCoherencePresentation}=await load();const p=projectileFocusTransferCoherencePresentation({incomingFocus:1,outgoingFocus:1,stress:1,critical:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.incomingScale+p.outgoingScale<1.6);assert.ok(p.secondaryScale<.78);});
test('Phase 4186 impact transfer yields interior when telegraph and edge focus overlap',async()=>{const {impactFocusTransferCoherencePresentation}=await load();const p=impactFocusTransferCoherencePresentation({incomingFocus:1,outgoingFocus:1,stress:1,critical:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<.78);});
test('Phase 4187 hazard transfer protects boundary while old interior focus retires',async()=>{const {hazardFocusTransferCoherencePresentation}=await load();const p=hazardFocusTransferCoherencePresentation({incomingFocus:1,outgoingFocus:1,stress:1,critical:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.outgoingScale<.7);});
test('Phase 4188 safe lane transfer keeps path canonical under boss focus handoff',async()=>{const {safeLaneFocusTransferCoherencePresentation}=await load();const p=safeLaneFocusTransferCoherencePresentation({incomingFocus:1,outgoingFocus:1,stress:1,critical:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<.8);});
test('Phase 4189 specialist transfer keeps silhouette ahead of recovery trail',async()=>{const {specialistFocusTransferCoherencePresentation}=await load();const p=specialistFocusTransferCoherencePresentation({incomingFocus:1,outgoingFocus:1,stress:1,critical:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.incomingScale>p.outgoingScale);});
test('Phase 4190 focus transfer budget keeps canonical priority and only attenuates secondary',async()=>{const {focusTransferCoherenceBudgetPresentation}=await load();const p=focusTransferCoherenceBudgetPresentation({criticalCount:2,stress:1,incomingFocus:1,outgoingFocus:1},false,false);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<.75);});
test('Phase 4185-4190 live renderers consume focus transfer coherence',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileFocusTransferCoherencePresentation/);assert.match(e,/specialistFocusTransferCoherencePresentation/);assert.match(s,/impactFocusTransferCoherencePresentation/);assert.match(g,/hazardFocusTransferCoherencePresentation/);assert.match(g,/safeLaneFocusTransferCoherencePresentation/);assert.match(e,/projectileFocusTransfer\.secondaryScale/);});
