import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-canonical-reacquisition-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4137 projectile canonical body reacquires before stale trail',async()=>{const {projectileCanonicalReacquisitionPresentation}=await load();const p=projectileCanonicalReacquisitionPresentation({release:.15,pressure:1,critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.trailScale<.8);assert.ok(p.directionScale>=.72);});
test('Phase 4138 impact reacquisition restores edge before fill',async()=>{const {impactCanonicalReacquisitionPresentation}=await load();const p=impactCanonicalReacquisitionPresentation({release:.2,pressure:1,critical:false},false);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);assert.ok(p.edgeAlphaScale>=.78);});
test('Phase 4139 hazard telegraph reacquisition preserves the danger boundary',async()=>{const {hazardCanonicalReacquisitionPresentation}=await load();const p=hazardCanonicalReacquisitionPresentation({telegraph:true,release:.15,pressure:1,critical:true},false);assert.ok(p.edgeAlphaScale>=.95);assert.ok(p.fillScale<1);});
test('Phase 4140 safe lane reacquisition keeps an escape path floor',async()=>{const {safeLaneCanonicalReacquisitionPresentation}=await load();const p=safeLaneCanonicalReacquisitionPresentation({visible:true,confidence:.9,release:.2,pressure:1},false);assert.ok(p.pathAlphaFloor>=.93);assert.ok(p.safeLaneScale>=1);});
test('Phase 4141 specialist reacquisition retires recovery trail before facing',async()=>{const {specialistCanonicalReacquisitionPresentation}=await load();const p=specialistCanonicalReacquisitionPresentation({owner:'attack',release:.2,pressure:1,critical:false},false);assert.equal(p.bodyScale,1);assert.ok(p.recoveryTrailScale<1);assert.ok(p.facingScale>=.86);});
test('Phase 4142 canonical reacquisition budget never dims canonical owners',async()=>{const {canonicalReacquisitionBudgetPresentation}=await load();const p=canonicalReacquisitionBudgetPresentation({criticalCount:2,projectileCount:12,impactCount:8,hazardCount:5,silhouetteCount:4,safeLaneVisible:true},false,false);assert.equal(p.canonicalScale,1);assert.equal(p.criticalEdgeScale,1);assert.ok(p.staleDecorationScale<1);assert.ok(p.safeLaneScale>=1);});
test('Phase 4137-4142 live renderers consume canonical reacquisition helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileCanonicalReacquisitionPresentation/);assert.match(e,/specialistCanonicalReacquisitionPresentation/);assert.match(s,/impactCanonicalReacquisitionPresentation/);assert.match(g,/hazardCanonicalReacquisitionPresentation/);assert.match(g,/safeLaneCanonicalReacquisitionPresentation/);});
