import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/boss-phase-aftermath-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/boss-phase-aftermath-vfx-assets.js');}

test('phase 2517 boss phase aftermath atlas covers six archetypes x two phases x burst aftermath',async()=>{const mod=await load(),audit=mod.auditBossPhaseAftermathVfxAtlas();assert.equal(audit.archetypeCount,6);assert.equal(audit.phaseCount,2);assert.equal(audit.stateCount,2);assert.equal(audit.itemCount,24);assert.equal(audit.uniqueCellCount,24);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.BOSS_PHASE_AFTERMATH_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:768,height:512});assert.ok(b.length>7000);});
test('phase 2518 actual phase transition queues archetype phase and boss position for world aftermath',()=>{assert.match(gameSource,/bossPhaseTransitionVfx\.push\(\{archetype,phase:cue\.phase,x:enemy\.pos\.x,y:enemy\.pos\.y/);assert.match(gameSource,/this\.bossPresentation\.update\(enemy\.id, bossRatio, archetype\)/);});
test('phase 2519 phase transition world cue changes from burst to aftermath without changing boss phase logic',()=>{assert.match(gameSource,/bossPhaseAftermathVfxSprite\(cue\.archetype,cue\.phase,state\)/);assert.match(gameSource,/progress<0\.34\?'burst':'aftermath'/);assert.match(gameSource,/bossPhaseForRatio/);});
test('phase 2520 phase aftermath queue is ttl bounded capped and reset between runs',()=>{assert.match(gameSource,/bossPhaseTransitionVfx\.length>12/);assert.match(gameSource,/this\.bossPhaseTransitionVfx = \[\]/);assert.match(gameSource,/for \(const cue of this\.bossPhaseTransitionVfx\) cue\.ttl -= safeDt/);});
test('phase 2521 boss phase aftermath atlas loads independently and old phase telegraph remains fallback',()=>{assert.match(gameSource,/initializeBossPhaseAftermathVfxAtlas/);assert.match(gameSource,/bossPhaseAftermathVfxAtlasImage/);assert.match(gameSource,/this\.presentation\.emitTelegraph\(\{ x: enemy\.pos\.x, y: enemy\.pos\.y, radius: cue\.ringRadius/);});
test('phase 2522 boss phase aftermath audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/boss-phase-aftermath-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-phase-aftermath-vfx-audit.js'),audit=mod.runBossPhaseAftermathVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/bossPhaseAftermathVfxPassed/);assert.match(candidateSource,/bossPhaseAftermathVfxPassed/);assert.match(candidateSource,/boss-phase-aftermath-vfx/);});
