import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/projectile-guard-impact-handoff-rendering.ts',import.meta.url);const enemySource=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/projectile-guard-impact-handoff-rendering.js');}
test('phase 3129 projectile guard impact handoff module exists',async()=>{const m=await load();assert.equal(typeof m.projectileGuardImpactHandoffPresentation,'function');});
test('phase 3130 strongly prevented projectile hands ownership to guard impact',async()=>{const {projectileGuardImpactHandoffPresentation}=await load();const p=projectileGuardImpactHandoffPresentation({preventedRatio:.72,impactTtl:.32,impactMaxTtl:.36},false);assert.equal(p.owner,'guard');assert.equal(p.threatAlphaScale,0);assert.ok(p.guardImpactAlpha>.45);});
test('phase 3131 lightly mitigated projectile remains ordinary impact',async()=>{const {projectileGuardImpactHandoffPresentation}=await load();const p=projectileGuardImpactHandoffPresentation({preventedRatio:.08,impactTtl:.32,impactMaxTtl:.36},false);assert.equal(p.owner,'impact');assert.equal(p.guardImpactAlpha,0);});
test('phase 3132 guard impact deflection line is bounded and fades',async()=>{const {projectileGuardImpactHandoffPresentation}=await load();const a=projectileGuardImpactHandoffPresentation({preventedRatio:.8,impactTtl:.34,impactMaxTtl:.36},false),b=projectileGuardImpactHandoffPresentation({preventedRatio:.8,impactTtl:.08,impactMaxTtl:.36},false);assert.ok(a.deflectDistance<=22);assert.ok(a.guardImpactAlpha>b.guardImpactAlpha);});
test('phase 3133 reduced flash compresses guard impact without reviving threat',async()=>{const {projectileGuardImpactHandoffPresentation}=await load();const f=projectileGuardImpactHandoffPresentation({preventedRatio:.7,impactTtl:.3,impactMaxTtl:.36},false),r=projectileGuardImpactHandoffPresentation({preventedRatio:.7,impactTtl:.3,impactMaxTtl:.36},true);assert.equal(r.threatAlphaScale,0);assert.ok(r.guardImpactAlpha<f.guardImpactAlpha);});
test('phase 3134 live projectile damage returns applied amount and queues presentation-only guard handoff',async()=>{const e=enemySource(),g=gameSource();assert.match(e,/onHeroDamage: \(amount: number, source\?: DamageReasonSource\) => number \| void/);assert.match(e,/projectileGuardImpactHandoffPresentation/);assert.match(e,/ctx\.onHeroDamage\(p\.damage, 'projectile'\)/);assert.match(g,/return applied/);const a=await import('../dist/game/projectile-guard-impact-handoff-audit.js');const audit=a.runProjectileGuardImpactHandoffAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
