import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const url=new URL('../src/game/boss-recovery-stagger-handoff-rendering.ts',import.meta.url);
async function load(){assert.equal(fs.existsSync(url),true);return import('../dist/game/boss-recovery-stagger-handoff-rendering.js');}
test('phase 3411 boss recovery stagger handoff module exists',async()=>{const m=await load();assert.equal(typeof m.bossRecoveryStaggerHandoffPresentation,'function');});
test('phase 3412 early special recovery stays authoritative over nonfatal heavy stagger',async()=>{const m=await load();const p=m.bossRecoveryStaggerHandoffPresentation({recovery:.9,stagger:1,tier:'heavy',specialTimer:4},false);assert.equal(p.owner,'recovery');assert.ok(p.recoveryScale>.85);assert.ok(p.staggerScale<.6);});
test('phase 3413 late special recovery yields to a strong heavy stagger instead of fighting it',async()=>{const m=await load();const p=m.bossRecoveryStaggerHandoffPresentation({recovery:.32,stagger:.92,tier:'heavy',specialTimer:4},false);assert.equal(p.owner,'stagger');assert.ok(p.recoveryScale<.55);assert.ok(p.staggerScale>.85);});
test('phase 3414 critical stagger can take ownership slightly earlier than heavy stagger',async()=>{const m=await load();const h=m.bossRecoveryStaggerHandoffPresentation({recovery:.48,stagger:.78,tier:'heavy',specialTimer:4},false),c=m.bossRecoveryStaggerHandoffPresentation({recovery:.48,stagger:.78,tier:'critical',specialTimer:4},false);assert.ok(c.staggerScale>=h.staggerScale);assert.ok(c.recoveryScale<=h.recoveryScale);});
test('phase 3415 a new boss telegraph always protects telegraph ownership and reduced motion identity',async()=>{const m=await load();for(const reduced of [false,true]){const p=m.bossRecoveryStaggerHandoffPresentation({recovery:.3,stagger:1,tier:'critical',specialTimer:.7},reduced);assert.equal(p.owner,'telegraph');assert.equal(p.telegraphProtected,true);assert.ok(p.recoveryScale<=.2);}});
test('phase 3416 boss render composes recovery-stagger handoff with presentation-only audit',async()=>{assert.match(source,/bossRecoveryStaggerHandoffPresentation/);assert.match(source,/bossRecoveryStaggerHandoff/);assert.match(source,/bossStaggerScale/);const a=await import('../dist/game/boss-recovery-stagger-handoff-audit.js');const r=a.runBossRecoveryStaggerHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
