import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-cluster-anchor-lineage-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-cluster-anchor-lineage-rendering.js');}
const live=(key,x=0,y=0)=>({key,x,y,ttl:.2,retired:false});const retired=(key,x=0,y=0)=>({key,x,y,ttl:.2,retired:true});
test('phase 3225 secondary impact anchor lineage module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactClusterAnchorLineagePresentation,'function');});
test('phase 3226 one active lineage elects exactly one count-label anchor',async()=>{const m=await load();const r=m.secondaryImpactClusterAnchorLineagePresentation({entries:[live('lineage-1')],nextId:2},[{pos:{x:-4,y:0},heldCount:3},{pos:{x:4,y:0},heldCount:3}],false);assert.equal(r.filter(v=>v.anchorOwner).length,1);const owner=r.find(v=>v.anchorOwner);assert.equal(owner.stableClusterKey,'lineage-1');assert.equal(owner.displayCount,3);assert.equal(owner.labelText,'×3');});
test('phase 3227 retired child lineage can never own a surviving count label after merge',async()=>{const m=await load();const r=m.secondaryImpactClusterAnchorLineagePresentation({entries:[retired('child-old',-8,0),live('merged-live',10,0)],nextId:3},[{pos:{x:-6,y:0},heldCount:4},{pos:{x:12,y:0},heldCount:4}],false);assert.equal(r.some(v=>v.anchorOwner&&v.stableClusterKey==='child-old'),false);assert.equal(r.some(v=>v.anchorOwner&&v.stableClusterKey==='merged-live'),true);});
test('phase 3228 rapid re-split assigns anchors only to fresh active child keys',async()=>{const m=await load();const state={entries:[retired('child-old',0,0),live('child-new-a',-34,0),live('child-new-b',34,0)],nextId:4};const r=m.secondaryImpactClusterAnchorLineagePresentation(state,[{pos:{x:-34,y:0},heldCount:2},{pos:{x:34,y:0},heldCount:2}],false);const keys=r.filter(v=>v.anchorOwner).map(v=>v.stableClusterKey).sort();assert.deepEqual(keys,['child-new-a','child-new-b']);});
test('phase 3229 only anchor owner carries held count label and reduced flash cannot raise label alpha',async()=>{const m=await load();const state={entries:[live('lineage-1')],nextId:2},impacts=[{pos:{x:-3,y:0},heldCount:5},{pos:{x:3,y:0},heldCount:5}];const normal=m.secondaryImpactClusterAnchorLineagePresentation(state,impacts,false),reduced=m.secondaryImpactClusterAnchorLineagePresentation(state,impacts,true);assert.equal(normal.filter(v=>v.labelText==='×5').length,1);assert.equal(normal.filter(v=>!v.anchorOwner).every(v=>v.displayCount===0&&v.labelText===''),true);assert.ok(Math.max(...reduced.map(v=>v.labelAlphaScale))<=Math.max(...normal.map(v=>v.labelAlphaScale)));});
test('phase 3230 spell rendering consumes cycle-safe anchor ownership with presentation-only audit',async()=>{const s=spellSource();assert.match(s,/secondaryImpactClusterAnchorLineagePresentation/);assert.match(s,/anchorOwner/);assert.match(s,/labelText/);const a=await import('../dist/game/secondary-impact-cluster-anchor-lineage-audit.js');const r=a.runSecondaryImpactClusterAnchorLineageAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});