import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-secondary-recovery-gate-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4179 projectile secondary recovery opens gradually after settle',async()=>{const {projectileSecondaryRecoveryGatePresentation}=await load();const low=projectileSecondaryRecoveryGatePresentation({release:.1,stress:1,critical:false},false,false),high=projectileSecondaryRecoveryGatePresentation({release:.9,stress:1,critical:false},false,false);assert.ok(low.secondaryScale<high.secondaryScale);assert.equal(low.canonicalScale,1);assert.ok(high.secondaryScale<=1);});
test('Phase 4180 impact fill recovery stays gated while edge remains canonical',async()=>{const {impactSecondaryRecoveryGatePresentation}=await load();const p=impactSecondaryRecoveryGatePresentation({release:.2,stress:.9,critical:true},false,false);assert.ok(p.secondaryScale<.82);assert.equal(p.canonicalScale,1);});
test('Phase 4181 hazard interior recovery cannot outrun danger boundary',async()=>{const {hazardSecondaryRecoveryGatePresentation}=await load();const p=hazardSecondaryRecoveryGatePresentation({release:.15,stress:1,critical:true},false,false);assert.ok(p.secondaryScale<.82);assert.equal(p.canonicalScale,1);});
test('Phase 4182 safe lane decoration returns after path ownership',async()=>{const {safeLaneSecondaryRecoveryGatePresentation}=await load();const p=safeLaneSecondaryRecoveryGatePresentation({release:.15,stress:1,critical:true},false,false);assert.ok(p.secondaryScale<.82);assert.equal(p.canonicalScale,1);});
test('Phase 4183 specialist recovery trail returns after silhouette ownership',async()=>{const {specialistSecondaryRecoveryGatePresentation}=await load();const p=specialistSecondaryRecoveryGatePresentation({release:.2,stress:1,critical:true},false,false);assert.ok(p.secondaryScale<.82);assert.equal(p.canonicalScale,1);});
test('Phase 4184 recovery gate budget never boosts secondary layers',async()=>{const {secondaryRecoveryGateBudgetPresentation}=await load();const p=secondaryRecoveryGateBudgetPresentation({criticalCount:2,stress:1,release:.2},false,false);assert.equal(p.canonicalScale,1);assert.ok(p.secondaryScale<=1);assert.ok(p.secondaryScale<.85);});
test('Phase 4179-4184 live renderers consume secondary recovery gates',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileSecondaryRecoveryGatePresentation/);assert.match(e,/specialistSecondaryRecoveryGatePresentation/);assert.match(s,/impactSecondaryRecoveryGatePresentation/);assert.match(g,/hazardSecondaryRecoveryGatePresentation/);assert.match(g,/safeLaneSecondaryRecoveryGatePresentation/);assert.match(e,/projectileSecondaryRecoveryGate\.secondaryScale/);});
