import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-ground-origin-rebase-rendering.ts',import.meta.url);
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-ground-origin-rebase-rendering.js');}

test('phase 3033 boss ground origin rebase module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceBossGroundOriginRebaseState,'function');assert.equal(typeof mod.bossGroundOriginRebasePresentation,'function');});
test('phase 3034 large boss displacement creates a bounded trailing ground origin instead of teleporting contact cues',async()=>{const {advanceBossGroundOriginRebaseState,bossGroundOriginRebasePresentation}=await loadModule();let s=advanceBossGroundOriginRebaseState(undefined,{x:100,y:100,phase:1,cycle:0},.016,30,false);s=advanceBossGroundOriginRebaseState(s,{x:185,y:100,phase:1,cycle:1},.016,30,false);const p=bossGroundOriginRebasePresentation(s,false);assert.ok(s.rebase>.7);assert.ok(s.offsetX<0&&Math.abs(s.offsetX)<=18);assert.ok(Math.abs(p.groundOffsetX)<=18);assert.ok(p.contactPulseScale<.4);});
test('phase 3035 phase transition rebases contact pulse even when the boss position barely changes',async()=>{const {advanceBossGroundOriginRebaseState,bossGroundOriginRebasePresentation}=await loadModule();let s=advanceBossGroundOriginRebaseState(undefined,{x:220,y:180,phase:1,cycle:2},.016,34,false);s=advanceBossGroundOriginRebaseState(s,{x:221,y:180,phase:2,cycle:2},.016,34,false);const p=bossGroundOriginRebasePresentation(s,false);assert.ok(s.rebase>=.5);assert.ok(p.contactPulseScale<=.55);assert.ok(Math.abs(p.groundOffsetX)<3);});
test('phase 3036 a new special cycle also rebases ground cues and suppresses stale settle pulses',async()=>{const {advanceBossGroundOriginRebaseState,bossGroundOriginRebasePresentation}=await loadModule();let s=advanceBossGroundOriginRebaseState(undefined,{x:300,y:240,phase:2,cycle:4},.016,36,false);s=advanceBossGroundOriginRebaseState(s,{x:304,y:241,phase:2,cycle:5},.016,36,false);const p=bossGroundOriginRebasePresentation(s,false);assert.ok(s.rebase>=.45);assert.ok(p.contactPulseScale<.65);assert.ok(p.shadowMotionScale<1);});
test('phase 3037 rebase decays back to the current ground origin and reduced motion tightens trail distance',async()=>{const {advanceBossGroundOriginRebaseState,bossGroundOriginRebasePresentation}=await loadModule();let s=advanceBossGroundOriginRebaseState(undefined,{x:100,y:100,phase:1,cycle:0},.016,30,false);s=advanceBossGroundOriginRebaseState(s,{x:180,y:120,phase:1,cycle:1},.016,30,false);const full=Math.abs(s.offsetX)+Math.abs(s.offsetY);let r=advanceBossGroundOriginRebaseState(undefined,{x:100,y:100,phase:1,cycle:0},.016,30,true);r=advanceBossGroundOriginRebaseState(r,{x:180,y:120,phase:1,cycle:1},.016,30,true);assert.ok(Math.abs(r.offsetX)+Math.abs(r.offsetY)<full);for(let i=0;i<6;i++)s=advanceBossGroundOriginRebaseState(s,{x:180,y:120,phase:1,cycle:1},.08,30,false);const p=bossGroundOriginRebasePresentation(s,false);assert.ok(s.rebase<.08);assert.ok(Math.abs(p.groundOffsetX)<.5);assert.ok(p.contactPulseScale>.9);});
test('phase 3038 boss update and render share rebase state across shadow and contact pulse and audit stays presentation-only',async()=>{assert.match(enemySource,/bossGroundOriginRebase/);assert.match(enemySource,/advanceBossGroundOriginRebaseState/);assert.match(enemySource,/bossGroundOriginRebasePresentation/);assert.match(enemySource,/bossGroundRebase\.groundOffsetX/);assert.match(enemySource,/bossGroundRebase\.contactPulseScale/);assert.equal(fs.existsSync(new URL('../src/game/boss-ground-origin-rebase-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-ground-origin-rebase-audit.js');const audit=mod.runBossGroundOriginRebaseAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
