import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-cleared-ground-geometry-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-cleared-ground-geometry-rendering.js');}
test('phase 3177 boss cleared-ground geometry module exists',async()=>{const m=await load();assert.equal(typeof m.bossClearedGroundGeometryPresentation,'function');});
test('phase 3178 circular hazards retain circular memory',async()=>{const {bossClearedGroundGeometryPresentation}=await load();const p=bossClearedGroundGeometryPresentation({geometryShape:undefined,radius:70,angle:0,length:0,alpha:.16},false);assert.equal(p.shape,'circle');assert.ok(p.radius>=60);});
test('phase 3179 corridor hazards retain directional cleared lane memory',async()=>{const {bossClearedGroundGeometryPresentation}=await load();const p=bossClearedGroundGeometryPresentation({geometryShape:'corridor',radius:54,angle:.8,length:330,alpha:.16},false);assert.equal(p.shape,'corridor');assert.ok(p.halfLength>120);assert.equal(p.angle,.8);});
test('phase 3180 cross hazards retain orthogonal geometry without extra hazard ownership',async()=>{const {bossClearedGroundGeometryPresentation}=await load();const p=bossClearedGroundGeometryPresentation({geometryShape:'cross',radius:64,angle:1.2,length:280,alpha:.16},false);assert.equal(p.shape,'cross');assert.ok(p.halfLength>100);assert.ok(p.alpha<=.2);});
test('phase 3181 reduced flash compresses geometry memory only',async()=>{const {bossClearedGroundGeometryPresentation}=await load();const a=bossClearedGroundGeometryPresentation({geometryShape:'corridor',radius:54,angle:0,length:320,alpha:.18},false),b=bossClearedGroundGeometryPresentation({geometryShape:'corridor',radius:54,angle:0,length:320,alpha:.18},true);assert.equal(a.shape,b.shape);assert.ok(b.alpha<a.alpha);});
test('phase 3182 live expiry carries geometry into cleared memory with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/geometryShape/);assert.match(s,/bossClearedGroundGeometryPresentation/);assert.match(s,/queueBossHazardAftermathVfx\(hazard\.kind,hazard\.pos\.x,hazard\.pos\.y,hazard\.radius/);const a=await import('../dist/game/boss-cleared-ground-geometry-audit.js');const r=a.runBossClearedGroundGeometryAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
