import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-dense-rhythm-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now()+Math.random());}
test('Phase 4203 dense projectile rhythm admits fewer old secondary peaks',async()=>{const {denseProjectileThreatRhythmPresentation}=await load();const newest=denseProjectileThreatRhythmPresentation({activeCount:12,indexFromNewest:0,phase:.5,stress:1,critical:false}),old=denseProjectileThreatRhythmPresentation({activeCount:12,indexFromNewest:3,phase:.5,stress:1,critical:false});assert.equal(newest.primaryScale,1);assert.ok(newest.secondaryScale>old.secondaryScale);});
test('Phase 4204 dense impact rhythm preserves critical response ownership',async()=>{const {denseImpactThreatRhythmPresentation}=await load();const p=denseImpactThreatRhythmPresentation({activeCount:14,indexFromNewest:3,phase:.5,stress:1,critical:true});assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale>=.48&&p.secondaryScale<=1);});
test('Phase 4205 dense hazard rhythm bounds secondary material under pressure',async()=>{const {denseHazardThreatRhythmPresentation}=await load();const p=denseHazardThreatRhythmPresentation({activeCount:16,indexFromNewest:5,phase:.3,stress:1,critical:false},false,true);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4206 dense safe lane rhythm preserves canonical path scale',async()=>{const {denseSafeLaneThreatRhythmPresentation}=await load();const p=denseSafeLaneThreatRhythmPresentation({activeCount:15,indexFromNewest:0,phase:.5,stress:1,critical:true});assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);});
test('Phase 4207 dense specialist rhythm is deterministic for a stable rank',async()=>{const {denseSpecialistThreatRhythmPresentation}=await load();const a=denseSpecialistThreatRhythmPresentation({activeCount:11,indexFromNewest:7,phase:.4,stress:.8,critical:false}),b=denseSpecialistThreatRhythmPresentation({activeCount:11,indexFromNewest:7,phase:.4,stress:.8,critical:false});assert.deepEqual(a,b);});
test('Phase 4208 unified dense cadence budget exposes one peak at extreme density',async()=>{const {denseThreatRhythmBudgetPresentation}=await load();const p=denseThreatRhythmBudgetPresentation({activeCount:16,criticalCount:2,stress:1,safeLaneVisible:true});assert.equal(p.maxConcurrentPeaks,1);assert.equal(p.primaryScale,1);assert.equal(p.safeLaneScale,1);assert.ok(p.secondaryScale<1);});
test('Phase 4203-4208 dense arbitration assigns distinct family slots at same battlefield rank',async()=>{const m=await load();const input={activeCount:14,indexFromNewest:0,phase:.5,stress:1,critical:false};const values=[m.denseProjectileThreatRhythmPresentation(input),m.denseImpactThreatRhythmPresentation(input),m.denseHazardThreatRhythmPresentation(input),m.denseSafeLaneThreatRhythmPresentation(input),m.denseSpecialistThreatRhythmPresentation(input)];assert.equal(new Set(values.map((value)=>value.slot)).size,5);assert.equal(values.filter((value)=>value.admitted).length,1);});
test('Phase 4208 dense budget reserves secondary capacity when safe lane is visible',async()=>{const {denseThreatRhythmBudgetPresentation}=await load();const base={activeCount:16,criticalCount:1,stress:.8};const absent=denseThreatRhythmBudgetPresentation({...base,safeLaneVisible:false}),present=denseThreatRhythmBudgetPresentation({...base,safeLaneVisible:true});assert.equal(present.safeLaneScale,1);assert.ok(present.secondaryScale<=absent.secondaryScale-.07);});
test('Phase 4203-4208 live renderers consume dense threat rhythm helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/denseProjectileThreatRhythmPresentation/);assert.match(e,/denseSpecialistThreatRhythmPresentation/);assert.match(s,/denseImpactThreatRhythmPresentation/);assert.match(g,/denseHazardThreatRhythmPresentation/);assert.match(g,/denseSafeLaneThreatRhythmPresentation/);assert.match(e,/projectileDenseRhythm\.secondaryScale/);});
