import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/specialist-ground-contact-ownership-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/specialist-ground-contact-ownership-rendering.js');}

test('phase 3009 specialist ground contact ownership module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.specialistGroundContactOwnershipPresentation,'function');});
test('phase 3010 ordinary locomotion keeps shadow and ground cues fully attached',async()=>{const mod=await loadModule();const p=mod.specialistGroundContactOwnershipPresentation('assassin',{motion:.9,attackCommitment:0,hitStagger:0,fatal:false,groundAnchor:0,attackOffsetX:0,hitOffsetX:0},false);assert.equal(p.owner,'locomotion');assert.equal(p.locomotionScale,1);assert.equal(p.shadowOffsetScale,1);assert.equal(p.groundPulseScale,1);});
test('phase 3011 committed attack anchors the shadow while preserving a bounded attack-direction follow',async()=>{const mod=await loadModule();const p=mod.specialistGroundContactOwnershipPresentation('shieldbearer',{motion:.7,attackCommitment:.9,hitStagger:.4,fatal:false,groundAnchor:.45,attackOffsetX:8,hitOffsetX:-4},false);assert.equal(p.owner,'attack');assert.ok(p.locomotionScale<.55);assert.ok(p.shadowOffsetScale<.5);assert.ok(p.groundFollowX>0);assert.ok(p.groundFollowX<3.5);});
test('phase 3012 reaction ownership follows only a small fraction of hit displacement so feet do not slide',async()=>{const mod=await loadModule();const p=mod.specialistGroundContactOwnershipPresentation('nullifier',{motion:.4,attackCommitment:.05,hitStagger:.95,fatal:false,groundAnchor:.1,attackOffsetX:5,hitOffsetX:-7},false);assert.equal(p.owner,'reaction');assert.ok(p.groundFollowX<0);assert.ok(Math.abs(p.groundFollowX)<2.5);assert.ok(p.shadowOffsetScale<.5);assert.ok(p.turnStopScale<.65);});
test('phase 3013 fatal transition clears ground pulses and reduced motion preserves owner identity',async()=>{const mod=await loadModule();const full=mod.specialistGroundContactOwnershipPresentation('siegeGolem',{motion:.7,attackCommitment:.9,hitStagger:1,fatal:true,groundAnchor:1,attackOffsetX:8,hitOffsetX:-8},false);const reduced=mod.specialistGroundContactOwnershipPresentation('siegeGolem',{motion:.7,attackCommitment:.9,hitStagger:1,fatal:true,groundAnchor:1,attackOffsetX:8,hitOffsetX:-8},true);assert.equal(full.owner,'fatal');assert.equal(reduced.owner,'fatal');assert.equal(full.groundPulseScale,0);assert.equal(full.shadowOffsetScale,0);assert.equal(full.groundFollowX,0);});
test('phase 3014 specialist render shares ownership with shadow and pulse and audit stays presentation-only',async()=>{assert.match(enemySource,/specialistGroundContactOwnershipPresentation/);assert.match(enemySource,/specialistGroundOwnership\.groundFollowX/);assert.match(enemySource,/specialistGroundOwnership\.shadowOffsetScale/);assert.match(enemySource,/specialistGroundOwnership\.groundPulseScale/);assert.equal(fs.existsSync(new URL('../src/game/specialist-ground-contact-ownership-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-ground-contact-ownership-audit.js');const audit=mod.runSpecialistGroundContactOwnershipAudit();assert.equal(audit.samples.length,96);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
