import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const u=new URL('../src/game/core-guard-visual-load-budget-rendering.ts',import.meta.url);const game=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(u),true);return import('../dist/game/core-guard-visual-load-budget-rendering.js');}
test('phase 3291 core guard visual-load budget module exists',async()=>{const m=await load();assert.equal(typeof m.coreGuardVisualLoadBudgetPresentation,'function');});
test('phase 3292 light single-source guard cues preserve their authored alpha',async()=>{const m=await load();const p=m.coreGuardVisualLoadBudgetPresentation({coreHitAlphaScale:.42,projectileAccentAlpha:.18,contactAccentAlpha:0,mitigationRatio:.22,mixedPressure:false},false);assert.ok(p.coreHitAlphaScale>.85);assert.ok(p.accentAlphaScale>.85);});
test('phase 3293 dense mixed-source guard composition stays inside one visual-load cap',async()=>{const m=await load();const p=m.coreGuardVisualLoadBudgetPresentation({coreHitAlphaScale:1,projectileAccentAlpha:.48,contactAccentAlpha:.42,mitigationRatio:.62,mixedPressure:true},false);assert.ok(p.combinedVisualLoad<=p.visualLoadCap+1e-9);assert.ok(p.coreHitAlphaScale<=1);assert.ok(p.accentAlphaScale<=1);});
test('phase 3294 heavily mitigated core hits yield more damage-cue alpha than guard accents',async()=>{const m=await load();const p=m.coreGuardVisualLoadBudgetPresentation({coreHitAlphaScale:1,projectileAccentAlpha:.48,contactAccentAlpha:.42,mitigationRatio:.9,mixedPressure:true},false);assert.ok(p.coreHitAlphaScale<p.accentAlphaScale);assert.ok(p.guardOwnedBias>.35);});
test('phase 3295 reduced flash lowers the total core guard load cap without erasing identity',async()=>{const m=await load();const full=m.coreGuardVisualLoadBudgetPresentation({coreHitAlphaScale:1,projectileAccentAlpha:.48,contactAccentAlpha:.42,mitigationRatio:.65,mixedPressure:true},false),reduced=m.coreGuardVisualLoadBudgetPresentation({coreHitAlphaScale:1,projectileAccentAlpha:.48,contactAccentAlpha:.42,mitigationRatio:.65,mixedPressure:true},true);assert.ok(reduced.visualLoadCap<full.visualLoadCap);assert.ok(reduced.combinedVisualLoad<=reduced.visualLoadCap+1e-9);assert.ok(reduced.accentAlphaScale>0);});
test('phase 3296 live coreHit render consumes one shared visual-load budget with presentation-only audit',async()=>{const s=game();assert.match(s,/coreGuardVisualLoadBudgetPresentation/);assert.match(s,/coreHitAlphaScale/);assert.match(s,/accentAlphaScale/);const a=await import('../dist/game/core-guard-visual-load-budget-audit.js');const r=a.runCoreGuardVisualLoadBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
