import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/specialist-reaction-lifecycle-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/specialist-reaction-lifecycle-vfx-assets.js');}

test('phase 2523 specialist reaction atlas covers four specialists x trigger aftermath',async()=>{const mod=await load(),audit=mod.auditSpecialistReactionLifecycleVfxAtlas();assert.equal(audit.specialistCount,4);assert.equal(audit.stateCount,2);assert.equal(audit.itemCount,8);assert.equal(audit.uniqueCellCount,8);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.SPECIALIST_REACTION_LIFECYCLE_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:512,height:256});assert.ok(b.length>4500);});
test('phase 2524 shieldbearer guard absorption queues reaction and guard break does not alter damage formula',()=>{assert.match(enemySource,/blocked = Math\.min\(enemy\.guardHp \?\? 0, remaining \* 0\.72\)/);assert.match(enemySource,/queueSpecialistReactionVfx\(enemy,'shieldbearer'/);assert.match(enemySource,/guardBroken/);});
test('phase 2525 assassin blink records actual destination reaction without changing blink reset',()=>{assert.match(enemySource,/assassinBlinkPosition\(enemy\.pos, ctx\.hero\.pos\)/);assert.match(enemySource,/queueSpecialistReactionVfx\(enemy,'assassin'/);assert.match(enemySource,/SPECIALIST_COMBAT_CONTRACT\.assassinBlinkResetSeconds/);});
test('phase 2526 siege golem contact attack queues slam reaction after existing target selection',()=>{assert.match(enemySource,/enemy\.type === 'siegeGolem'[\s\S]*queueSpecialistReactionVfx\(enemy,'siegeGolem'/);assert.match(enemySource,/if \(enemy\.target === 'core'\) ctx\.onCoreDamage/);});
test('phase 2527 nullifier entry reaction is edge-triggered bounded resettable and fail-open',()=>{assert.match(enemySource,/nullifierHeroInside/);assert.match(enemySource,/queueSpecialistReactionVfx\(enemy,'nullifier'/);assert.match(enemySource,/specialistReactionVfx\.length > 24/);assert.match(enemySource,/this\.specialistReactionVfx = \[\]/);assert.match(gameSource,/initializeSpecialistReactionLifecycleVfxAtlas/);});
test('phase 2528 specialist reaction lifecycle audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/specialist-reaction-lifecycle-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-reaction-lifecycle-vfx-audit.js'),audit=mod.runSpecialistReactionLifecycleVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/specialistReactionLifecycleVfxPassed/);assert.match(candidateSource,/specialistReactionLifecycleVfxPassed/);assert.match(candidateSource,/specialist-reaction-lifecycle-vfx/);});
