import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/boss-safe-response-slot-hysteresis.ts',import.meta.url),'utf8');const game=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const freeze=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');const candidate=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');const mod=fs.existsSync(new URL('../dist/game/boss-safe-response-slot-hysteresis.js',import.meta.url))?await import('../dist/game/boss-safe-response-slot-hysteresis.js'):null;
const place=(slot,x,y,visible=true)=>({visible,slot,pos:{x,y},animated:false,motionAmplitude:0,presentationOnly:true});const input=(bossPos={x:500,y:400},heroPos={x:120,y:400},corePos={x:1150,y:400},extraProtected=[])=>({bossPos,bossRadius:70,heroPos,corePos,width:1280,height:800,extraProtected});
test('phase 2781 crossing the displacement guard with the same strict slot rebases the held anchor instead of snapping to strict position',()=>{assert.ok(mod?.bossSafeResponseSameSlotRebase);if(!mod)return;let r=mod.bossSafeResponseSlotHysteresis({previous:null,current:place('above',500,290),placementInput:input(),bossId:7,cycle:4,now:10});r=mod.bossSafeResponseSlotHysteresis({previous:r.memory,current:place('above',610,282),placementInput:input({x:610,y:390}),bossId:7,cycle:4,now:10.05});assert.equal(r.placement.slot,'above');assert.deepEqual(r.placement.pos,{x:610,y:280});assert.deepEqual(r.memory?.bossPos,{x:610,y:390});assert.deepEqual(r.memory?.pos,{x:610,y:280});});
test('phase 2782 same-slot rebase refreshes the hold window from the current time',()=>{assert.ok(mod?.bossSafeResponseSameSlotRebase);if(!mod)return;let r=mod.bossSafeResponseSlotHysteresis({previous:null,current:place('above',500,290),placementInput:input(),bossId:7,cycle:4,now:10});r=mod.bossSafeResponseSlotHysteresis({previous:r.memory,current:place('above',610,282),placementInput:input({x:610,y:390}),bossId:7,cycle:4,now:10.05});assert.ok((r.memory?.holdUntil??0)>10.2);});
test('phase 2783 a displacement-guard handoff that requires a different strict slot releases immediately instead of rebasing',()=>{assert.ok(mod?.bossSafeResponseSameSlotRebase);if(!mod)return;let r=mod.bossSafeResponseSlotHysteresis({previous:null,current:place('above',500,290),placementInput:input(),bossId:7,cycle:4,now:10});r=mod.bossSafeResponseSlotHysteresis({previous:r.memory,current:place('right',760,390),placementInput:input({x:610,y:390}),bossId:7,cycle:4,now:10.05});assert.equal(r.placement.slot,'right');assert.deepEqual(r.placement.pos,{x:760,y:390});});
test('phase 2784 an unsafe followed position cannot be preserved merely because strict slot identity is unchanged',()=>{assert.ok(mod?.bossSafeResponseSameSlotRebase);if(!mod)return;let r=mod.bossSafeResponseSlotHysteresis({previous:null,current:place('above',500,290),placementInput:input(),bossId:7,cycle:4,now:10});const moved={x:610,y:390};const unsafe={x:610,y:280,radius:40};r=mod.bossSafeResponseSlotHysteresis({previous:r.memory,current:place('above',610,282),placementInput:input(moved,{x:120,y:400},{x:1150,y:400},[unsafe]),bossId:7,cycle:4,now:10.05});assert.deepEqual(r.placement.pos,{x:610,y:282});});
test('phase 2785 same-slot rebase remains presentation-only and Game keeps the existing showLabel gate and boss ring path',()=>{assert.match(source,/bossSafeResponseSameSlotRebase/);assert.match(source,/BOSS_SAFE_RESPONSE_SLOT_BOSS_DISPLACEMENT_GUARD/);assert.match(game,/if\(presentation\.showLabel\)/);assert.doesNotMatch(source,/boss\.pos\s*=/);});
test('phase 2786 boss safe-response same-slot rebase audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/boss-safe-response-same-slot-rebase-audit.ts',import.meta.url)),true);if(!fs.existsSync(new URL('../dist/game/boss-safe-response-same-slot-rebase-audit.js',import.meta.url)))return;const a=(await import('../dist/game/boss-safe-response-same-slot-rebase-audit.js')).runBossSafeResponseSameSlotRebaseAudit();assert.equal(a.samples.length,64);assert.equal(a.actionCount,9);assert.equal(a.presentationOnly,true);assert.equal(a.gameplayFormulaMutation,false);assert.equal(a.snapshotSchemaMutation,false);assert.equal(a.passed,true);assert.match(freeze,/bossSafeResponseSameSlotRebasePassed/);assert.match(candidate,/bossSafeResponseSameSlotRebasePassed/);assert.match(candidate,/boss-safe-response-same-slot-rebase/);});
