import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const enemies=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');const game=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const freeze=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');const candidate=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
const exists=fs.existsSync(new URL('../dist/game/spawn-lane-presentation-memory.js',import.meta.url));const mod=exists?await import('../dist/game/spawn-lane-presentation-memory.js'):null;
test('phase 2667 spawn lane memory lasts longer than the 0.72 second portal but stays brief',()=>{assert.ok(mod);if(!mod)return;assert.ok(mod.SPAWN_LANE_MEMORY_SECONDS>.72);assert.ok(mod.SPAWN_LANE_MEMORY_SECONDS<2);});
test('phase 2668 remembering a nearby matching portal refreshes it instead of adding a duplicate',()=>{assert.ok(mod);if(!mod)return;let mem=[];mem=mod.rememberSpawnLanePortal(mem,{pos:{x:20,y:100},kind:'regular',target:'hero'});const first=mem[0];mem=mod.rememberSpawnLanePortal(mod.advanceSpawnLaneMemory(mem,.5),{pos:{x:28,y:106},kind:'regular',target:'hero'});assert.equal(mem.length,1);assert.ok(mem[0].ttl>first.ttl-.5);assert.ok(mem[0].pos.x>20);});
test('phase 2669 presentation memory expires deterministically without mutating the input array',()=>{assert.ok(mod);if(!mod)return;const mem=mod.rememberSpawnLanePortal([],{pos:{x:20,y:100},kind:'elite',target:'core'});const copy=structuredClone(mem);const next=mod.advanceSpawnLaneMemory(mem,mod.SPAWN_LANE_MEMORY_SECONDS+.01);assert.deepEqual(mem,copy);assert.equal(next.length,0);});
test('phase 2670 memory cap preserves boss and elite entries before routine lanes',()=>{assert.ok(mod);if(!mod)return;let mem=[];for(let i=0;i<20;i++)mem=mod.rememberSpawnLanePortal(mem,{pos:{x:i*70,y:i%2?10:710},kind:i===0?'boss':i===1?'elite':'regular',target:i%2?'hero':'core'});assert.ok(mem.length<=mod.SPAWN_LANE_MEMORY_LIMIT);assert.equal(mem.some(x=>x.kind==='boss'),true);assert.equal(mem.some(x=>x.kind==='elite'),true);});
test('phase 2671 EnemyManager owns presentation-only lane memory and Game consumes memory views instead of raw portal TTL views',()=>{assert.match(enemies,/spawnLaneMemory/);assert.match(enemies,/spawnLanePresentationViews\(\)/);assert.match(enemies,/rememberSpawnLanePortal/);assert.match(enemies,/advanceSpawnLaneMemory/);assert.match(game,/portals:this\.enemies\.spawnLanePresentationViews\(\)/);});
test('phase 2672 spawn lane memory audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/spawn-lane-presentation-memory-audit.ts',import.meta.url)),true);if(!fs.existsSync(new URL('../dist/game/spawn-lane-presentation-memory-audit.js',import.meta.url)))return;const a=(await import('../dist/game/spawn-lane-presentation-memory-audit.js')).runSpawnLanePresentationMemoryAudit();assert.equal(a.samples.length,64);assert.equal(a.actionCount,9);assert.equal(a.presentationOnly,true);assert.equal(a.gameplayFormulaMutation,false);assert.equal(a.snapshotSchemaMutation,false);assert.equal(a.passed,true);assert.match(freeze,/spawnLanePresentationMemoryPassed/);assert.match(candidate,/spawnLanePresentationMemoryPassed/);assert.match(candidate,/spawn-lane-presentation-memory/);});
