import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
async function load(){return import('../dist/game/character-silhouette-trail-budget-rendering.js');}const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const input=(owner='locomotion',pivot=.2)=>({owner,pivotWeight:pivot,baseAlpha:.6,trailDistanceScale:1,motionLayerActive:owner!=='locomotion'});
test('phase 3495 neutral locomotion keeps ordinary silhouette trail budget',async()=>{const m=await load();const p=m.characterSilhouetteTrailBudgetPresentation(input(),false);assert.equal(p.alphaScale,1);assert.equal(p.trailDistanceScale,1);});
test('phase 3496 strong hit pivot shortens the trail so the ghost does not cross the body',async()=>{const m=await load();const p=m.characterSilhouetteTrailBudgetPresentation(input('hit',.9),false);assert.ok(p.trailDistanceScale<.75);assert.ok(p.alphaScale<.8);});
test('phase 3497 boss special keeps more identity trail than recovery at equal pivot',async()=>{const m=await load();const special=m.characterSilhouetteTrailBudgetPresentation(input('special',.7),false),recovery=m.characterSilhouetteTrailBudgetPresentation(input('recovery',.7),false);assert.ok(special.alphaScale>recovery.alphaScale);});
test('phase 3498 larger pivot monotonically reduces trail distance for attack ownership',async()=>{const m=await load();const low=m.characterSilhouetteTrailBudgetPresentation(input('attack',.45),false),high=m.characterSilhouetteTrailBudgetPresentation(input('attack',.9),false);assert.ok(high.trailDistanceScale<low.trailDistanceScale);});
test('phase 3499 reduced motion caps trail alpha and distance without changing owner identity',async()=>{const m=await load();const p=m.characterSilhouetteTrailBudgetPresentation(input('special',.6),true);assert.equal(p.owner,'special');assert.ok(p.alphaScale<=.55);assert.ok(p.trailDistanceScale<=.6);});
test('phase 3500 live specialist and boss dynamic silhouettes consume the trail budget',async()=>{const s=source();assert.match(s,/characterSilhouetteTrailBudgetPresentation/);assert.match(s,/silhouetteTrailBudget\.alphaScale/);assert.match(s,/silhouetteTrailBudget\.trailDistanceScale/);const a=await import('../dist/game/character-silhouette-trail-budget-audit.js');const r=a.runCharacterSilhouetteTrailBudgetAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
