import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/safe-lane-transition-forecast-agreement-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/safe-lane-transition-forecast-agreement-rendering.js');}
const current={x:120,y:200},next={x:420,y:160};
test('phase 3231 safe-lane transition forecast agreement module exists',async()=>{const m=await load();assert.equal(typeof m.safeLaneTransitionForecastAgreementPresentation,'function');});
test('phase 3232 stable distant forecast keeps transition vfx and geometry icon on current target',async()=>{const m=await load();const p=m.safeLaneTransitionForecastAgreementPresentation({currentTarget:current,currentConfidence:.74,nextTarget:next,forecastUrgency:.4,transitionMs:3200},false);assert.equal(p.owner,'current');assert.deepEqual(p.target,current);assert.deepEqual(p.transitionVfxTarget,current);assert.deepEqual(p.geometryIconTarget,current);});
test('phase 3233 imminent high urgency forecast promotes one shared visual target before transition',async()=>{const m=await load();const p=m.safeLaneTransitionForecastAgreementPresentation({currentTarget:current,currentConfidence:.72,nextTarget:next,forecastUrgency:.84,transitionMs:900},false);assert.equal(p.owner,'forecast');assert.deepEqual(p.target,next);assert.deepEqual(p.transitionVfxTarget,next);assert.deepEqual(p.geometryIconTarget,next);assert.deepEqual(p.labelTarget,next);});
test('phase 3234 forecast selection exactly agrees with cleared-ground target arbitration threshold',async()=>{const f=await import('../dist/game/boss-cleared-safe-lane-forecast-arbitration-rendering.js');const m=await load();const input={currentTarget:current,currentConfidence:.68,nextTarget:next,forecastUrgency:.65,transitionMs:1800};const ground=f.bossClearedSafeLaneForecastTarget(input,false),visual=m.safeLaneTransitionForecastAgreementPresentation(input,false);assert.equal(visual.owner,ground.owner);assert.deepEqual(visual.target,ground.target);});
test('phase 3235 reduced flash changes intensity only and never selected visual target',async()=>{const m=await load();const input={currentTarget:current,currentConfidence:.72,nextTarget:next,forecastUrgency:.9,transitionMs:700};const normal=m.safeLaneTransitionForecastAgreementPresentation(input,false),reduced=m.safeLaneTransitionForecastAgreementPresentation(input,true);assert.deepEqual(reduced.target,normal.target);assert.deepEqual(reduced.transitionVfxTarget,normal.transitionVfxTarget);assert.ok(reduced.alphaScale<=normal.alphaScale);});
test('phase 3236 game reuses one forecast visual target for path label and geometry identity with presentation-only audit',async()=>{const g=gameSource();assert.match(g,/safeLaneTransitionForecastAgreementPresentation/);assert.match(g,/transitionVfxTarget/);assert.match(g,/geometryIconTarget/);assert.match(g,/labelTarget/);const a=await import('../dist/game/safe-lane-transition-forecast-agreement-audit.js');const r=a.runSafeLaneTransitionForecastAgreementAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});