import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/boss-special-recovery-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-special-recovery-rendering.js');}

test('phase 2961 boss special recovery module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceBossSpecialRecoveryState,'function');assert.equal(typeof mod.bossSpecialRecoveryPresentation,'function');});
test('phase 2962 inferno rebounds while juggernaut follows through after confirmed special',async()=>{const mod=await loadModule();const state=mod.advanceBossSpecialRecoveryState(undefined,true,0.016,'inferno');const fire=mod.bossSpecialRecoveryPresentation('inferno',2,state,1,0,false);const jug=mod.bossSpecialRecoveryPresentation('juggernaut',2,state,1,0,false);assert.ok(fire.recovery>0.8);assert.ok(fire.offsetX<0);assert.ok(jug.offsetX>0);assert.notEqual(fire.stance,jug.stance);});
test('phase 2963 summoner and abyss witch descend while twin maw counter-yaws after release',async()=>{const mod=await loadModule();const s=mod.advanceBossSpecialRecoveryState(undefined,true,0.016,'summoner');const summon=mod.bossSpecialRecoveryPresentation('summoner',3,s,0,1,false);const witch=mod.bossSpecialRecoveryPresentation('abyssWitch',3,s,0,1,false);const twin=mod.bossSpecialRecoveryPresentation('twinMaw',3,s,1,0,false);assert.ok(summon.offsetY>0);assert.ok(witch.offsetY>0);assert.ok(twin.rotation<0);assert.ok(Math.abs(twin.rotation)>0.02);});
test('phase 2964 recovery decays completely and leaves no residual body transform',async()=>{const mod=await loadModule();let s=mod.advanceBossSpecialRecoveryState(undefined,true,0.016,'timeEater');for(let i=0;i<80;i++)s=mod.advanceBossSpecialRecoveryState(s,false,0.05,'timeEater');const p=mod.bossSpecialRecoveryPresentation('timeEater',1,s,1,0,false);assert.equal(s.recovery,0);assert.equal(p.offsetX,0);assert.equal(p.offsetY,0);assert.equal(p.rotation,0);assert.equal(p.scaleX,1);assert.equal(p.scaleY,1);});
test('phase 2965 reduced motion preserves recovery state and stance while compressing transform',async()=>{const mod=await loadModule();const s=mod.advanceBossSpecialRecoveryState(undefined,true,0.016,'juggernaut');const full=mod.bossSpecialRecoveryPresentation('juggernaut',3,s,1,0,false);const reduced=mod.bossSpecialRecoveryPresentation('juggernaut',3,s,1,0,true);assert.equal(reduced.recovery,full.recovery);assert.equal(reduced.stance,full.stance);assert.ok(Math.abs(reduced.offsetX)<Math.abs(full.offsetX));assert.ok(Math.abs(reduced.rotation)<=Math.abs(full.rotation));});
test('phase 2966 boss lifecycle triggers recovery only on actual special and deterministic audit stays presentation-only',async()=>{assert.match(enemySource,/bossSpecialRecovery/);assert.match(enemySource,/advanceBossSpecialRecoveryState/);assert.match(enemySource,/bossSpecialRecoveryPresentation/);assert.match(enemySource,/updateBossSpecial/);assert.equal(fs.existsSync(new URL('../src/game/boss-special-recovery-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-special-recovery-audit.js');const audit=mod.runBossSpecialRecoveryAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
