import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-cluster-readability-budget-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-cluster-readability-budget-rendering.js');}
const dense=()=>Array.from({length:8},(_,i)=>({pos:{x:200+(i%4)*8,y:220+Math.floor(i/4)*9},ttl:.12-i*.005,maxTtl:.14}));
test('phase 3153 secondary impact cluster readability budget module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactClusterReadabilityBudgetPresentation,'function');});
test('phase 3154 sparse secondary impacts remain individually readable',async()=>{const {secondaryImpactClusterReadabilityBudgetPresentation}=await load();const r=secondaryImpactClusterReadabilityBudgetPresentation([{pos:{x:80,y:80},ttl:.12,maxTtl:.14},{pos:{x:260,y:220},ttl:.1,maxTtl:.14}],'high',false);assert.equal(r.filter(v=>v.visible).length,2);assert.ok(r.every(v=>v.alphaScale>.8&&v.sizeScale>.9));});
test('phase 3155 dense secondary impacts compress within the shared impact cluster limit',async()=>{const {secondaryImpactClusterReadabilityBudgetPresentation}=await load();const r=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'high',false);assert.ok(r.filter(v=>v.visible).length<=3);assert.ok(r.some(v=>v.clusterCount>=6));assert.ok(r.some(v=>!v.visible));});
test('phase 3156 quality tier tightens dense impact visibility budget',async()=>{const {secondaryImpactClusterReadabilityBudgetPresentation}=await load();const h=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'high',false),m=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'medium',false),l=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'low',false);assert.ok(h.filter(v=>v.visible).length>m.filter(v=>v.visible).length);assert.ok(m.filter(v=>v.visible).length>l.filter(v=>v.visible).length);});
test('phase 3157 reduced flash lowers secondary cluster alpha without changing visibility ownership',async()=>{const {secondaryImpactClusterReadabilityBudgetPresentation}=await load();const f=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'high',false),r=secondaryImpactClusterReadabilityBudgetPresentation(dense(),'high',true);assert.deepEqual(r.map(v=>v.visible),f.map(v=>v.visible));assert.ok(r.filter(v=>v.visible).every((v,i)=>v.alphaScale<=f.filter(x=>x.visible)[i].alphaScale));});
test('phase 3158 splash and chain live paths enter the existing presentation-quality cluster budget',async()=>{const s=spellSource(),g=gameSource();assert.match(s,/secondaryKind\?: SecondaryImpactKind/);assert.match(s,/secondaryKind:'splash'/);assert.match(s,/secondaryKind:'chain'/);assert.match(s,/secondaryImpactClusterReadabilityBudgetPresentation/);assert.match(s,/presentationQuality/);assert.match(g,/this\.presentation\.quality/);const a=await import('../dist/game/secondary-impact-cluster-readability-budget-audit.js');const audit=a.runSecondaryImpactClusterReadabilityBudgetAudit();assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
