import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-cluster-identity-hold-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-cluster-identity-hold-rendering.js');}
test('phase 3171 secondary impact cluster identity hold module exists',async()=>{const m=await load();assert.equal(typeof m.advanceSecondaryImpactClusterIdentityHold,'function');});
test('phase 3172 nearby impacts receive stable spatial identity',async()=>{const m=await load();const s=m.advanceSecondaryImpactClusterIdentityHold(m.createSecondaryImpactClusterIdentityHoldState(),[{pos:{x:201,y:202}},{pos:{x:218,y:214}}],.016);const a=m.secondaryImpactClusterIdentityFor(s,{x:205,y:207});assert.ok(a.key.length>0);assert.equal(a.heldCount,2);});
test('phase 3173 held count survives one-frame cluster shrink',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterIdentityHold(m.createSecondaryImpactClusterIdentityHoldState(),[{pos:{x:200,y:200}},{pos:{x:210,y:205}},{pos:{x:220,y:210}}],.016);s=m.advanceSecondaryImpactClusterIdentityHold(s,[{pos:{x:205,y:205}}],.04);assert.equal(m.secondaryImpactClusterIdentityFor(s,{x:205,y:205}).heldCount,3);});
test('phase 3174 held count decays after bounded hold window',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterIdentityHold(m.createSecondaryImpactClusterIdentityHoldState(),[{pos:{x:200,y:200}},{pos:{x:210,y:205}},{pos:{x:220,y:210}}],.016);s=m.advanceSecondaryImpactClusterIdentityHold(s,[{pos:{x:205,y:205}}],.28);assert.equal(m.secondaryImpactClusterIdentityFor(s,{x:205,y:205}).heldCount,1);});
test('phase 3175 distant clusters do not steal held identity',async()=>{const m=await load();const s=m.advanceSecondaryImpactClusterIdentityHold(m.createSecondaryImpactClusterIdentityHoldState(),[{pos:{x:80,y:80}},{pos:{x:320,y:260}}],.016);assert.notEqual(m.secondaryImpactClusterIdentityFor(s,{x:80,y:80}).key,m.secondaryImpactClusterIdentityFor(s,{x:320,y:260}).key);});
test('phase 3176 live spell path feeds stable cluster key and held count into shared readability budget',async()=>{const s=spellSource();assert.match(s,/secondaryImpactClusterIdentityHold/);assert.match(s,/stableClusterKey/);assert.match(s,/heldCount/);const a=await import('../dist/game/secondary-impact-cluster-identity-hold-audit.js');const r=a.runSecondaryImpactClusterIdentityHoldAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
