import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/safe-lane-forecast-visual-coherence-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/safe-lane-forecast-visual-coherence-rendering.js');}
test('phase 3249 safe-lane visual coherence exposes exact-boundary handoff state',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:500,y:310},currentConfidence:.8,nextTarget:{x:500,y:310},forecastUrgency:.46,transitionMs:900},false);assert.equal(typeof p.bridgeVisible,'boolean');assert.equal(typeof p.handoffSettled,'boolean');});
test('phase 3250 separated imminent forecast keeps a secondary bridge visible',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:500,y:310},currentConfidence:.78,nextTarget:{x:410,y:430},forecastUrgency:.9,transitionMs:600},false);assert.equal(p.forecastPromoted,true);assert.equal(p.bridgeVisible,true);assert.equal(p.handoffSettled,false);});
test('phase 3251 current and next target equality settles the handoff and removes duplicate bridge',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:410,y:430},currentConfidence:.82,nextTarget:{x:410,y:430},forecastUrgency:.46,transitionMs:900},false);assert.equal(p.handoffSettled,true);assert.equal(p.bridgeVisible,false);assert.equal(p.bridgeAlphaScale,0);});
test('phase 3252 tiny target drift at transition boundary is treated as the same new current lane',async()=>{const m=await load();const p=m.safeLaneForecastVisualCoherencePresentation({currentTarget:{x:410,y:430},currentConfidence:.82,nextTarget:{x:414,y:433},forecastUrgency:.46,transitionMs:900},false);assert.equal(p.handoffSettled,true);assert.equal(p.bridgeVisible,false);});
test('phase 3253 reduced flash never re-enables a settled bridge or raises primary emphasis',async()=>{const m=await load();const input={currentTarget:{x:410,y:430},currentConfidence:.82,nextTarget:{x:410,y:430},forecastUrgency:.46,transitionMs:900};const a=m.safeLaneForecastVisualCoherencePresentation(input,false),b=m.safeLaneForecastVisualCoherencePresentation(input,true);assert.equal(a.bridgeVisible,false);assert.equal(b.bridgeVisible,false);assert.ok(b.primaryAlphaScale<=a.primaryAlphaScale);});
test('phase 3254 live mythic rendering gates bridge arc and direction icon through the boundary handoff with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/safeLaneVisual\.bridgeVisible/);assert.match(s,/safeLaneVisual\.handoffSettled/);const a=await import('../dist/game/safe-lane-forecast-visual-coherence-audit.js');const r=a.runSafeLaneForecastVisualCoherenceAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
