import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/boss-heavy-hit-stagger-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-heavy-hit-stagger-rendering.js');}

test('phase 2979 boss heavy hit stagger module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceBossHeavyHitStaggerState,'function');assert.equal(typeof mod.bossHeavyHitStaggerPresentation,'function');});
test('phase 2980 critical boss hits read stronger than heavy hits but remain bounded',async()=>{const mod=await loadModule();const heavy=mod.advanceBossHeavyHitStaggerState(undefined,{tier:'heavy',directionX:-1,directionY:0},0,false);const critical=mod.advanceBossHeavyHitStaggerState(undefined,{tier:'critical',directionX:-1,directionY:0},0,false);const a=mod.bossHeavyHitStaggerPresentation('inferno',1,heavy,4,false);const b=mod.bossHeavyHitStaggerPresentation('inferno',1,critical,4,false);assert.ok(b.stagger>a.stagger);assert.ok(Math.hypot(b.offsetX,b.offsetY)<=8);assert.ok(Math.abs(b.rotation)<=0.16);assert.ok(b.scaleX>=0.9&&b.scaleX<=1.1);assert.ok(b.scaleY>=0.9&&b.scaleY<=1.1);});
test('phase 2981 archetype and phase hierarchy keep juggernaut grounded and late phase more stable',async()=>{const mod=await loadModule();const s=mod.advanceBossHeavyHitStaggerState(undefined,{tier:'critical',directionX:-1,directionY:0.2},0,false);const summon=mod.bossHeavyHitStaggerPresentation('summoner',1,s,4,false);const jug=mod.bossHeavyHitStaggerPresentation('juggernaut',1,s,4,false);const late=mod.bossHeavyHitStaggerPresentation('summoner',3,s,4,false);assert.ok(Math.abs(jug.offsetY)>Math.abs(summon.offsetY));assert.ok(Math.abs(jug.rotation)<Math.abs(summon.rotation));assert.ok(Math.hypot(late.offsetX,late.offsetY)<=Math.hypot(summon.offsetX,summon.offsetY));assert.notEqual(jug.stance,summon.stance);});
test('phase 2982 active boss special telegraph protects body readability from hit stagger',async()=>{const mod=await loadModule();const s=mod.advanceBossHeavyHitStaggerState(undefined,{tier:'critical',directionX:-1,directionY:0},0,false);const open=mod.bossHeavyHitStaggerPresentation('twinMaw',2,s,4,false);const protectedPose=mod.bossHeavyHitStaggerPresentation('twinMaw',2,s,0.8,false);assert.equal(protectedPose.telegraphProtected,true);assert.ok(protectedPose.genericRecoilScale<=0.15);assert.ok(Math.hypot(protectedPose.offsetX,protectedPose.offsetY)<Math.hypot(open.offsetX,open.offsetY));assert.ok(Math.abs(protectedPose.rotation)<Math.abs(open.rotation));});
test('phase 2983 reduced motion preserves boss stagger stance while compressing transform',async()=>{const mod=await loadModule();const s=mod.advanceBossHeavyHitStaggerState(undefined,{tier:'critical',directionX:-0.8,directionY:0.6},0,false);const full=mod.bossHeavyHitStaggerPresentation('abyssWitch',2,s,4,false);const reduced=mod.bossHeavyHitStaggerPresentation('abyssWitch',2,s,4,true);assert.equal(reduced.stance,full.stance);assert.equal(reduced.stagger,full.stagger);assert.ok(Math.hypot(reduced.offsetX,reduced.offsetY)<Math.hypot(full.offsetX,full.offsetY));assert.ok(Math.abs(reduced.rotation)<Math.abs(full.rotation));});
test('phase 2984 boss damage triggers only heavy critical stagger, decays in update, and render composes telegraph-safe recoil',async()=>{assert.match(enemySource,/bossHeavyHitStagger/);assert.match(enemySource,/advanceBossHeavyHitStaggerState/);assert.match(enemySource,/bossHeavyHitStaggerPresentation/);assert.match(enemySource,/impactTier !== 'normal'/);assert.match(enemySource,/genericRecoilScale/);assert.match(enemySource,/specialTimer/);assert.equal(fs.existsSync(new URL('../src/game/boss-heavy-hit-stagger-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-heavy-hit-stagger-audit.js');const audit=mod.runBossHeavyHitStaggerAudit();assert.equal(audit.samples.length,72);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
