import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=()=>fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');async function load(){return import('../dist/game/boss-special-anticipation-emphasis-rendering.js');}
const input=(over={})=>({archetype:'inferno',phase:2,charge:.75,recovery:0,stagger:0,...over});
test('phase 3519 charging boss special exposes anticipation body and ring emphasis together',async()=>{const m=await load();const p=m.bossSpecialAnticipationEmphasisPresentation(input(),false,false);assert.equal(p.active,true);assert.ok(p.ringAlphaScale>1);assert.ok(p.bodyScaleX!==1||p.bodyScaleY!==1);});
test('phase 3520 phase three anticipation is stronger than phase one at equal charge',async()=>{const m=await load();const p1=m.bossSpecialAnticipationEmphasisPresentation(input({phase:1}),false,false),p3=m.bossSpecialAnticipationEmphasisPresentation(input({phase:3}),false,false);assert.ok(p3.ringWidthScale>p1.ringWidthScale);assert.ok(p3.ringRadiusScale>=p1.ringRadiusScale);});
test('phase 3521 juggernaut anticipation compresses lower while abyss witch lifts vertically',async()=>{const m=await load();const j=m.bossSpecialAnticipationEmphasisPresentation(input({archetype:'juggernaut'}),false,false),w=m.bossSpecialAnticipationEmphasisPresentation(input({archetype:'abyssWitch'}),false,false);assert.ok(j.bodyScaleY<1);assert.ok(w.bodyScaleY>1);});
test('phase 3522 stagger pressure yields boss special anticipation body exaggeration first',async()=>{const m=await load();const clean=m.bossSpecialAnticipationEmphasisPresentation(input(),false,false),hit=m.bossSpecialAnticipationEmphasisPresentation(input({stagger:.9}),false,false);assert.ok(hit.bodyStrength<clean.bodyStrength);assert.ok(hit.ringAlphaScale<=clean.ringAlphaScale);});
test('phase 3523 reduced flash lowers ring emphasis without moving the anticipation radius',async()=>{const m=await load();const normal=m.bossSpecialAnticipationEmphasisPresentation(input(),false,false),reduced=m.bossSpecialAnticipationEmphasisPresentation(input(),false,true);assert.equal(reduced.ringRadiusScale,normal.ringRadiusScale);assert.ok(reduced.ringAlphaScale<normal.ringAlphaScale);});
test('phase 3524 live boss special ring and body consume one anticipation presentation layer',async()=>{const s=source();assert.match(s,/bossSpecialAnticipationEmphasisPresentation/);assert.match(s,/bossSpecialAnticipation\.ringAlphaScale/);assert.match(s,/bossSpecialAnticipation\.bodyScaleX/);const a=await import('../dist/game/boss-special-anticipation-emphasis-audit.js');const r=a.runBossSpecialAnticipationEmphasisAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
