import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-spatial-recovery-rendering.js',import.meta.url);async function load(){return import(moduleUrl.href);}
test('Phase 4107 projectile corridor release restores trail without body fade',async()=>{const {projectileCorridorReleasePresentation}=await load();const a=projectileCorridorReleasePresentation({pressure:.9,release:.1,critical:false},false),b=projectileCorridorReleasePresentation({pressure:.9,release:.9,critical:false},false);assert.equal(a.bodyAlphaScale,1);assert.ok(b.trailAlphaScale>a.trailAlphaScale);assert.ok(b.trailAlphaScale<=1);});
test('Phase 4108 telegraph safe lane release has no secondary rebound',async()=>{const {telegraphSafeLaneReleasePresentation}=await load();const a=telegraphSafeLaneReleasePresentation({overlap:1,release:.2,telegraphActive:true},false),b=telegraphSafeLaneReleasePresentation({overlap:.2,release:.8,telegraphActive:false},false);assert.ok(a.telegraphEdgeAlphaScale>=.92);assert.ok(a.safeLaneAlphaScale>=1);assert.ok(b.secondaryAlphaScale<=1);});
test('Phase 4109 impact corridor release keeps edge at least as strong as fill',async()=>{const {impactCorridorReleasePresentation}=await load();const p=impactCorridorReleasePresentation({life:.3,heroProximity:.8,neighborCount:6,release:.6,critical:false},false);assert.equal(p.canonicalAlphaScale,1);assert.ok(p.edgeAlphaScale>=p.fillAlphaScale);});
test('Phase 4110 specialist recovery keeps direction while hazard clears',async()=>{const {specialistDirectionalReleasePresentation}=await load();const p=specialistDirectionalReleasePresentation({owner:'recovery',hazardPressure:.8,recovery:.7},false);assert.equal(p.bodyAlphaScale,1);assert.ok(p.directionAlphaScale>=.64);});
test('Phase 4111 reclaim guard restores secondary only after corridor release',async()=>{const {spatialReclaimGuardPresentation}=await load();const a=spatialReclaimGuardPresentation({release:.1,pressure:1,safeLaneVisible:true},false),b=spatialReclaimGuardPresentation({release:.9,pressure:.2,safeLaneVisible:true},false);assert.equal(a.canonicalBodyAlphaScale,1);assert.ok(a.safeLaneAlphaScale>=1);assert.ok(b.secondaryAlphaScale>a.secondaryAlphaScale);});
test('Phase 4112 recovery budget prevents simultaneous secondary restoration',async()=>{const {spatialRecoveryBudgetPresentation}=await load();const p=spatialRecoveryBudgetPresentation({recoveringCount:12,pressure:1,criticalCount:2},false,false);assert.equal(p.canonicalBodyAlphaScale,1);assert.equal(p.criticalAlphaScale,1);assert.ok(p.secondaryRecoveryScale<1);});
test('Phase 4107-4112 live renderers consume spatial recovery helpers',async()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileCorridorReleasePresentation/);assert.match(e,/specialistDirectionalReleasePresentation/);assert.match(s,/impactCorridorReleasePresentation/);assert.match(g,/spatialReclaimGuardPresentation/);assert.match(g,/telegraphSafeLaneReleasePresentation/);});
