import test from 'node:test';
import assert from 'node:assert/strict';
import * as separation from '../dist/game/threat-impact-spatial-separation-rendering.js';
import * as ownership from '../dist/game/threat-impact-shared-footprint-ownership-rendering.js';

test('Phase 4209 projectile secondary trail never outranks canonical body in shared footprint',()=>{const p=ownership.projectileFootprintOwnershipPresentation({bodyOverlap:1,laneProximity:1,critical:false});assert.equal(p.canonicalBodyScale,1);assert.ok(p.trailCeiling<=.58);});
test('Phase 4210 boss telegraph and safe lane jointly reserve shared footprint',()=>{const p=separation.telegraphSafeLaneSeparationPresentation({telegraphActive:true,safeLaneVisible:true,overlap:1,critical:true});assert.equal(p.telegraphEdgeAlphaScale,.98);assert.ok(p.safeLaneAlphaScale>=1);assert.ok(p.secondaryAlphaScale<=.5);});
test('Phase 4211 impact fill yields near hero and safe-lane footprint',()=>{const p=separation.impactCorridorSeparationPresentation({heroProximity:1,safeLaneProximity:1,neighborCount:8,critical:false});assert.equal(p.canonicalAlphaScale,1);assert.ok(p.fillAlphaScale<=.34);});
test('Phase 4212 specialist recovery trail yields to canonical body under local pressure',()=>{const p=separation.specialistDirectionalSeparationPresentation({owner:'recovery',hazardPressure:1,crowd:1,attackStrength:0});assert.equal(p.bodyAlphaScale,1);assert.ok(p.trailAlphaScale<=.58);});
test('Phase 4213 shared footprint budget preserves protected owners',()=>{const p=ownership.sharedFootprintBudgetPresentation({pressure:1,criticalCount:3,safeLaneVisible:true,bossTelegraphActive:true});assert.equal(p.criticalScale,1);assert.equal(p.canonicalBodyScale,1);assert.equal(p.bossTelegraphEdgeScale,1);assert.equal(p.safeLaneScale,1);assert.ok(p.secondaryCeiling<.6);});
test('Phase 4214 reduced accessibility settings only lower secondary ownership material',()=>{const base=ownership.sharedFootprintBudgetPresentation({pressure:.8,criticalCount:1,safeLaneVisible:true,bossTelegraphActive:true}),reduced=ownership.sharedFootprintBudgetPresentation({pressure:.8,criticalCount:1,safeLaneVisible:true,bossTelegraphActive:true},true,true);assert.equal(reduced.criticalScale,1);assert.equal(reduced.canonicalBodyScale,1);assert.equal(reduced.bossTelegraphEdgeScale,1);assert.equal(reduced.safeLaneScale,1);assert.ok(reduced.secondaryCeiling<=base.secondaryCeiling);});
