import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');const url=new URL('../src/game/hero-ultimate-aim-continuity-rendering.ts',import.meta.url);
async function load(){assert.equal(fs.existsSync(url),true);return import('../dist/game/hero-ultimate-aim-continuity-rendering.js');}
test('phase 3417 hero ultimate aim continuity module exists',async()=>{const m=await load();assert.equal(typeof m.advanceHeroUltimateAimContinuityState,'function');assert.equal(typeof m.heroUltimateAimContinuityPresentation,'function');});
test('phase 3418 ultimate activation captures a normalized facing identity',async()=>{const m=await load();const s=m.advanceHeroUltimateAimContinuityState(undefined,{x:-3,y:4},0,false);assert.ok(Math.abs(Math.hypot(s.lockedX,s.lockedY)-1)<1e-6);assert.ok(s.hold>.5);});
test('phase 3419 release and early recovery preserve the original ultimate direction after movement turns',async()=>{const m=await load();let s=m.advanceHeroUltimateAimContinuityState(undefined,{x:1,y:0},0,false);s=m.advanceHeroUltimateAimContinuityState(s,null,.34,false);const p=m.heroUltimateAimContinuityPresentation(s,-1,0,true,.34,false);assert.equal(p.owner,'ultimate');assert.ok(p.facingX>.2);assert.ok(p.retention>.35);});
test('phase 3420 expired ultimate continuity returns cleanly to live facing',async()=>{const m=await load();let s=m.advanceHeroUltimateAimContinuityState(undefined,{x:1,y:0},0,false);s=m.advanceHeroUltimateAimContinuityState(s,null,2,false);const p=m.heroUltimateAimContinuityPresentation(s,-1,0,false,.7,false);assert.equal(p.owner,'current');assert.ok(p.facingX<-.99);assert.equal(p.retention,0);});
test('phase 3421 reduced motion keeps identity but shortens the continuity window',async()=>{const m=await load();const a=m.advanceHeroUltimateAimContinuityState(undefined,{x:0,y:1},0,false),b=m.advanceHeroUltimateAimContinuityState(undefined,{x:0,y:1},0,true);assert.ok(b.hold<a.hold);const p=m.heroUltimateAimContinuityPresentation(b,1,0,true,.05,true);assert.equal(p.owner,'ultimate');assert.ok(Number.isFinite(p.overlayAngle));});
test('phase 3422 game wires ultimate trigger decay reset and uses locked facing for ultimate body presentation',async()=>{assert.match(source,/heroUltimateAimContinuityState/);assert.match(source,/advanceHeroUltimateAimContinuityState/);assert.match(source,/heroUltimateAimContinuityPresentation/);assert.match(source,/heroUltimateBodyPresentation\(this\.heroUltimateBodyState, ultimateAim\.facingX, ultimateAim\.facingY/);const a=await import('../dist/game/hero-ultimate-aim-continuity-audit.js');const r=a.runHeroUltimateAimContinuityAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
