import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
async function load(){return import('../dist/game/hero-directional-overlay-owner-rendering.js');}const source=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const input=(owner='movement',body=0,move=0,cast=0,retention=0)=>({owner,bodyAngle:body,movementAngle:move,castAngle:cast,actionRetention:retention,movementBlend:.8,castBlend:owner==='movement'?0:.8});
test('phase 3489 movement ownership leaves locomotion overlay direction untouched',async()=>{const m=await load();const p=m.heroDirectionalOverlayOwnerPresentation(input('movement',0,.4,.7,0),false);assert.equal(p.owner,'movement');assert.ok(Math.abs(p.movementAngle-.4)<.001);assert.equal(p.movementAlphaScale,1);});
test('phase 3490 active cast ownership aligns directional overlays to the retained body direction',async()=>{const m=await load();const p=m.heroDirectionalOverlayOwnerPresentation(input('cast',Math.PI,.05,-2.9,.9),false);assert.equal(p.owner,'cast');assert.ok(Math.abs(Math.abs(p.movementAngle)-Math.PI)<.01);assert.ok(Math.abs(Math.abs(p.castAngle)-Math.PI)<.01);});
test('phase 3491 opposite locomotion overlay is strongly suppressed while action owns facing',async()=>{const m=await load();const p=m.heroDirectionalOverlayOwnerPresentation(input('ultimate',Math.PI,0,0,1),false);assert.ok(p.movementAlphaScale<=.35);assert.equal(p.singleDirectionalOwner,true);});
test('phase 3492 nearby locomotion direction keeps more movement texture than an opposite direction',async()=>{const m=await load();const near=m.heroDirectionalOverlayOwnerPresentation(input('cast',.2,.05,.2,.8),false),far=m.heroDirectionalOverlayOwnerPresentation(input('cast',Math.PI,0,Math.PI,.8),false);assert.ok(near.movementAlphaScale>far.movementAlphaScale);});
test('phase 3493 reduced motion never adds a new directional transition layer',async()=>{const m=await load();const p=m.heroDirectionalOverlayOwnerPresentation(input('cast',1.2,-1.5,1.2,.9),true);assert.equal(p.movementAngle,1.2);assert.equal(p.castAngle,1.2);assert.equal(p.presentationOnly,true);});
test('phase 3494 live hero movement and cast overlays consume one directional overlay owner',async()=>{const s=source();assert.match(s,/heroDirectionalOverlayOwnerPresentation/);assert.match(s,/directionalOverlay\.movementAngle/);assert.match(s,/directionalOverlay\.castAngle/);const a=await import('../dist/game/hero-directional-overlay-owner-audit.js');const r=a.runHeroDirectionalOverlayOwnerAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
