import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../src/game/hero-crisis-ground-settle-rendering.ts',import.meta.url);
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/hero-crisis-ground-settle-rendering.js');}

test('phase 3057 hero crisis ground settle module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.advanceHeroCrisisGroundSettleState,'function');assert.equal(typeof mod.heroCrisisGroundSettlePresentation,'function');});
test('phase 3058 critical recoil starts a persistent ground settle owner while ordinary hits do not',async()=>{const {advanceHeroCrisisGroundSettleState,heroCrisisGroundSettlePresentation}=await loadModule();const critical=advanceHeroCrisisGroundSettleState(undefined,1.12,0,false);const normal=advanceHeroCrisisGroundSettleState(undefined,.72,0,false);assert.ok(critical.settle>.9);assert.equal(normal.settle,0);assert.equal(heroCrisisGroundSettlePresentation(critical,0,false).owner,'impact');});
test('phase 3059 movement restart remains under the same settle owner after critical recoil decays',async()=>{const {advanceHeroCrisisGroundSettleState,heroCrisisGroundSettlePresentation}=await loadModule();let s=advanceHeroCrisisGroundSettleState(undefined,1.1,0,false);s=advanceHeroCrisisGroundSettleState(s,null,.16,false);const p=heroCrisisGroundSettlePresentation(s,.85,false);assert.equal(p.owner,'settle');assert.ok(p.groundMotionScale>.62&&p.groundMotionScale<1);assert.ok(p.movementRestartScale>.65&&p.movementRestartScale<1);});
test('phase 3060 final settle converges monotonically to ordinary ground ownership without a one frame snap',async()=>{const {advanceHeroCrisisGroundSettleState,heroCrisisGroundSettlePresentation}=await loadModule();let s=advanceHeroCrisisGroundSettleState(undefined,1.2,0,false);const scales=[];for(let i=0;i<8;i++){s=advanceHeroCrisisGroundSettleState(s,null,.05,false);scales.push(heroCrisisGroundSettlePresentation(s,.72,false).groundMotionScale);}for(let i=1;i<scales.length;i++)assert.ok(scales[i]>=scales[i-1]-.0001);assert.ok(scales.at(-1)>.9);});
test('phase 3061 reduced motion shortens crisis settle and tightens ground distortion',async()=>{const {advanceHeroCrisisGroundSettleState,heroCrisisGroundSettlePresentation}=await loadModule();let full=advanceHeroCrisisGroundSettleState(undefined,1.2,0,false),reduced=advanceHeroCrisisGroundSettleState(undefined,1.2,0,true);full=advanceHeroCrisisGroundSettleState(full,null,.12,false);reduced=advanceHeroCrisisGroundSettleState(reduced,null,.12,true);const pf=heroCrisisGroundSettlePresentation(full,.6,false),pr=heroCrisisGroundSettlePresentation(reduced,.6,true);assert.ok(reduced.settle<full.settle);assert.ok(Math.abs(1-pr.widthScale)<Math.abs(1-pf.widthScale));});
test('phase 3062 hero hit queue update and shadow composition share crisis settle state and audit stays presentation only',async()=>{assert.match(gameSource,/heroCrisisGroundSettleState/);assert.match(gameSource,/advanceHeroCrisisGroundSettleState/);assert.match(gameSource,/heroCrisisGroundSettlePresentation/);assert.match(gameSource,/heroCrisisGroundSettle\.groundMotionScale/);assert.match(gameSource,/heroCrisisGroundScale=heroHitGroundHandoff\.owner==='hit'\?1:Math\.min/);assert.doesNotMatch(gameSource,/heroCrisisGroundSettle\.groundMotionScale\*heroCrisisGroundSettle\.movementRestartScale/);assert.equal(fs.existsSync(new URL('../src/game/hero-crisis-ground-settle-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/hero-crisis-ground-settle-audit.js');const audit=mod.runHeroCrisisGroundSettleAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
