import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
async function load(){return import('../dist/game/safe-lane-gap-hazard-handoff-rendering.js');}const source=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const current=(start=.3,end=.5,release=.1)=>({visible:true,start,end,release});
test('phase 3501 overlapping moving gap keeps smooth tracking instead of resetting continuity',async()=>{const m=await load();const p=m.safeLaneGapHazardHandoffPresentation({current:current(),next:{start:.34,end:.54}},false);assert.equal(p.mode,'track');assert.equal(p.resetBeforeAdvance,false);});
test('phase 3502 non-overlapping new imminent hazard snaps immediately so smoothing cannot draw through danger',async()=>{const m=await load();const p=m.safeLaneGapHazardHandoffPresentation({current:current(.15,.3),next:{start:.62,end:.78}},false);assert.equal(p.mode,'snap');assert.equal(p.resetBeforeAdvance,true);});
test('phase 3503 materially expanding danger gap snaps outward instead of lagging behind the unsafe edge',async()=>{const m=await load();const p=m.safeLaneGapHazardHandoffPresentation({current:current(.35,.5),next:{start:.22,end:.62}},false);assert.equal(p.mode,'snap');assert.equal(p.resetBeforeAdvance,true);});
test('phase 3504 missing current hazard preserves bounded release ownership',async()=>{const m=await load();const p=m.safeLaneGapHazardHandoffPresentation({current:current(),next:null},false);assert.equal(p.mode,'release');assert.equal(p.resetBeforeAdvance,false);assert.equal(p.nextGap,null);});
test('phase 3505 reduced motion always adopts current hazard geometry directly',async()=>{const m=await load();const p=m.safeLaneGapHazardHandoffPresentation({current:current(.1,.2),next:{start:.3,end:.45}},true);assert.equal(p.mode,'snap');assert.equal(p.resetBeforeAdvance,true);});
test('phase 3506 live safe-lane arbitrates hazard handoff before feather hysteresis advances',async()=>{const s=source();assert.match(s,/safeLaneGapHazardHandoffPresentation/);assert.match(s,/gapHandoff\.resetBeforeAdvance/);assert.match(s,/advanceSafeLaneGapFeatherHysteresisState/);const a=await import('../dist/game/safe-lane-gap-hazard-handoff-audit.js');const r=a.runSafeLaneGapHazardHandoffAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
