import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const mapSource=fs.readFileSync(new URL('../src/game/map-evolution.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/map-evolution-aftermath-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/map-evolution-aftermath-vfx-assets.js');}

test('phase 2529 map evolution aftermath atlas covers three maps x two stages x collapse debris settle',async()=>{const mod=await load(),audit=mod.auditMapEvolutionAftermathVfxAtlas();assert.equal(audit.mapCount,3);assert.equal(audit.stageCount,2);assert.equal(audit.stateCount,3);assert.equal(audit.itemCount,18);assert.equal(audit.uniqueCellCount,18);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.MAP_EVOLUTION_AFTERMATH_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:384,height:768});assert.ok(b.length>6500);});
test('phase 2530 actual map evolution queues map stage lifecycle at evolution time',()=>{assert.match(gameSource,/emitMapEvolutionVfx\(stage:MapEvolutionStage\)/);assert.match(gameSource,/mapEvolutionAftermathVfx\.push\(\{mapId:this\.terrain\.currentLayout\.id,stage/);assert.match(gameSource,/if \(evolved\) \{ this\.showBattlefieldEvolutionToast\(evolved\); this\.emitMapEvolutionVfx\(evolved\); \}/);});
test('phase 2531 map evolution lifecycle transitions collapse to debris to settle',()=>{assert.match(gameSource,/progress<0\.24\?'collapse':progress<0\.62\?'debris':'settle'/);assert.match(gameSource,/mapEvolutionAftermathVfxSprite\(cue\.mapId,cue\.stage,state\)/);});
test('phase 2532 map evolution aftermath queue is capped ttl driven and reset between runs',()=>{assert.match(gameSource,/mapEvolutionAftermathVfx\.length>8/);assert.match(gameSource,/for \(const cue of this\.mapEvolutionAftermathVfx\) cue\.ttl -= safeDt/);assert.match(gameSource,/this\.mapEvolutionAftermathVfx = \[\]/);});
test('phase 2533 map evolution aftermath is fail-open and preserves existing map evolution gameplay',()=>{assert.match(gameSource,/initializeMapEvolutionAftermathVfxAtlas/);assert.match(gameSource,/queueBattlefieldEnvironmentReactionVfx\('evolutionCollapse'/);assert.match(mapSource,/if \(stage >= 1\)/);assert.match(mapSource,/if \(stage >= 2\)/);});
test('phase 2534 map evolution aftermath audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/map-evolution-aftermath-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/map-evolution-aftermath-vfx-audit.js'),audit=mod.runMapEvolutionAftermathVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/mapEvolutionAftermathVfxPassed/);assert.match(candidateSource,/mapEvolutionAftermathVfxPassed/);assert.match(candidateSource,/map-evolution-aftermath-vfx/);});
