import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-hit-world-guard-arbitration-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-hit-world-guard-arbitration-rendering.js');}
test('phase 3219 core-hit world-guard arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.coreHitWorldGuardArbitrationPresentation,'function');});
test('phase 3220 unmitigated core damage keeps the coreHit cue authoritative',async()=>{const m=await load();const p=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:0,mitigationRatio:0,worldDamageOwned:false,hitTtl:.28,hitMaxTtl:.34},false);assert.equal(p.owner,'hit');assert.equal(p.coreHitAlphaScale,1);assert.equal(p.worldDamageOwned,false);});
test('phase 3221 strongly mitigated core damage yields full damage cue to world guard',async()=>{const m=await load();const p=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:.72,mitigationRatio:.78,worldDamageOwned:false,hitTtl:.28,hitMaxTtl:.34},false);assert.equal(p.owner,'world-guard');assert.equal(p.coreHitAlphaScale,0);assert.equal(p.worldDamageOwned,true);});
test('phase 3222 once world damage ownership latches the same coreHit cue never reanimates',async()=>{const m=await load();const first=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:.64,mitigationRatio:.82,worldDamageOwned:false,hitTtl:.3,hitMaxTtl:.34},false);const later=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:0,mitigationRatio:.82,worldDamageOwned:first.worldDamageOwned,hitTtl:.14,hitMaxTtl:.34},false);assert.equal(first.worldDamageOwned,true);assert.equal(later.owner,'retired');assert.equal(later.coreHitAlphaScale,0);});
test('phase 3223 medium mitigation shares emphasis and reduced flash never raises the remaining hit cue',async()=>{const m=await load();const normal=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:.42,mitigationRatio:.48,worldDamageOwned:false,hitTtl:.3,hitMaxTtl:.34},false);const reduced=m.coreHitWorldGuardArbitrationPresentation({worldGuardStrength:.42,mitigationRatio:.48,worldDamageOwned:false,hitTtl:.3,hitMaxTtl:.34},true);assert.equal(normal.owner,'shared');assert.ok(normal.coreHitAlphaScale>0&&normal.coreHitAlphaScale<1);assert.ok(reduced.coreHitAlphaScale<=normal.coreHitAlphaScale);});
test('phase 3224 live coreHit stores mitigation metadata and uses presentation-only arbitration audit',async()=>{const s=gameSource();assert.match(s,/mitigationRatio/);assert.match(s,/coreHitWorldGuardArbitrationPresentation/);assert.match(s,/worldDamageOwned/);const a=await import('../dist/game/core-hit-world-guard-arbitration-audit.js');const r=a.runCoreHitWorldGuardArbitrationAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
