import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const gameSource=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
const freezeSource=fs.readFileSync(new URL('../src/game/release-freeze-audit.ts',import.meta.url),'utf8');
const candidateSource=fs.readFileSync(new URL('../src/game/release-candidate-audit.ts',import.meta.url),'utf8');
function pngDimensions(buffer){assert.equal(buffer.toString('ascii',1,4),'PNG');return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};}
async function load(){assert.equal(fs.existsSync(new URL('../src/game/boss-hazard-aftermath-vfx-assets.ts',import.meta.url)),true);return import('../dist/game/boss-hazard-aftermath-vfx-assets.js');}

test('phase 2535 boss hazard aftermath atlas covers six hazards x detonate residual',async()=>{const mod=await load(),audit=mod.auditBossHazardAftermathVfxAtlas();assert.equal(audit.hazardCount,6);assert.equal(audit.stateCount,2);assert.equal(audit.itemCount,12);assert.equal(audit.uniqueCellCount,12);assert.equal(audit.passed,true);const b=fs.readFileSync(path.resolve(mod.BOSS_HAZARD_AFTERMATH_VFX_ATLAS.src.replace(/^\.\//,'')));assert.deepEqual(pngDimensions(b),{width:384,height:512});assert.ok(b.length>5000);});
test('phase 2536 only actually expiring active hazards queue aftermath without changing arena damage',()=>{assert.match(gameSource,/expiringHazards=this\.bossArena\.hazards\.filter\(\(hazard\)=>hazard\.telegraph<=0&&hazard\.ttl>0&&hazard\.ttl-safeDt<=0\)/);assert.match(gameSource,/this\.bossArena\.update\(dt,/);assert.match(gameSource,/queueBossHazardAftermathVfx\(hazard\.kind,hazard\.pos\.x,hazard\.pos\.y,hazard\.radius\)/);});
test('phase 2537 boss hazard aftermath transitions detonate to residual in world space',()=>{assert.match(gameSource,/progress<0\.32\?'detonate':'residual'/);assert.match(gameSource,/bossHazardAftermathVfxSprite\(cue\.kind,state\)/);});
test('phase 2538 boss hazard aftermath queue is ttl bounded capped and reset',()=>{assert.match(gameSource,/bossHazardAftermathVfx\.length>16/);assert.match(gameSource,/for\(const cue of this\.bossHazardAftermathVfx\)cue\.ttl-=safeDt/);assert.match(gameSource,/this\.bossHazardAftermathVfx=\[\]/);});
test('phase 2539 hazard aftermath atlas loads independently while lifecycle fallback remains',()=>{assert.match(gameSource,/initializeBossHazardAftermathVfxAtlas/);assert.match(gameSource,/bossHazardAftermathVfxAtlasImage/);assert.match(gameSource,/bossArenaLifecycleVfxSprite\(hazard\.kind,hazard\.telegraph>0\?'telegraph':'active'\)/);});
test('phase 2540 hazard aftermath audit is deterministic release-bound and presentation-only',async()=>{assert.equal(fs.existsSync(new URL('../src/game/boss-hazard-aftermath-vfx-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/boss-hazard-aftermath-vfx-audit.js'),audit=mod.runBossHazardAftermathVfxAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.passed,true);assert.match(freezeSource,/bossHazardAftermathVfxPassed/);assert.match(candidateSource,/bossHazardAftermathVfxPassed/);assert.match(candidateSource,/boss-hazard-aftermath-vfx/);});
