import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/boss-cleared-safe-lane-forecast-arbitration-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/boss-cleared-safe-lane-forecast-arbitration-rendering.js');}
test('phase 3213 cleared-ground safe-lane forecast arbitration module exists',async()=>{const m=await load();assert.equal(typeof m.bossClearedSafeLaneForecastTarget,'function');});
test('phase 3214 stable low-urgency forecast keeps current safe-lane target authoritative',async()=>{const m=await load();const p=m.bossClearedSafeLaneForecastTarget({currentTarget:{x:500,y:310},currentConfidence:.8,nextTarget:{x:400,y:440},forecastUrgency:.24,transitionMs:3600},false);assert.equal(p.owner,'current');assert.deepEqual(p.target,{x:500,y:310});});
test('phase 3215 imminent forecast promotes nextTarget before the safe-zone transition',async()=>{const m=await load();const p=m.bossClearedSafeLaneForecastTarget({currentTarget:{x:500,y:310},currentConfidence:.8,nextTarget:{x:400,y:440},forecastUrgency:.72,transitionMs:900},false);assert.equal(p.owner,'forecast');assert.deepEqual(p.target,{x:400,y:440});assert.ok(p.confidence>=.65);});
test('phase 3216 imminent nextTarget can pre-agree with cleared corridor',async()=>{const m=await load();const p=m.bossClearedSafeLaneForecastTarget({currentTarget:{x:410,y:440},currentConfidence:.76,nextTarget:{x:520,y:312},forecastUrgency:.82,transitionMs:650},false);assert.equal(p.owner,'forecast');assert.equal(p.target.x,520);});
test('phase 3217 missing or distant forecast leaves current lane unchanged',async()=>{const m=await load();const none=m.bossClearedSafeLaneForecastTarget({currentTarget:{x:500,y:312},currentConfidence:.74},false);const distant=m.bossClearedSafeLaneForecastTarget({currentTarget:{x:500,y:312},currentConfidence:.74,nextTarget:{x:420,y:430},forecastUrgency:.72,transitionMs:4200},false);assert.equal(none.owner,'current');assert.equal(distant.owner,'current');});
test('phase 3218 live mythic render stores forecast nextTarget for cleared-ground arbitration with presentation-only audit',async()=>{const s=gameSource();assert.match(s,/forecastTarget/);assert.match(s,/forecastUrgency/);assert.match(s,/bossClearedSafeLaneForecastTarget/);const a=await import('../dist/game/boss-cleared-safe-lane-forecast-arbitration-audit.js');const r=a.runBossClearedSafeLaneForecastArbitrationAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
