import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const u=new URL('../src/game/secondary-impact-lineage-label-motion-settle-rendering.ts',import.meta.url);const spells=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(u),true);return import('../dist/game/secondary-impact-lineage-label-motion-settle-rendering.js');}
test('phase 3297 secondary lineage label motion-settle module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactLineageLabelMotionSettle,'function');});
test('phase 3298 first visible lineage label adopts its clean placement without artificial travel',async()=>{const m=await load();const r=m.secondaryImpactLineageLabelMotionSettle([], 'L1',{x:300,y:250},true,false);assert.deepEqual(r.presentation.pos,{x:300,y:250});assert.equal(r.presentation.settled,true);});
test('phase 3299 large placement changes move by a bounded per-frame step instead of teleporting',async()=>{const m=await load();let r=m.secondaryImpactLineageLabelMotionSettle([], 'L1',{x:300,y:250},true,false);r=m.secondaryImpactLineageLabelMotionSettle(r.memory,'L1',{x:390,y:330},true,false);const d=Math.hypot(r.presentation.pos.x-300,r.presentation.pos.y-250);assert.ok(d>0&&d<=m.SECONDARY_IMPACT_LABEL_MAX_RENDER_STEP+1e-9);assert.equal(r.presentation.settled,false);});
test('phase 3300 tiny placement drift snaps cleanly and does not create perpetual micro motion',async()=>{const m=await load();let r=m.secondaryImpactLineageLabelMotionSettle([], 'L1',{x:300,y:250},true,false);r=m.secondaryImpactLineageLabelMotionSettle(r.memory,'L1',{x:302,y:252},true,false);assert.deepEqual(r.presentation.pos,{x:302,y:252});assert.equal(r.presentation.settled,true);});
test('phase 3301 reduced motion disables interpolation and hidden lineages retire their render memory',async()=>{const m=await load();let r=m.secondaryImpactLineageLabelMotionSettle([], 'L1',{x:300,y:250},true,false);r=m.secondaryImpactLineageLabelMotionSettle(r.memory,'L1',{x:390,y:330},true,true);assert.deepEqual(r.presentation.pos,{x:390,y:330});r=m.secondaryImpactLineageLabelMotionSettle(r.memory,'L1',{x:390,y:330},false,false);assert.equal(r.presentation.visible,false);assert.equal(r.memory.some(e=>e.lineageKey==='L1'),false);});
test('phase 3302 live secondary labels render from settled positions with presentation-only audit',async()=>{const s=spells();assert.match(s,/secondaryImpactLineageLabelMotionSettle/);assert.match(s,/secondaryImpactLineageLabelMotionMemory/);const a=await import('../dist/game/secondary-impact-lineage-label-motion-settle-audit.js');const r=a.runSecondaryImpactLineageLabelMotionSettleAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
