import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-secondary-ceiling-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4161 projectile trail ceiling tightens as battlefield stress rises',async()=>{const {projectileSecondaryCeilingPresentation}=await load();const low=projectileSecondaryCeilingPresentation({stress:.1,critical:false,bossActive:false,reacquire:.8},false,false),high=projectileSecondaryCeilingPresentation({stress:1,critical:false,bossActive:true,reacquire:.2},false,false);assert.ok(high.trailScale<low.trailScale);assert.ok(high.trailScale>=.45);});
test('Phase 4162 impact fill yields before the protected impact edge',async()=>{const {impactSecondaryCeilingPresentation}=await load();const p=impactSecondaryCeilingPresentation({stress:1,critical:true,bossActive:true,reacquire:.2},false);assert.ok(p.fillScale<1);assert.equal(p.edgeScale,1);});
test('Phase 4163 hazard interior yields while danger boundary remains canonical',async()=>{const {hazardSecondaryCeilingPresentation}=await load();const p=hazardSecondaryCeilingPresentation({stress:1,telegraph:true,critical:true,reacquire:.2},false);assert.ok(p.fillScale<.8);assert.equal(p.edgeScale,1);});
test('Phase 4164 specialist recovery trail yields before silhouette ownership',async()=>{const {specialistSecondaryCeilingPresentation}=await load();const p=specialistSecondaryCeilingPresentation({stress:1,owner:'special',critical:true,reacquire:.2},false);assert.ok(p.trailScale<1);assert.equal(p.silhouetteScale,1);});
test('Phase 4165 stale boss decoration receives a bounded ceiling without touching telegraph edge',async()=>{const {bossSecondaryCeilingPresentation}=await load();const p=bossSecondaryCeilingPresentation({stress:1,critical:true,reacquire:.2},false);assert.ok(p.staleScale<.75);assert.equal(p.telegraphScale,1);});
test('Phase 4166 secondary ceiling budget is monotonic and never boosts decoration',async()=>{const {secondaryCeilingBudgetPresentation}=await load();const a=secondaryCeilingBudgetPresentation({criticalCount:0,crowd:.2,bossActive:false},false,false),b=secondaryCeilingBudgetPresentation({criticalCount:2,crowd:1,bossActive:true},false,false);assert.ok(b.secondaryScale<=a.secondaryScale);assert.ok(b.secondaryScale<=1);assert.ok(b.secondaryScale>=.45);});
test('Phase 4161-4166 live renderers consume final secondary ceilings',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileSecondaryCeilingPresentation/);assert.match(e,/specialistSecondaryCeilingPresentation/);assert.match(s,/impactSecondaryCeilingPresentation/);assert.match(g,/hazardSecondaryCeilingPresentation/);assert.match(g,/bossSecondaryCeilingPresentation/);});
