import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/core-guard-damage-source-body-language-rendering.ts',import.meta.url);const gameSource=()=>fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/core-guard-damage-source-body-language-rendering.js');}
test('phase 3237 core guard damage-source body-language module exists',async()=>{const m=await load();assert.equal(typeof m.coreGuardDamageSourceBodyLanguagePresentation,'function');});
test('phase 3238 projectile and contact core guard pressure use visibly different body language',async()=>{const m=await load();const p=m.coreGuardDamageSourceBodyLanguagePresentation({source:'projectile',owner:'world-guard',mitigationRatio:.8,ttl:.28,maxTtl:.34},false),c=m.coreGuardDamageSourceBodyLanguagePresentation({source:'contact',owner:'world-guard',mitigationRatio:.8,ttl:.28,maxTtl:.34},false);assert.equal(p.sourceClass,'projectile');assert.equal(c.sourceClass,'contact');assert.ok(p.bodyScaleX>p.bodyScaleY);assert.ok(c.bodyScaleY>=c.bodyScaleX);assert.notDeepEqual([p.deflectAlpha,p.contactRingAlpha],[c.deflectAlpha,c.contactRingAlpha]);});
test('phase 3239 source body language never creates a second damage owner beside arbitration',async()=>{const m=await load();for(const source of ['projectile','contact','arena']){const p=m.coreGuardDamageSourceBodyLanguagePresentation({source,owner:'world-guard',mitigationRatio:.9,ttl:.3,maxTtl:.34},false);assert.equal(p.damageOwner,'world-guard');assert.equal(p.visible,true);assert.equal(p.duplicatesDamageCue,false);}});
test('phase 3240 non projectile-contact sources fall back to neutral body language',async()=>{const m=await load();const p=m.coreGuardDamageSourceBodyLanguagePresentation({source:'arena',owner:'shared',mitigationRatio:.5,ttl:.2,maxTtl:.34},false);assert.equal(p.sourceClass,'other');assert.equal(p.bodyScaleX,1);assert.equal(p.bodyScaleY,1);});
test('phase 3241 reduced flash lowers additive source accents without changing source geometry',async()=>{const m=await load();const input={source:'projectile',owner:'world-guard',mitigationRatio:.8,ttl:.28,maxTtl:.34};const a=m.coreGuardDamageSourceBodyLanguagePresentation(input,false),b=m.coreGuardDamageSourceBodyLanguagePresentation(input,true);assert.equal(a.bodyScaleX,b.bodyScaleX);assert.equal(a.bodyScaleY,b.bodyScaleY);assert.ok(b.deflectAlpha<=a.deflectAlpha);assert.ok(b.contactRingAlpha<=a.contactRingAlpha);});
test('phase 3242 live coreHit carries source metadata and renders source body language through a presentation-only audit',async()=>{const s=gameSource();assert.match(s,/damageSource/);assert.match(s,/coreGuardDamageSourceBodyLanguagePresentation/);const a=await import('../dist/game/core-guard-damage-source-body-language-audit.js');const r=a.runCoreGuardDamageSourceBodyLanguageAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
