import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-final-readability-settle-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4173 projectile settle keeps canonical floor while unsettled trail yields',async()=>{const {projectileFinalReadabilitySettlePresentation}=await load();const p=projectileFinalReadabilitySettlePresentation({primaryFloor:.38,reacquire:.15,stress:1,critical:false},false,false);assert.ok(p.primaryFloor>=.42);assert.ok(p.secondaryScale<.72);assert.ok(p.secondaryScale<=1);});
test('Phase 4174 impact settle protects edge before interior decoration',async()=>{const {impactFinalReadabilitySettlePresentation}=await load();const p=impactFinalReadabilitySettlePresentation({primaryFloor:.4,reacquire:.2,stress:.9,critical:true},false,false);assert.ok(p.primaryFloor>=.48);assert.ok(p.secondaryScale<.82);});
test('Phase 4175 hazard settle keeps telegraph boundary stable through crowd churn',async()=>{const {hazardFinalReadabilitySettlePresentation}=await load();const p=hazardFinalReadabilitySettlePresentation({primaryFloor:.44,reacquire:.2,stress:1,critical:true},false,false);assert.ok(p.primaryFloor>=.5);assert.ok(p.secondaryScale<.82);});
test('Phase 4176 safe lane settle preserves path while contour decoration yields',async()=>{const {safeLaneFinalReadabilitySettlePresentation}=await load();const p=safeLaneFinalReadabilitySettlePresentation({primaryFloor:.62,reacquire:.2,stress:1,critical:true,confidence:.9},false,false);assert.ok(p.primaryFloor>=.72);assert.ok(p.secondaryScale<.82);});
test('Phase 4177 specialist settle keeps silhouette ownership stable',async()=>{const {specialistFinalReadabilitySettlePresentation}=await load();const p=specialistFinalReadabilitySettlePresentation({primaryFloor:.4,reacquire:.15,stress:1,critical:true},false,false);assert.ok(p.primaryFloor>=.5);assert.ok(p.secondaryScale<.82);});
test('Phase 4178 settle budget never attenuates primary ownership',async()=>{const {finalReadabilitySettleBudgetPresentation}=await load();const p=finalReadabilitySettleBudgetPresentation({criticalCount:2,stress:1,bossActive:true,safeLaneVisible:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<1);assert.ok(p.safeLaneScale>=1);});
test('Phase 4173-4178 live renderers consume final readability settle helpers',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileFinalReadabilitySettlePresentation/);assert.match(e,/specialistFinalReadabilitySettlePresentation/);assert.match(s,/impactFinalReadabilitySettlePresentation/);assert.match(g,/hazardFinalReadabilitySettlePresentation/);assert.match(g,/safeLaneFinalReadabilitySettlePresentation/);assert.match(e,/projectileFinalSettle\.secondaryScale/);});
