import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-cluster-split-lineage-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/secondary-impact-cluster-split-lineage-rendering.js');}
test('phase 3189 secondary impact split-lineage module exists',async()=>{const m=await load();assert.equal(typeof m.advanceSecondaryImpactClusterSplitLineage,'function');});
test('phase 3190 one dense cluster receives one lineage key',async()=>{const m=await load();const s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:200,y:200}},{pos:{x:214,y:205}},{pos:{x:222,y:194}}],.016);const a=m.secondaryImpactSplitLineageFor(s,{x:210,y:201}),b=m.secondaryImpactSplitLineageFor(s,{x:218,y:199});assert.equal(a.key,b.key);assert.ok(a.key.length>0);});
test('phase 3191 split cluster keeps parent lineage on one branch and creates distinct child lineage',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:240,y:220}},{pos:{x:250,y:222}},{pos:{x:260,y:218}}],.016);const parent=m.secondaryImpactSplitLineageFor(s,{x:250,y:220}).key;s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:190,y:220}},{pos:{x:198,y:222}},{pos:{x:302,y:220}},{pos:{x:310,y:222}}],.04);const left=m.secondaryImpactSplitLineageFor(s,{x:194,y:221}).key,right=m.secondaryImpactSplitLineageFor(s,{x:306,y:221}).key;assert.notEqual(left,right);assert.ok(left===parent||right===parent);});
test('phase 3192 child lineages stay attached to space when counts swap',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:240,y:220}},{pos:{x:250,y:220}},{pos:{x:260,y:220}}],.016);s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:188,y:216}},{pos:{x:196,y:220}},{pos:{x:204,y:224}},{pos:{x:304,y:216}}],.04);const leftKey=m.secondaryImpactSplitLineageFor(s,{x:196,y:220}).key,rightKey=m.secondaryImpactSplitLineageFor(s,{x:304,y:216}).key;s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:194,y:220}},{pos:{x:298,y:214}},{pos:{x:306,y:220}},{pos:{x:314,y:226}}],.04);assert.equal(m.secondaryImpactSplitLineageFor(s,{x:194,y:220}).key,leftKey);assert.equal(m.secondaryImpactSplitLineageFor(s,{x:306,y:220}).key,rightKey);});
test('phase 3193 stale child lineage retires after bounded absence',async()=>{const m=await load();let s=m.advanceSecondaryImpactClusterSplitLineage(m.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:180,y:200}},{pos:{x:300,y:200}}],.016);const old=m.secondaryImpactSplitLineageFor(s,{x:300,y:200}).key;s=m.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:180,y:200}}],.30);assert.notEqual(m.secondaryImpactSplitLineageFor(s,{x:300,y:200}).key,old);});
test('phase 3194 live spell path feeds lineage key into shared secondary readability budget with presentation-only audit',async()=>{const s=spellSource();assert.match(s,/secondaryImpactClusterSplitLineage/);assert.match(s,/lineageKey/);assert.match(s,/stableClusterKey:lineage/);const a=await import('../dist/game/secondary-impact-cluster-split-lineage-audit.js');const r=a.runSecondaryImpactClusterSplitLineageAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
