import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const moduleUrl=new URL('../dist/game/threat-impact-readability-contrast-rendering.js',import.meta.url);
async function load(){return import(moduleUrl.href+'?v='+Date.now());}
test('Phase 4167 projectile body and trail maintain a minimum readability contrast gap',async()=>{const {projectileReadabilityContrastPresentation}=await load();const p=projectileReadabilityContrastPresentation({bodyFloor:.4,trailScale:.7,critical:false,bossActive:false,crowd:1},false);assert.ok(p.bodyAlphaFloor>=.4);assert.ok(p.trailScale<=.7);assert.ok(p.minimumGap>=.12);});
test('Phase 4168 impact edge remains decisively stronger than interior decoration',async()=>{const {impactReadabilityContrastPresentation}=await load();const p=impactReadabilityContrastPresentation({edgeFloor:.45,fillScale:.6,critical:true,bossActive:true,crowd:1},false);assert.ok(p.edgeAlphaFloor>=.45);assert.ok(p.fillScale<=.6);assert.ok(p.minimumGap>=.14);});
test('Phase 4169 hazard boundary contrast increases without raising hazard interior',async()=>{const {hazardReadabilityContrastPresentation}=await load();const p=hazardReadabilityContrastPresentation({edgeFloor:.5,fillScale:.6,telegraph:true,critical:true,crowd:1},false);assert.ok(p.edgeAlphaFloor>=.5);assert.ok(p.fillScale<=.6);});
test('Phase 4170 safe lane path contrast is protected during critical boss pressure',async()=>{const {safeLaneReadabilityContrastPresentation}=await load();const p=safeLaneReadabilityContrastPresentation({pathFloor:.72,confidence:.9,critical:true,bossActive:true,crowd:1},false);assert.ok(p.pathAlphaFloor>=.72);assert.ok(p.decorativeScale<1);});
test('Phase 4171 specialist silhouette and recovery trail retain a stable contrast gap',async()=>{const {specialistReadabilityContrastPresentation}=await load();const p=specialistReadabilityContrastPresentation({silhouetteFloor:.52,trailScale:.65,owner:'special',critical:true,crowd:1},false);assert.ok(p.silhouetteAlphaFloor>=.52);assert.ok(p.trailScale<=.65);assert.ok(p.minimumGap>=.12);});
test('Phase 4172 contrast budget preserves primary layers and tightens only secondary layers',async()=>{const {readabilityContrastBudgetPresentation}=await load();const p=readabilityContrastBudgetPresentation({criticalCount:2,crowd:1,bossActive:true,safeLaneVisible:true},false,false);assert.equal(p.primaryScale,1);assert.ok(p.secondaryScale<1);assert.ok(p.safeLaneScale>=1);});
test('Phase 4167-4172 live renderers compose floor and ceiling into final contrast',()=>{const e=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8'),s=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8'),g=fs.readFileSync(new URL('../src/game/game.ts',import.meta.url),'utf8');assert.match(e,/projectileReadabilityContrastPresentation/);assert.match(e,/specialistReadabilityContrastPresentation/);assert.match(s,/impactReadabilityContrastPresentation/);assert.match(g,/hazardReadabilityContrastPresentation/);assert.match(g,/safeLaneReadabilityContrastPresentation/);});
