import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const u=new URL('../src/game/secondary-impact-lineage-label-priority-rendering.ts',import.meta.url);const spells=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');async function load(){assert.equal(fs.existsSync(u),true);return import('../dist/game/secondary-impact-lineage-label-priority-rendering.js');}
const c=(lineageKey,heldCount,ttl=.1,budgetVisible=true)=>({lineageKey,heldCount,ttl,budgetVisible});
test('phase 3279 secondary lineage label priority module exists',async()=>{const m=await load();assert.equal(typeof m.secondaryImpactLineageLabelPriorityOrder,'function');});
test('phase 3280 higher held-count lineage receives placement opportunity before lower count',async()=>{const m=await load();const r=m.secondaryImpactLineageLabelPriorityOrder([c('a',2),c('b',6),c('c',3)]);assert.deepEqual(r.map(x=>x.lineageKey),['b','c','a']);});
test('phase 3281 equal counts use ttl then lineage key for deterministic order',async()=>{const m=await load();const r=m.secondaryImpactLineageLabelPriorityOrder([c('z',4,.08),c('b',4,.12),c('a',4,.12)]);assert.deepEqual(r.map(x=>x.lineageKey),['a','b','z']);});
test('phase 3282 singleton budget-hidden and expired lineages never consume placement priority',async()=>{const m=await load();const r=m.secondaryImpactLineageLabelPriorityOrder([c('a',1),c('b',3,.1,false),c('c',4,0,true),c('d',2,.1,true)]);assert.deepEqual(r.map(x=>x.lineageKey),['d']);});
test('phase 3283 priority ordering is stable across input permutation',async()=>{const m=await load();const a=m.secondaryImpactLineageLabelPriorityOrder([c('x',4),c('y',7),c('z',3)]),b=m.secondaryImpactLineageLabelPriorityOrder([c('z',3),c('x',4),c('y',7)]);assert.deepEqual(a,b);});
test('phase 3284 SpellSystem places eligible secondary labels in priority order with presentation-only audit',async()=>{const s=spells();assert.match(s,/secondaryImpactLineageLabelPriorityOrder/);const a=await import('../dist/game/secondary-impact-lineage-label-priority-audit.js');const r=a.runSecondaryImpactLineageLabelPriorityAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.passed,true);});
