import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/projectile-impact-arrival-handoff-rendering.ts',import.meta.url);const spellSource=fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/projectile-impact-arrival-handoff-rendering.js');}
test('phase 3099 projectile impact arrival handoff module exists',async()=>{const m=await load();assert.equal(typeof m.projectileImpactEntryOffset,'function');assert.equal(typeof m.projectileImpactVisualPosition,'function');});
test('phase 3100 collision captures only the residual visual launch displacement',async()=>{const {projectileImpactEntryOffset}=await load();const o=projectileImpactEntryOffset({x:-20,y:8},.05,.1);assert.ok(o.x<0&&Math.abs(o.x)<20);assert.ok(o.y>0&&o.y<8);});
test('phase 3101 impact stamp begins at arrival owner then settles to canonical impact point',async()=>{const {projectileImpactVisualPosition}=await load();const start=projectileImpactVisualPosition({x:200,y:100},{x:-8,y:4},.18,.18);const mid=projectileImpactVisualPosition({x:200,y:100},{x:-8,y:4},.09,.18);const end=projectileImpactVisualPosition({x:200,y:100},{x:-8,y:4},0,.18);assert.ok(start.x<mid.x&&mid.x<200);assert.deepEqual(end,{x:200,y:100});});
test('phase 3102 zero residual offset leaves impact presentation canonical',async()=>{const {projectileImpactEntryOffset,projectileImpactVisualPosition}=await load();const o=projectileImpactEntryOffset({x:-20,y:8},0,.1);assert.deepEqual(o,{x:0,y:0});assert.deepEqual(projectileImpactVisualPosition({x:20,y:30},o,.1,.18),{x:20,y:30});});
test('phase 3103 reduced motion compresses impact arrival carry without changing canonical destination',async()=>{const {projectileImpactEntryOffset}=await load();const f=projectileImpactEntryOffset({x:-18,y:8},.08,.1,false),r=projectileImpactEntryOffset({x:-18,y:8},.08,.1,true);assert.ok(Math.hypot(r.x,r.y)<Math.hypot(f.x,f.y));});
test('phase 3104 hero archer and boss impact stamps carry visual entry offset while gameplay impact positions stay canonical',async()=>{assert.match(spellSource,/entryOffset/);assert.match(spellSource,/projectileImpactVisualPosition/);assert.match(enemySource,/entryOffset/);assert.match(enemySource,/projectileImpactVisualPosition/);assert.match(enemySource,/pos:\{\.\.\.p\.pos\}/);const a=await import('../dist/game/projectile-impact-arrival-handoff-audit.js');const audit=a.runProjectileImpactArrivalHandoffAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
