import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const moduleUrl=new URL('../src/game/secondary-impact-lineage-label-anchor-rendering.ts',import.meta.url);const lineageUrl=new URL('../src/game/secondary-impact-cluster-split-lineage-rendering.ts',import.meta.url);const spellSource=()=>fs.readFileSync(new URL('../src/game/spells.ts',import.meta.url),'utf8');
async function load(){assert.equal(fs.existsSync(moduleUrl),true);assert.equal(fs.existsSync(lineageUrl),true);return{label:await import('../dist/game/secondary-impact-lineage-label-anchor-rendering.js'),lineage:await import('../dist/game/secondary-impact-cluster-split-lineage-rendering.js')};}
test('phase 3225 secondary impact lineage label-anchor module exists',async()=>{const m=await load();assert.equal(typeof m.label.secondaryImpactLineageLabelPresentation,'function');assert.equal(typeof m.lineage.secondaryImpactActiveLineageAnchorFor,'function');});
test('phase 3226 active lineage exposes its canonical presentation anchor',async()=>{const m=await load();let s=m.lineage.advanceSecondaryImpactClusterSplitLineage(m.lineage.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:210,y:220}},{pos:{x:222,y:224}}],.016);const key=m.lineage.secondaryImpactSplitLineageFor(s,{x:216,y:222}).key;const anchor=m.lineage.secondaryImpactActiveLineageAnchorFor(s,key);assert.ok(anchor);assert.equal(anchor.key,key);assert.ok(Math.abs(anchor.pos.x-216)<8);});
test('phase 3227 retired child lineage never owns a count-label anchor after merge',async()=>{const m=await load();let s=m.lineage.advanceSecondaryImpactClusterSplitLineage(m.lineage.createSecondaryImpactClusterSplitLineageState(),[{pos:{x:188,y:220}},{pos:{x:312,y:220}}],.016);const oldRight=m.lineage.secondaryImpactSplitLineageFor(s,{x:312,y:220}).key;s=m.lineage.advanceSecondaryImpactClusterSplitLineage(s,[{pos:{x:250,y:220}}],.04);assert.equal(m.lineage.secondaryImpactActiveLineageAnchorFor(s,oldRight),null);});
test('phase 3228 active lineage label uses held count once and stays anchored above the lineage center',async()=>{const m=await load();const p=m.label.secondaryImpactLineageLabelPresentation({lineageKey:'lineage-3',anchor:{x:260,y:212},heldCount:4,ttl:.12,maxTtl:.14,budgetVisible:true},false);assert.equal(p.visible,true);assert.equal(p.text,'×4');assert.equal(p.pos.x,260);assert.ok(p.pos.y<212);});
test('phase 3229 unbound retired or singleton secondary impacts do not create duplicate labels',async()=>{const m=await load();const unbound=m.label.secondaryImpactLineageLabelPresentation({lineageKey:'unbound:3:4',anchor:{x:220,y:220},heldCount:4,ttl:.12,maxTtl:.14,budgetVisible:true},false);const retired=m.label.secondaryImpactLineageLabelPresentation({lineageKey:'lineage-9',anchor:undefined,heldCount:5,ttl:.12,maxTtl:.14,budgetVisible:true},false);const singleton=m.label.secondaryImpactLineageLabelPresentation({lineageKey:'lineage-2',anchor:{x:220,y:220},heldCount:1,ttl:.12,maxTtl:.14,budgetVisible:true},false);assert.equal(unbound.visible,false);assert.equal(retired.visible,false);assert.equal(singleton.visible,false);});
test('phase 3230 live secondary render consumes lineage anchor for one cycle-safe count label with presentation-only audit',async()=>{const s=spellSource();assert.match(s,/secondaryImpactActiveLineageAnchorFor/);assert.match(s,/secondaryImpactLineageLabelPresentation/);assert.match(s,/secondaryLineageLabels/);const a=await import('../dist/game/secondary-impact-lineage-label-anchor-audit.js');const r=a.runSecondaryImpactLineageLabelAnchorAudit();assert.equal(r.actionCount,9);assert.equal(r.presentationOnly,true);assert.equal(r.gameplayFormulaMutation,false);assert.equal(r.snapshotSchemaMutation,false);assert.equal(r.newAtlasCount,0);assert.equal(r.passed,true);});
