import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const enemySource=fs.readFileSync(new URL('../src/game/enemies.ts',import.meta.url),'utf8');
const moduleUrl=new URL('../src/game/specialist-turn-stop-rendering.ts',import.meta.url);
async function loadModule(){assert.equal(fs.existsSync(moduleUrl),true);return import('../dist/game/specialist-turn-stop-rendering.js');}
const motion=(overrides={})=>({motionBlend:0.7,stride:1,facingX:1,facingY:0,turn:0.65,recovery:0.2,...overrides});
const signature=(overrides={})=>({arrival:0,brace:0,plant:0,...overrides});

test('phase 2955 specialist turn stop module exists',async()=>{const mod=await loadModule();assert.equal(typeof mod.specialistTurnStopPresentation,'function');});
test('phase 2956 assassin blink exit preserves directional lean through turn',async()=>{const mod=await loadModule();const p=mod.specialistTurnStopPresentation('assassin',motion(),signature({arrival:0.9}),false);const idle=mod.specialistTurnStopPresentation('assassin',motion({turn:0,recovery:0}),signature(),false);assert.ok(p.exit>0.45);assert.ok(p.offsetX>idle.offsetX);assert.ok(Math.abs(p.rotation)>Math.abs(idle.rotation));assert.ok(p.directionRetention>0.45);});
test('phase 2957 shieldbearer reorients from brace around a wider anchored stance',async()=>{const mod=await loadModule();const p=mod.specialistTurnStopPresentation('shieldbearer',motion({turn:-0.8,motionBlend:0.35,recovery:0.45}),signature({brace:0.8}),false);assert.ok(p.bracePivot>0.3);assert.ok(p.scaleX>p.scaleY);assert.ok(p.groundAnchor>0.4);assert.ok(p.rotation<0);});
test('phase 2958 siege golem stop settles heavier while nullifier pivot remains restrained',async()=>{const mod=await loadModule();const golem=mod.specialistTurnStopPresentation('siegeGolem',motion({motionBlend:0.08,turn:0.5,recovery:0.95}),signature({plant:0.25}),false);const nullifier=mod.specialistTurnStopPresentation('nullifier',motion({motionBlend:0.08,turn:0.5,recovery:0.95}),signature(),false);assert.ok(golem.stop>0.7);assert.ok(golem.offsetY>nullifier.offsetY);assert.ok(Math.abs(golem.rotation)<=0.09);assert.ok(Math.abs(nullifier.rotation)<=0.08);});
test('phase 2959 reduced motion keeps specialist turn stop identity with compressed displacement',async()=>{const mod=await loadModule();const m=motion({turn:0.8,recovery:0.7});const s=signature({arrival:0.8});const full=mod.specialistTurnStopPresentation('assassin',m,s,false);const reduced=mod.specialistTurnStopPresentation('assassin',m,s,true);assert.equal(reduced.exit,full.exit);assert.equal(reduced.stop,full.stop);assert.ok(Math.hypot(reduced.offsetX,reduced.offsetY)<Math.hypot(full.offsetX,full.offsetY));assert.ok(Math.abs(reduced.rotation)<=Math.abs(full.rotation));});
test('phase 2960 enemy render integrates specialist turn stop layer and deterministic audit stays presentation-only',async()=>{assert.match(enemySource,/specialistTurnStopPresentation/);assert.match(enemySource,/specialistTurnStop/);assert.match(enemySource,/renderMotion/);assert.match(enemySource,/specialistLocomotionSignature/);assert.equal(fs.existsSync(new URL('../src/game/specialist-turn-stop-audit.ts',import.meta.url)),true);const mod=await import('../dist/game/specialist-turn-stop-audit.js');const audit=mod.runSpecialistTurnStopAudit();assert.equal(audit.samples.length,64);assert.equal(audit.actionCount,9);assert.equal(audit.presentationOnly,true);assert.equal(audit.gameplayFormulaMutation,false);assert.equal(audit.snapshotSchemaMutation,false);assert.equal(audit.newAtlasCount,0);assert.equal(audit.passed,true);});
